const archetypeArray = [
	{
		id: 'idealist',
		archetype: 'Idealist',
		honestyHumility: 'high',
		emotionality: 'high',
		extraversion: 'low',
		agreeableness: 'high',
		conscientiousness: 'low',
		opennessToExperience: 'low',
		altruism: 'high',
		leastH: 'H3',
		leastE: 'E1',
		leastX: 'X2',
		leastA: 'A3',
		leastC: 'C3',
		leastO: 'O2',
	},
	{
		id: 'realist',
		archetype: 'Realist',
		honestyHumility: 'low',
		emotionality: 'high',
		extraversion: 'low',
		agreeableness: 'low',
		conscientiousness: 'high',
		opennessToExperience: 'low',
		altruism: 'high',
		leastH: 'H4',
		leastE: 'E4',
		leastX: 'X2',
		leastA: 'A4',
		leastC: 'C4',
		leastO: 'O3',
	},
	{
		id: 'caregiver',
		archetype: 'Fürsorger',
		honestyHumility: 'high',
		emotionality: 'high',
		extraversion: 'low',
		agreeableness: 'high',
		conscientiousness: 'high',
		opennessToExperience: 'low',
		altruism: 'high',
		leastH: 'H3',
		leastE: 'E1',
		leastX: 'X2',
		leastA: 'A3',
		leastC: 'C3',
		leastO: 'O4',
	},
	{
		id: 'warrior',
		archetype: 'Krieger',
		honestyHumility: 'low',
		emotionality: 'low',
		extraversion: 'high',
		agreeableness: 'low',
		conscientiousness: 'high',
		opennessToExperience: 'high',
		altruism: 'low',
		leastH: 'H3',
		leastE: 'E4',
		leastX: 'X3',
		leastA: 'A2',
		leastC: 'C1',
		leastO: 'O1',
	},
	{
		id: 'seeker',
		archetype: 'Sucher',
		honestyHumility: 'low',
		emotionality: 'low',
		extraversion: 'high',
		agreeableness: 'low',
		conscientiousness: 'low',
		opennessToExperience: 'high',
		altruism: 'low',
		leastH: 'H2',
		leastE: 'E4',
		leastX: 'X1',
		leastA: 'A2',
		leastC: 'C3',
		leastO: 'O1',
	},
	{
		id: 'lover',
		archetype: 'Liebhaber',
		honestyHumility: 'low',
		emotionality: 'high',
		extraversion: 'high',
		agreeableness: 'high',
		conscientiousness: 'low',
		opennessToExperience: 'high',
		altruism: 'high',
		leastH: 'H3',
		leastE: 'E1',
		leastX: 'X1',
		leastA: 'A3',
		leastC: 'C1',
		leastO: 'O2',
	},
	{
		id: 'creator',
		archetype: 'Schöpfer',
		honestyHumility: 'low',
		emotionality: 'low',
		extraversion: 'low',
		agreeableness: 'high',
		conscientiousness: 'high',
		opennessToExperience: 'high',
		altruism: 'low',
		leastH: 'H3',
		leastE: 'E1',
		leastX: 'X3',
		leastA: 'A1',
		leastC: 'C4',
		leastO: 'O4',
	},
	{
		id: 'revolutionary',
		archetype: 'Revolutionär',
		honestyHumility: 'low',
		emotionality: 'high',
		extraversion: 'high',
		agreeableness: 'low',
		conscientiousness: 'low',
		opennessToExperience: 'high',
		altruism: 'low',
		leastH: 'H3',
		leastE: 'E1',
		leastX: 'X1',
		leastA: 'A2',
		leastC: 'C4',
		leastO: 'O1',
	},
	{
		id: 'sage',
		archetype: 'Weiser',
		honestyHumility: 'high',
		emotionality: 'low',
		extraversion: 'low',
		agreeableness: 'low',
		conscientiousness: 'high',
		opennessToExperience: 'high',
		altruism: 'high',
		leastH: 'H3',
		leastE: 'E4',
		leastX: 'X4',
		leastA: 'A2',
		leastC: 'C2',
		leastO: 'O1',
	},
	{
		id: 'magician',
		archetype: 'Magier',
		honestyHumility: 'low',
		emotionality: 'low',
		extraversion: 'high',
		agreeableness: 'high',
		conscientiousness: 'high',
		opennessToExperience: 'high',
		altruism: 'high',
		leastH: 'H4',
		leastE: 'E1',
		leastX: 'X2',
		leastA: 'A2',
		leastC: 'C1',
		leastO: 'O1',
	},
	{
		id: 'ruler',
		archetype: 'Herrscher',
		honestyHumility: 'low',
		emotionality: 'low',
		extraversion: 'high',
		agreeableness: 'low',
		conscientiousness: 'high',
		opennessToExperience: 'low',
		altruism: 'high',
		leastH: 'H3',
		leastE: 'E4',
		leastX: 'X4',
		leastA: 'A2',
		leastC: 'C3',
		leastO: 'O1',
	},
	{
		id: 'fool',
		archetype: 'Narr',
		honestyHumility: 'low',
		emotionality: 'low',
		extraversion: 'high',
		agreeableness: 'high',
		conscientiousness: 'low',
		opennessToExperience: 'high',
		altruism: 'low',
		leastH: 'H3',
		leastE: 'E3',
		leastX: 'X1',
		leastA: 'A1',
		leastC: 'C3',
		leastO: 'O2',
	},
];
