const facetArray = [
	{
		name: 'H1',
		domain: 'H',
		descriptionHigh: 'ist nicht bereit, andere zu manipulieren',
		adjectiveHigh: 'aufrichtig',
		itemHigh1: 'verwendet keine Schmeicheleien, um Vorteile zu erzielen',
		itemHigh2: 'vermeidet es, Zuneigung vorzutäuschen, um sich Vorteile zu verschaffen',
		itemHigh3: 'lehnt es ab, freundliches Verhalten aus taktischem Kalkül zu zeigen',
		itemHigh4: 'verzichtet auf vorgetäuschte Zustimmung, um sich einen Vorteil zu sichern',
		descriptionLow:
			'wird anderen schmeicheln oder vorgeben, sie zu mögen, um sich Vorteile zu verschaffen',
		adjectiveLow: 'manipulativ',
		itemLow1:
			'zeigt taktisch-freundliches Verhalten gegenüber Personen, die nicht geschätzt werden',
		itemLow2: 'reagiert positiv auf humorlose Beiträge, um sich einen Vorteil zu verschaffen',
		itemLow3: 'nutzt schmeichelndes Verhalten zur Erreichung von Zielen',
		itemLow4: 'täuscht positive Gefühle vor, um Unterstützung zu erhalten',
	},
	{
		name: 'H2',
		domain: 'H',
		descriptionHigh:
			'lehnt es ab, materielle Vorteile durch unrechtmäßige Angebote zu erhalten',
		adjectiveHigh: 'rechtschaffen',
		itemHigh1: 'vermeidet Eigentumsdelikte, auch wenn keine Konsequenzen drohen',
		itemHigh2: 'meidet den Erwerb unrechtmäßig erlangter Güter, unabhängig vom eigenen Bedarf',
		itemHigh3:
			'verzichtet auf den Gebrauch gefälschter Zahlungsmittel, selbst bei Straffreiheit',
		itemHigh4: 'verwendet kein Falschgeld, selbst wenn Entdeckung ausgeschlossen ist',
		descriptionLow: 'ist bereit, durch Betrug oder Diebstahl sich zu bereichern',
		adjectiveLow: 'unredlich',
		itemLow1: 'würde einen sehr hohen Geldbetrag stehlen, wenn keinerlei Konsequenzen drohen',
		itemLow2: 'fühlt sich versucht, gestohlene Waren zu kaufen, wenn finanzielle Not besteht',
		itemLow3: 'lässt sich verleiten, Falschgeld zu benutzen, wenn es risikolos erscheint',
		itemLow4: 'akzeptiert eine Bestechung, wenn die Belohnung hoch genug ist',
	},
	{
		name: 'H3',
		domain: 'H',
		descriptionHigh:
			'ist nicht besonders durch finanzielle oder soziale Statusüberlegungen motiviert',
		adjectiveHigh: 'bescheiden',
		itemHigh1: 'legt wenig Wert auf finanziellen Reichtum',
		itemHigh2: 'bevorzugt keinen Wohnort mit hohem gesellschaftlichem Ansehen',
		itemHigh3: 'entscheidet sich bei Kleidung eher für praktische als luxuriöse Varianten',
		itemHigh4: 'bewertet schlichte Gegenstände höher als exklusive Luxusprodukte',
		descriptionLow: 'will Reichtum und Privilegien genießen und zur Schau stellen',
		adjectiveLow: 'materialistisch',
		itemLow1: 'strebt nach einem Wohnumfeld mit hohem sozialem Status',
		itemLow2: 'legt Wert darauf, mit exklusiver Kleidung aufzufallen',
		itemLow3: 'erlebt den Besitz teurer Konsumgüter als besonders befriedigend',
		itemLow4: 'betrachtet materiellen Wohlstand als vorrangiges Lebensziel',
	},
	{
		name: 'H4',
		domain: 'H',
		descriptionHigh:
			'sieht sich selbst als eine gewöhnliche Person, die keinen Anspruch auf Sonderbehandlung erhebt',
		adjectiveHigh: 'demütig',
		itemHigh1: 'beschreibt sich als gewöhnliche Person ohne Anspruch auf Überlegenheit',
		itemHigh2: 'lehnt es ab, bevorzugt behandelt zu werden',
		itemHigh3: 'äußert nicht den Anspruch, mehr Respekt zu verdienen als andere',
		itemHigh4:
			'zeigt kein Interesse daran, als wichtig oder hochgestellt wahrgenommen zu werden',
		descriptionLow:
			'betrachtet sich selbst als überlegen und als berechtigt, Privilegien zu genießen, die andere nicht haben',
		adjectiveLow: 'überheblich',
		itemLow1: 'hält sich für respektwürdiger als den Durchschnitt',
		itemLow2: 'möchte als bedeutende und statushohe Person wahrgenommen werden',
		itemLow3: 'bewertet sich selbst als überlegen gegenüber durchschnittlichen Personen',
		itemLow4: 'empfindet es als angenehm, als besondere Person behandelt zu werden',
	},
	{
		name: 'E1',
		domain: 'E',
		descriptionHigh: 'neigt stark dazu, körperliche Schäden zu vermeiden',
		adjectiveHigh: 'ängstlich',
		itemHigh1: 'fühlt sich bei Reisen unter gefährlichen Bedingungen ängstlich',
		itemHigh2: 'reagiert sehr furchtsam auf körperliche Gefahren',
		itemHigh3: 'vermeidet berufliche Tätigkeiten mit physischem Risiko',
		itemHigh4: 'verliert in Drucksituationen leicht die Fassung',
		descriptionLow:
			'hat wenig Angst vor Verletzungen und ist relativ zäh, tapfer und unempfindlich gegenüber körperlichen Schmerzen',
		adjectiveLow: 'furchtlos',
		itemLow1: 'akzeptiert gefährliche Tätigkeiten ohne große Bedenken',
		itemLow2: 'bewahrt auch in Notfällen innere Ruhe',
		itemLow3: 'reist selbst bei potenziellen Gefahren mit Zuversicht',
		itemLow4: 'zeigt keine Angstreaktionen bei körperlicher Bedrohung',
	},
	{
		name: 'E2',
		domain: 'E',
		descriptionHigh: 'neigt dazu, sich auch mit relativ kleinen Problemen zu beschäftigen',
		adjectiveHigh: 'sorgenvoll',
		itemHigh1: 'macht sich auch über Kleinigkeiten häufig Sorgen',
		itemHigh2: 'empfindet starke Anspannung beim Warten auf wichtige Entscheidungen',
		itemHigh3: 'fühlt sich oft besorgter als andere in vergleichbaren Situationen',
		itemHigh4: 'schläft schlecht bei anhaltenden Sorgen',
		descriptionLow: 'verspürt wenig Stress als Reaktion auf Widrigkeiten',
		adjectiveLow: 'gelassen',
		itemLow1: 'macht sich deutlich weniger Sorgen als die meisten anderen',
		itemLow2: 'schläft auch unter Stressbedingungen in der Regel problemlos',
		itemLow3: 'reagiert gelassen auf kleinere Alltagsprobleme',
		itemLow4: 'geht mit Entscheidungssituationen um, ohne ängstlich zu werden',
	},
	{
		name: 'E3',
		domain: 'E',
		descriptionHigh:
			'möchte die eigenen Schwierigkeiten mit denen teilen, die einem Mut machen und Trost spenden',
		adjectiveHigh: 'hilfesuchend',
		itemHigh1: 'sucht Trost bei anderen nach schmerzhaften Erfahrungen',
		itemHigh2: 'teilt Sorgen bevorzugt mit anderen Personen',
		itemHigh3: 'verlässt sich in schwierigen Zeiten häufig auf emotionale Unterstützung',
		itemHigh4: 'fühlt sich besser, wenn Probleme mit jemandem besprochen werden',
		descriptionLow:
			'fühlt sich selbstbewusst und in der Lage, Probleme ohne Hilfe oder Ratschläge zu bewältigen',
		adjectiveLow: 'selbstgenügsam',
		itemLow1: 'meidet emotionale Unterstützung in belastenden Situationen',
		itemLow2: 'spricht selten über persönliche Probleme',
		itemLow3: 'bewältigt belastende Erfahrungen lieber allein',
		itemLow4: 'geht mit Sorgen in der Regel ohne Austausch mit anderen um',
	},
	{
		name: 'E4',
		domain: 'E',
		descriptionHigh:
			'empfindet eine starke emotionale Bindung und eine empathische Sensibilität für die Gefühle anderer',
		adjectiveHigh: 'empathisch',
		itemHigh1: 'fühlt sich nach weinen, wenn andere weinen',
		itemHigh2: 'empfindet den Schmerz nahestehender Personen mit',
		itemHigh3: 'reagiert emotional, wenn vertraute Personen für längere Zeit Abschied nehmen',
		itemHigh4: 'wird leicht von gefühlvollen Situationen berührt',
		descriptionLow:
			'zeigt wenig Emotionen beim Abschiednehmen oder als Reaktion auf die Sorgen anderer',
		adjectiveLow: 'gefühlskalt',
		itemLow1: 'bleibt selbst in stark gefühlsbetonten Situationen nüchtern',
		itemLow2: 'reagiert kaum emotional auf das Weinen anderer',
		itemLow3: 'zeigt nur geringe emotionale Reaktion, wenn andere Personen unglücklich sind',
		itemLow4: 'empfindet bei Abschieden selten starke Gefühle',
	},
	{
		name: 'X1',
		domain: 'X',
		descriptionHigh:
			'ist im Allgemeinen mit sich selbst zufrieden und hält sich für sympathisch',
		adjectiveHigh: 'selbstzufrieden',
		itemHigh1: 'empfindet grundsätzlich Zufriedenheit mit sich selbst',
		itemHigh2:
			'geht davon aus, dass andere bestimmte Aspekte der eigenen Persönlichkeit schätzen',
		itemHigh3: 'kommt mit den meisten Personen gut zurecht',
		itemHigh4: 'erlebt sich selbst als wertvolle Person',
		descriptionLow:
			'neigt dazu, ein Gefühl der persönlichen Wertlosigkeit zu haben und sich selbst als unbeliebt zu sehen',
		adjectiveLow: 'selbstkritisch',
		itemLow1: 'fühlt sich unbeliebt im sozialen Umfeld',
		itemLow2: 'zweifelt oft am eigenen Wert',
		itemLow3: 'zeigt häufig Unzufriedenheit mit der eigenen Person',
		itemLow4: 'nimmt an, dass wenig an der eigenen Persönlichkeit geschätzt wird',
	},
	{
		name: 'X2',
		domain: 'X',
		descriptionHigh: 'ist bereit, auf Fremde zuzugehen und sich in Gruppen zu Wort zu melden',
		adjectiveHigh: 'durchsetzungsfähig',
		itemHigh1: 'ergreift in sozialen Situationen häufig als erste Person die Initiative',
		itemHigh2: 'äußert sich stellvertretend für Gruppen in gemeinschaftlichen Kontexten',
		itemHigh3: 'teilt persönliche Meinungen regelmäßig in Gruppengesprächen',
		itemHigh4: 'fühlt sich bei öffentlichen Redebeiträgen weder nervös noch gehemmt',
		descriptionLow:
			'fühlt sich in Führungspositionen oder beim Sprechen in der Öffentlichkeit schüchtern oder unbehaglich',
		adjectiveLow: 'schüchtern',
		itemLow1: 'bringt in Gruppengesprächen selten eigene Meinungen ein',
		itemLow2: 'fühlt sich beim Sprechen vor Gruppen häufig unsicher',
		itemLow3: 'gibt meist anderen den Vortritt die Initiative in sozialen Situationen',
		itemLow4: 'überlässt es anderen, im Namen der Gruppe zu sprechen',
	},
	{
		name: 'X3',
		domain: 'X',
		descriptionHigh: 'freut sich über Gespräche, Besuche und gemeinsame Feiern mit anderen',
		adjectiveHigh: 'gesellig',
		itemHigh1: 'genießt es, von vielen Person umgeben zu sein und Gespräche zu führen',
		itemHigh2:
			'bevorzugt Tätigkeiten mit aktiver sozialer Interaktion gegenüber alleiniger Arbeit',
		itemHigh3: 'knüpft in neuen Umgebungen rasch soziale Kontakte',
		itemHigh4: 'führt gerne beiläufige Gespräche mit anderen',
		descriptionLow: 'bevorzugt Einzelaktivitäten und vermeidet Unterhaltungen',
		adjectiveLow: 'zurückgezogen',
		itemLow1: 'vermeidet oberflächliche Gespräche mit Fremden',
		itemLow2: 'zieht ruhige Umgebungen ohne viel Kommunikation vor',
		itemLow3: 'arbeitet lieber allein als im ständigen Austausch mit anderen',
		itemLow4:
			'empfindet keine Notwendigkeit, in neuen Situationen sofort Freundschaften zu schließen',
	},
	{
		name: 'X4',
		domain: 'X',
		descriptionHigh: 'verspürt Optimismus und gute Laune',
		adjectiveHigh: 'optimistisch',
		itemHigh1: 'wirkt fast durchgängig energiegeladen',
		itemHigh2: 'zeigt sich an den meisten Tagen fröhlich und optimistisch',
		itemHigh3: 'verbreitet häufig eine positive Stimmung im sozialen Umfeld',
		itemHigh4: 'tritt lebhafter und heiterer auf als die meisten anderen',
		descriptionLow: 'neigt dazu, sich nicht besonders fröhlich oder energiegeladen zu fühlen',
		adjectiveLow: 'pessimistisch',
		itemLow1: 'hört öfter von anderen, dass mehr Heiterkeit guttun würde',
		itemLow2: 'wirkt weniger dynamisch als der Durchschnitt',
		itemLow3: 'fühlt sich häufig erschöpft oder energielos',
		itemLow4: 'erlebt sich meist als niedergeschlagen oder pessimistisch',
	},
	{
		name: 'A1',
		domain: 'A',
		descriptionHigh:
			'ist in der Regel bereit, nach schlechter Behandlung durch andere wieder zu vertrauen und freundschaftliche Beziehungen wieder aufzubauen',
		adjectiveHigh: 'verzeihend',
		itemHigh1: 'hegt selten Groll – selbst gegenüber Personen, die stark geschadet haben',
		itemHigh2: 'verfolgt gegenüber unfairer Behandlung das Prinzip „vergeben und vergessen“',
		itemHigh3: 'bemüht sich auch nach Verletzungen darum, Vertrauen wieder aufzubauen',
		itemHigh4: 'findet meist die Bereitschaft, anderen aufrichtig zu vergeben',
		descriptionLow: 'neigt dazu, einen Groll gegenüber denen zu hegen, die man beleidigt haben',
		adjectiveLow: 'nachtragend',
		itemLow1: 'bleibt dauerhaft misstrauisch gegenüber Personen, die einmal getäuscht haben',
		itemLow2: 'empfindet vollständige Vergebung gegenüber gemeinem Verhalten als schwierig',
		itemLow3: 'trägt lange das erlittene Unrecht mit sich',
		itemLow4: 'hält Personen, die Schaden verursacht haben, für unverzeihlich',
	},
	{
		name: 'A2',
		domain: 'A',
		descriptionHigh: 'ist zurückhaltend, andere hart zu beurteilen',
		adjectiveHigh: 'nachsichtig',
		itemHigh1: 'akzeptiert die Fehler anderer im Allgemeinen ohne zu klagen',
		itemHigh2: 'tendiert zu einer nachsichtigen Beurteilung anderer Personen',
		itemHigh3: 'sagt selten etwas Negatives, auch wenn viele Fehler gemacht werden',
		itemHigh4: 'wird von anderen als tolerant und locker empfunden',
		descriptionLow: 'neigt dazu, andere kritisch zu beurteilen',
		adjectiveLow: 'kritisch',
		itemLow1: 'kritisiert andere oft zu streng',
		itemLow2: 'fällt es schwer, Fehler anderer zu ignorieren',
		itemLow3: 'urteilt schnell bei Fehlern anderer Personen',
		itemLow4: 'zögert nicht, Fehler wiederholt auftretender Personen zu kritisieren',
	},
	{
		name: 'A3',
		domain: 'A',
		descriptionHigh:
			'vermeidet Streitigkeiten und geht auf die Vorschläge anderer ein, auch wenn diese unvernünftig sein mögen',
		adjectiveHigh: 'kompromissbereit',
		itemHigh1: 'zeigt meist Flexibilität in der eigenen Meinung, wenn andere widersprechen',
		itemHigh2: 'gilt häufig als gelassen und aufgeschlossen',
		itemHigh3:
			'bemüht sich, ruhig zu bleiben und andere Ansichten zu berücksichtigen statt zu streiten',
		itemHigh4:
			'ist bereit, Kompromisse einzugehen, auch wenn die eigene Meinung richtig erscheint',
		descriptionLow: 'gilt als stur und ist streitlustig',
		adjectiveLow: 'streitlustig',
		itemLow1: 'wird häufig als zu stur wahrgenommen',
		itemLow2: 'reagiert bei Widerspruch oft mit Gegenargumenten',
		itemLow3:
			'fällt es schwer, Kompromisse einzugehen, wenn die eigene Meinung als richtig gilt',
		itemLow4: 'ändert selten die eigene Meinung, selbst wenn andere widersprechen',
	},
	{
		name: 'A4',
		domain: 'A',
		descriptionHigh: 'hat eine große Hemmschwelle, Wut zu fühlen oder auszudrücken',
		adjectiveHigh: 'ausgeglichen',
		itemHigh1: 'zeigt selbst bei schlechter Behandlung selten Wut',
		itemHigh2: 'reagiert weniger schnell mit Ärger als die meisten Personen',
		itemHigh3: 'wird als ruhig und ausgeglichen wahrgenommen',
		itemHigh4: 'verliert selten die Beherrschung, auch in frustrierenden Situationen',
		descriptionLow: 'neigt dazu, schnell die Beherrschung zu verlieren',
		adjectiveLow: 'jähzornig',
		itemLow1: 'gilt als jähzornig',
		itemLow2: 'fällt es schwer, die Beherrschung zu bewahren, wenn Beleidigungen erfolgen',
		itemLow3: 'empfindet häufig Ärger bei unfairer Behandlung',
		itemLow4: 'gerät schneller in Rage als die meisten bekannten Personen',
	},
	{
		name: 'C1',
		domain: 'C',
		descriptionHigh:
			'sorgt für Ordnung und bevorzugt eine strukturierte Herangehensweise an Aufgaben',
		adjectiveHigh: 'ordentlich',
		itemHigh1: 'reinigt die Wohn- oder Arbeitsumgebung recht häufig',
		itemHigh2: 'plant voraus und organisiert, um Stress in der letzten Minute zu vermeiden',
		itemHigh3: 'erhält oft Komplimente für die Sauberkeit von Wohn- oder Arbeitsumgebung',
		itemHigh4: 'nutzt Organisationsfähigkeiten, um Schwierigkeiten bei der Arbeit zu vermeiden',
		descriptionLow: 'neigt dazu, unordentlich und planlos zu sein',
		adjectiveLow: 'chaotisch',
		itemLow1: 'wird oft wegen Unordnung in der Wohn- oder Arbeitsumgebung aufgezogen',
		itemLow2: 'hat manchmal Schwierigkeiten bei der Arbeit aufgrund von Unordnung',
		itemLow3: 'sorgt häufig für eine chaotische Umgebung auf Grund von mangelnder Ordnung',
		itemLow4: 'gerät oft in Zeitdruck wegen fehlender Vorausplanung',
	},
	{
		name: 'C2',
		domain: 'C',
		descriptionHigh:
			'verfügt über eine ausgeprägte Arbeitsmoral und ist bereit, sich anzustrengen',
		adjectiveHigh: 'ehrgeizig',
		itemHigh1: 'setzt sich bei der Arbeit häufig ehrgeizige Ziele',
		itemHigh2: 'fordert sich selbst oft stark, um ein Ziel zu erreichen',
		itemHigh3: 'gibt selten auf, bevor Ziele erreicht sind',
		itemHigh4: 'erledigt gerne mehr als das Minimum bei der Arbeit',
		descriptionLow: 'hat wenig Selbstdisziplin und ist wenig motiviert, etwas zu erreichen',
		adjectiveLow: 'antriebslos',
		itemLow1: 'gibt häufig auf, bevor ein gesetztes Ziel erreicht wird',
		itemLow2: 'erledigt meist nur das Minimum, um durchzukommen',
		itemLow3: 'setzt sich selten herausfordernde Ziele bei der Arbeit',
		itemLow4: 'investiert meist wenig Aufwand, um Ziele zu erreichen',
	},
	{
		name: 'C3',
		domain: 'C',
		descriptionHigh: 'überprüft sorgfältig auf Fehler und mögliche Verbesserungen',
		adjectiveHigh: 'gewissenhaft',
		itemHigh1: 'überprüft die eigene Arbeit häufig mehrfach, um Fehler zu finden',
		itemHigh2: 'legt Wert auf Genauigkeit, auch wenn das mehr Zeit kostet',
		itemHigh3: 'gilt oft als perfektionistisch',
		itemHigh4: 'achtet sehr sorgfältig darauf, keine kleinen Details zu übersehen',
		descriptionLow:
			'toleriert einige Fehler in der eigenen Arbeit und neigt dazu, Details zu vernachlässigen',
		adjectiveLow: 'nachlässig',
		itemLow1: 'schenkt kleinen Details bei der Arbeit wenig Beachtung',
		itemLow2: 'sieht selten die Notwendigkeit, die Arbeit nach Abschluss nochmal zu überprüfen',
		itemLow3: 'misst der perfekten Genauigkeit bei der Arbeit wenig Bedeutung bei',
		itemLow4: 'wird selten als detailorientiert oder perfektionistisch beschrieben',
	},
	{
		name: 'C4',
		domain: 'C',
		descriptionHigh:
			'wägt die eigenen Optionen sorgfältig ab und neigt dazu, vorsichtig und selbstbeherrscht zu sein',
		adjectiveHigh: 'selbstbeherrscht',
		itemHigh1: 'lässt Impulse das Verhalten nicht bestimmen',
		itemHigh2: 'denkt Entscheidungen meist sorgfältig durch, bevor gehandelt wird',
		itemHigh3: 'handelt überlegt, um Fehler zu vermeiden',
		itemHigh4: 'folgt meist einem Plan statt spontan zu handeln',
		descriptionLow: 'handelt impulsiv und neigt dazu, die Konsequenzen nicht zu bedenken',
		adjectiveLow: 'impulsiv',
		itemLow1:
			'trifft Entscheidungen eher aus dem Gefühl heraus als durch sorgfältiges Nachdenken',
		itemLow2: 'macht viele Fehler, weil vor dem Handeln nicht nachgedacht wird',
		itemLow3: 'bevorzugt es, spontan zu handeln statt einem Plan zu folgen',
		itemLow4: 'handelt oft nach dem momentanen Gefühl, auch wenn das keine gute Idee ist',
	},
	{
		name: 'O1',
		domain: 'O',
		descriptionHigh:
			'hat eine ausgeprägte Wertschätzung für verschiedene Kunstformen und Naturwunder',
		adjectiveHigh: 'kunstsinnig',
		itemHigh1: 'würde bei Gelegenheit gerne ein klassisches Konzert besuchen',
		itemHigh2: 'beobachtet manchmal gerne den Wind, der durch die Bäume weht',
		itemHigh3: 'genießt den Besuch von Kunstgalerien und das Betrachten von Gemälden',
		itemHigh4: 'empfindet Poesie als bedeutungsvoll und lesenswert',
		descriptionLow: 'neigt dazu, sich nicht in Kunstwerken oder Naturwundern zu verlieren',
		adjectiveLow: 'kunstuninteressiert',
		itemLow1: 'empfindet einen Besuch in einer Kunstgalerie als eher langweilig',
		itemLow2: 'würde kaum Zeit mit dem Lesen von Gedichten verbringen',
		itemLow3: 'zeigt kein Interesse an einem Besuch eines klassischen Konzerts',
		itemLow4: 'sieht keinen Sinn darin, sich die Wunder der Natur anzusehen',
	},
	{
		name: 'O2',
		domain: 'O',
		descriptionHigh: 'liest viel und interessiert sich für Reisen',
		adjectiveHigh: 'wissbegierig',
		itemHigh1: 'zeigt Interesse an Geschichte und Politik anderer Länder',
		itemHigh2: 'schaut sich gerne Karten von verschiedenen Orten an',
		itemHigh3: 'findet Bücher zur Geschichte von Wissenschaft und Technik faszinierend',
		itemHigh4: 'liest gerne Enzyklopädien oder Sachbücher',
		descriptionLow: 'hat wenig Interesse an Natur- oder Sozialkunde',
		adjectiveLow: 'unwissbegierig',
		itemLow1: 'empfindet Technik- und Sachbücher als langweilig',
		itemLow2: 'hat nie gerne in Enzyklopädien geblättert',
		itemLow3: 'findet Themen wie Geschichte und Politik anderer Länder uninteressant',
		itemLow4: 'zeigt wenig Interesse am Betrachten von Karten unbekannter Orte',
	},
	{
		name: 'O3',
		domain: 'O',
		descriptionHigh:
			'sucht aktiv nach neuen Lösungen für Probleme und drückt sich künstlerisch aus',
		adjectiveHigh: 'kreativ',
		itemHigh1:
			'würde es genießen, ein Kunstwerk zu schaffen, wie einen Roman, ein Lied oder ein Gemälde',
		itemHigh2: 'wird oft als fantasievoll und einfallsreich beschrieben',
		itemHigh3: 'bevorzugt Berufe, in denen Kreativität und Neues gefragt sind',
		itemHigh4: 'sieht sich selbst als Person, die gerne Ideen kreativ ausdrückt',
		descriptionLow: 'neigt kaum zu eigenen Ideen',
		adjectiveLow: 'fantasielos',
		itemLow1: 'bevorzugt eine Tätigkeit mit Routine statt kreativer Arbeit',
		itemLow2: 'hält sich nicht für künstlerisch oder kreativ',
		itemLow3:
			'wird von künstlerischen Tätigkeiten wie Schreiben, Malen oder Komponieren wenig angesprochen',
		itemLow4: 'wird selten als fantasievoll oder kreativ beschrieben',
	},
	{
		name: 'O4',
		domain: 'O',
		descriptionHigh: 'ist offen für Ideen, die seltsam oder radikal erscheinen mögen',
		adjectiveHigh: 'unkonventionell',
		itemHigh1: 'mag Personen mit unkonventionellen Ansichten',
		itemHigh2: 'sieht sich selbst als etwas exzentrisch',
		itemHigh3: 'genießt es, Ideen zu bedenken, die unkonventionelles Denken erfordern',
		itemHigh4: 'spricht gerne über abstrakte oder philosophische Themen',
		descriptionLow: 'vermeidet exzentrische oder normabweichende Personen',
		adjectiveLow: 'konventionell',
		itemLow1: 'hält es für Zeitverschwendung, radikalen Ideen Beachtung zu schenken',
		itemLow2: 'findet philosophische Diskussionen langweilig',
		itemLow3: 'bevorzugt Personen mit traditionellen und konventionellen Ansichten',
		itemLow4: 'sieht sich selbst als konventionell und typisch',
	},
	{
		name: 'Alt1',
		domain: 'Alt',
		descriptionHigh:
			'vermeidet es, Schaden anzurichten, und reagiert großzügig gegenüber denen, die schwächer sind oder Hilfe benötigen',
		adjectiveHigh: 'mitfühlend',
		itemHigh1: 'empfindet Mitgefühl für Personen, die weniger privilegiert sind',
		itemHigh2: 'gibt Bedürftigen gern großzügig etwas ab',
		itemHigh3:
			'fühlt sich schuldig, wenn jemandem Schaden zugefügt wird, selbst wenn keine Sympathie besteht',
		itemHigh4: 'wird als warmherzig und mitfühlend beschrieben',
		descriptionLow:
			'ist nicht besorgt darüber, andere zu verletzen, und kann als hartherzig angesehen werden',
		adjectiveLow: 'hartherzig',
		itemLow1: 'stört es kaum, Personen Schaden zuzufügen, wenn keine Sympathie besteht',
		itemLow2: 'gilt als gefühllos oder hart',
		itemLow3: 'zeigt wenig Mitgefühl für Personen in schlechterer Lage',
		itemLow4: 'gibt selten etwas an andere ab, auch wenn Bedarf besteht',
	},
];
