function selectTopThreeMoralValues(facetLevels) {
	const EXTREMELY_STRONG_POSITIVE = 10;
	const VERY_STRONG_POSITIVE = 9;
	const STRONG_POSITIVE = 8;
	const MODERATELY_STRONG_POSITIVE = 7;
	const MODERATE_POSITIVE = 6;
	const MODERATELY_WEAK_POSITIVE = 5;
	const WEAK_POSITIVE = 4;
	const VERY_WEAK_POSITIVE = 3;
	const MINIMAL_POSITIVE = 2;
	const NEGLIGIBLE_POSITIVE = 1;
	const NO_CORRELATION = 0;
	const NEGLIGIBLE_NEGATIVE = -1;
	const MINIMAL_NEGATIVE = -2;
	const VERY_WEAK_NEGATIVE = -3;
	const WEAK_NEGATIVE = -4;
	const MODERATELY_WEAK_NEGATIVE = -5;
	const MODERATE_NEGATIVE = -6;
	const MODERATELY_STRONG_NEGATIVE = -7;
	const STRONG_NEGATIVE = -8;
	const VERY_STRONG_NEGATIVE = -9;
	const EXTREMELY_STRONG_NEGATIVE = -10;

	const adjustments20 = {
		// H1
		H1: {
			high: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: EXTREMELY_STRONG_NEGATIVE,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: WEAK_NEGATIVE,
				powerDominance: MODERATELY_STRONG_NEGATIVE,
				powerResources: WEAK_NEGATIVE,
				face: MODERATE_NEGATIVE,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: VERY_WEAK_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: VERY_WEAK_POSITIVE,
				humility: MODERATELY_STRONG_POSITIVE,
				benevolenceDependability: MODERATELY_WEAK_POSITIVE,
				benevolenceCaring: VERY_WEAK_POSITIVE,
				universalismConcern: NEGLIGIBLE_NEGATIVE,
				universalismNature: EXTREMELY_STRONG_NEGATIVE,
				universalismTolerance: VERY_WEAK_POSITIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: EXTREMELY_STRONG_POSITIVE,
				stimulation: MINIMAL_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: WEAK_POSITIVE,
				powerDominance: MODERATELY_STRONG_POSITIVE,
				powerResources: WEAK_POSITIVE,
				face: MODERATE_POSITIVE,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: VERY_WEAK_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: VERY_WEAK_NEGATIVE,
				humility: MODERATELY_STRONG_NEGATIVE,
				benevolenceDependability: MODERATELY_WEAK_NEGATIVE,
				benevolenceCaring: VERY_WEAK_NEGATIVE,
				universalismConcern: NEGLIGIBLE_POSITIVE,
				universalismNature: EXTREMELY_STRONG_POSITIVE,
				universalismTolerance: VERY_WEAK_NEGATIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
		},

		// H2
		H2: {
			high: {
				selfDirectionThought: EXTREMELY_STRONG_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: NEGLIGIBLE_POSITIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: VERY_WEAK_NEGATIVE,
				powerDominance: MODERATE_NEGATIVE,
				powerResources: STRONG_NEGATIVE,
				face: NEGLIGIBLE_NEGATIVE,
				securityPersonal: EXTREMELY_STRONG_NEGATIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: WEAK_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: MINIMAL_POSITIVE,
				humility: WEAK_POSITIVE,
				benevolenceDependability: VERY_WEAK_POSITIVE,
				benevolenceCaring: MODERATELY_WEAK_POSITIVE,
				universalismConcern: STRONG_POSITIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: VERY_WEAK_POSITIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
			low: {
				selfDirectionThought: EXTREMELY_STRONG_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: NEGLIGIBLE_NEGATIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: VERY_WEAK_POSITIVE,
				powerDominance: MODERATE_POSITIVE,
				powerResources: STRONG_POSITIVE,
				face: NEGLIGIBLE_POSITIVE,
				securityPersonal: EXTREMELY_STRONG_POSITIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: WEAK_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: MINIMAL_NEGATIVE,
				humility: WEAK_NEGATIVE,
				benevolenceDependability: VERY_WEAK_NEGATIVE,
				benevolenceCaring: MODERATELY_WEAK_NEGATIVE,
				universalismConcern: STRONG_NEGATIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: VERY_WEAK_NEGATIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
		},

		// H3
		H3: {
			high: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: NEGLIGIBLE_NEGATIVE,
				hedonism: MINIMAL_NEGATIVE,
				achievement: MODERATE_NEGATIVE,
				powerDominance: WEAK_NEGATIVE,
				powerResources: VERY_STRONG_NEGATIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: NEGLIGIBLE_POSITIVE,
				conformityInterpersonal: MINIMAL_POSITIVE,
				humility: VERY_STRONG_POSITIVE,
				benevolenceDependability: MINIMAL_POSITIVE,
				benevolenceCaring: WEAK_POSITIVE,
				universalismConcern: MODERATE_POSITIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: EXTREMELY_STRONG_NEGATIVE,
				universalismObjectivity: VERY_WEAK_POSITIVE,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: NEGLIGIBLE_POSITIVE,
				hedonism: MINIMAL_POSITIVE,
				achievement: MODERATE_POSITIVE,
				powerDominance: WEAK_POSITIVE,
				powerResources: VERY_STRONG_POSITIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: NEGLIGIBLE_NEGATIVE,
				conformityInterpersonal: MINIMAL_NEGATIVE,
				humility: VERY_STRONG_NEGATIVE,
				benevolenceDependability: MINIMAL_NEGATIVE,
				benevolenceCaring: WEAK_NEGATIVE,
				universalismConcern: MODERATE_NEGATIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: EXTREMELY_STRONG_POSITIVE,
				universalismObjectivity: VERY_WEAK_NEGATIVE,
			},
		},

		// H4
		H4: {
			high: {
				selfDirectionThought: EXTREMELY_STRONG_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: VERY_WEAK_NEGATIVE,
				powerDominance: STRONG_NEGATIVE,
				powerResources: VERY_WEAK_NEGATIVE,
				face: MODERATE_NEGATIVE,
				securityPersonal: EXTREMELY_STRONG_NEGATIVE,
				securitySocietal: NEGLIGIBLE_POSITIVE,
				tradition: VERY_WEAK_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: MODERATELY_WEAK_POSITIVE,
				humility: EXTREMELY_STRONG_POSITIVE,
				benevolenceDependability: VERY_WEAK_POSITIVE,
				benevolenceCaring: MINIMAL_POSITIVE,
				universalismConcern: WEAK_POSITIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
			low: {
				selfDirectionThought: EXTREMELY_STRONG_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: MINIMAL_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: VERY_WEAK_POSITIVE,
				powerDominance: STRONG_POSITIVE,
				powerResources: VERY_WEAK_POSITIVE,
				face: MODERATE_POSITIVE,
				securityPersonal: EXTREMELY_STRONG_POSITIVE,
				securitySocietal: NEGLIGIBLE_NEGATIVE,
				tradition: VERY_WEAK_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: MODERATELY_WEAK_NEGATIVE,
				humility: EXTREMELY_STRONG_NEGATIVE,
				benevolenceDependability: VERY_WEAK_NEGATIVE,
				benevolenceCaring: MINIMAL_NEGATIVE,
				universalismConcern: WEAK_NEGATIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
		},

		// E1
		E1: {
			high: {
				selfDirectionThought: WEAK_NEGATIVE,
				selfDirectionAction: MODERATELY_WEAK_NEGATIVE,
				stimulation: STRONG_NEGATIVE,
				hedonism: VERY_WEAK_NEGATIVE,
				achievement: NEGLIGIBLE_NEGATIVE,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: EXTREMELY_STRONG_POSITIVE,
				face: EXTREMELY_STRONG_POSITIVE,
				securityPersonal: VERY_STRONG_POSITIVE,
				securitySocietal: MODERATE_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: VERY_WEAK_POSITIVE,
				conformityInterpersonal: MINIMAL_POSITIVE,
				humility: EXTREMELY_STRONG_NEGATIVE,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: EXTREMELY_STRONG_NEGATIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: EXTREMELY_STRONG_NEGATIVE,
			},
			low: {
				selfDirectionThought: WEAK_POSITIVE,
				selfDirectionAction: MODERATELY_WEAK_POSITIVE,
				stimulation: STRONG_POSITIVE,
				hedonism: VERY_WEAK_POSITIVE,
				achievement: NEGLIGIBLE_POSITIVE,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: EXTREMELY_STRONG_NEGATIVE,
				face: EXTREMELY_STRONG_NEGATIVE,
				securityPersonal: VERY_STRONG_NEGATIVE,
				securitySocietal: MODERATE_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: VERY_WEAK_NEGATIVE,
				conformityInterpersonal: MINIMAL_NEGATIVE,
				humility: EXTREMELY_STRONG_POSITIVE,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: EXTREMELY_STRONG_POSITIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: EXTREMELY_STRONG_POSITIVE,
			},
		},

		// E2
		E2: {
			high: {
				selfDirectionThought: MODERATE_NEGATIVE,
				selfDirectionAction: WEAK_NEGATIVE,
				stimulation: VERY_WEAK_NEGATIVE,
				hedonism: MINIMAL_NEGATIVE,
				achievement: NEGLIGIBLE_NEGATIVE,
				powerDominance: EXTREMELY_STRONG_POSITIVE,
				powerResources: EXTREMELY_STRONG_POSITIVE,
				face: EXTREMELY_STRONG_POSITIVE,
				securityPersonal: STRONG_POSITIVE,
				securitySocietal: MODERATELY_WEAK_POSITIVE,
				tradition: NEGLIGIBLE_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: EXTREMELY_STRONG_NEGATIVE,
				humility: EXTREMELY_STRONG_NEGATIVE,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: EXTREMELY_STRONG_NEGATIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_NEGATIVE,
			},
			low: {
				selfDirectionThought: MODERATE_POSITIVE,
				selfDirectionAction: WEAK_POSITIVE,
				stimulation: VERY_WEAK_POSITIVE,
				hedonism: MINIMAL_POSITIVE,
				achievement: NEGLIGIBLE_POSITIVE,
				powerDominance: EXTREMELY_STRONG_NEGATIVE,
				powerResources: EXTREMELY_STRONG_NEGATIVE,
				face: EXTREMELY_STRONG_NEGATIVE,
				securityPersonal: STRONG_NEGATIVE,
				securitySocietal: MODERATELY_WEAK_NEGATIVE,
				tradition: NEGLIGIBLE_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: EXTREMELY_STRONG_POSITIVE,
				humility: EXTREMELY_STRONG_POSITIVE,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: EXTREMELY_STRONG_POSITIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_POSITIVE,
			},
		},

		// E3
		E3: {
			high: {
				selfDirectionThought: MODERATE_NEGATIVE,
				selfDirectionAction: MODERATELY_STRONG_NEGATIVE,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: MINIMAL_NEGATIVE,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: EXTREMELY_STRONG_POSITIVE,
				face: EXTREMELY_STRONG_POSITIVE,
				securityPersonal: MODERATELY_STRONG_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: NEGLIGIBLE_POSITIVE,
				conformityRules: NEGLIGIBLE_POSITIVE,
				conformityInterpersonal: WEAK_POSITIVE,
				humility: EXTREMELY_STRONG_NEGATIVE,
				benevolenceDependability: MINIMAL_POSITIVE,
				benevolenceCaring: MODERATE_POSITIVE,
				universalismConcern: MINIMAL_POSITIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_NEGATIVE,
			},
			low: {
				selfDirectionThought: MODERATE_POSITIVE,
				selfDirectionAction: MODERATELY_STRONG_POSITIVE,
				stimulation: MINIMAL_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: MINIMAL_POSITIVE,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: EXTREMELY_STRONG_NEGATIVE,
				face: EXTREMELY_STRONG_NEGATIVE,
				securityPersonal: MODERATELY_STRONG_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: NEGLIGIBLE_NEGATIVE,
				conformityRules: NEGLIGIBLE_NEGATIVE,
				conformityInterpersonal: WEAK_NEGATIVE,
				humility: EXTREMELY_STRONG_POSITIVE,
				benevolenceDependability: MINIMAL_NEGATIVE,
				benevolenceCaring: MODERATE_NEGATIVE,
				universalismConcern: MINIMAL_NEGATIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_POSITIVE,
			},
		},

		// E4
		E4: {
			high: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: NEGLIGIBLE_NEGATIVE,
				hedonism: MINIMAL_NEGATIVE,
				achievement: MODERATELY_WEAK_NEGATIVE,
				powerDominance: MODERATELY_STRONG_NEGATIVE,
				powerResources: MINIMAL_NEGATIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: EXTREMELY_STRONG_NEGATIVE,
				tradition: VERY_WEAK_POSITIVE,
				conformityRules: EXTREMELY_STRONG_POSITIVE,
				conformityInterpersonal: VERY_WEAK_POSITIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: MODERATE_POSITIVE,
				benevolenceCaring: STRONG_POSITIVE,
				universalismConcern: VERY_WEAK_POSITIVE,
				universalismNature: VERY_WEAK_POSITIVE,
				universalismTolerance: MODERATE_NEGATIVE,
				universalismObjectivity: EXTREMELY_STRONG_NEGATIVE,
			},
			low: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: NEGLIGIBLE_POSITIVE,
				hedonism: MINIMAL_POSITIVE,
				achievement: MODERATELY_WEAK_POSITIVE,
				powerDominance: MODERATELY_STRONG_POSITIVE,
				powerResources: MINIMAL_POSITIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: EXTREMELY_STRONG_POSITIVE,
				tradition: VERY_WEAK_NEGATIVE,
				conformityRules: EXTREMELY_STRONG_NEGATIVE,
				conformityInterpersonal: VERY_WEAK_NEGATIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: MODERATE_NEGATIVE,
				benevolenceCaring: STRONG_NEGATIVE,
				universalismConcern: VERY_WEAK_NEGATIVE,
				universalismNature: VERY_WEAK_NEGATIVE,
				universalismTolerance: MODERATE_POSITIVE,
				universalismObjectivity: EXTREMELY_STRONG_POSITIVE,
			},
		},

		// X1
		X1: {
			high: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: MODERATELY_WEAK_POSITIVE,
				stimulation: MINIMAL_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: MODERATELY_STRONG_POSITIVE,
				powerDominance: VERY_WEAK_POSITIVE,
				powerResources: MINIMAL_POSITIVE,
				face: NEGLIGIBLE_POSITIVE,
				securityPersonal: MODERATE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: MINIMAL_NEGATIVE,
				humility: MODERATELY_WEAK_NEGATIVE,
				benevolenceDependability: EXTREMELY_STRONG_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: EXTREMELY_STRONG_NEGATIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: MINIMAL_NEGATIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
			low: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: MODERATELY_WEAK_NEGATIVE,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: MODERATELY_STRONG_NEGATIVE,
				powerDominance: VERY_WEAK_NEGATIVE,
				powerResources: MINIMAL_NEGATIVE,
				face: NEGLIGIBLE_NEGATIVE,
				securityPersonal: MODERATE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: MINIMAL_POSITIVE,
				humility: MODERATELY_WEAK_POSITIVE,
				benevolenceDependability: EXTREMELY_STRONG_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: EXTREMELY_STRONG_POSITIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: MINIMAL_POSITIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
		},

		// X2
		X2: {
			high: {
				selfDirectionThought: WEAK_POSITIVE,
				selfDirectionAction: MODERATE_POSITIVE,
				stimulation: STRONG_POSITIVE,
				hedonism: MINIMAL_POSITIVE,
				achievement: MINIMAL_POSITIVE,
				powerDominance: MODERATELY_WEAK_POSITIVE,
				powerResources: NEGLIGIBLE_POSITIVE,
				face: MODERATELY_WEAK_POSITIVE,
				securityPersonal: MODERATELY_STRONG_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: VERY_WEAK_NEGATIVE,
				conformityRules: MODERATE_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: VERY_WEAK_NEGATIVE,
				benevolenceDependability: MODERATE_NEGATIVE,
				benevolenceCaring: MODERATELY_STRONG_NEGATIVE,
				universalismConcern: EXTREMELY_STRONG_NEGATIVE,
				universalismNature: WEAK_NEGATIVE,
				universalismTolerance: VERY_WEAK_NEGATIVE,
				universalismObjectivity: MODERATELY_WEAK_NEGATIVE,
			},
			low: {
				selfDirectionThought: WEAK_NEGATIVE,
				selfDirectionAction: MODERATE_NEGATIVE,
				stimulation: STRONG_NEGATIVE,
				hedonism: MINIMAL_NEGATIVE,
				achievement: MINIMAL_NEGATIVE,
				powerDominance: MODERATELY_WEAK_NEGATIVE,
				powerResources: NEGLIGIBLE_NEGATIVE,
				face: MODERATELY_WEAK_NEGATIVE,
				securityPersonal: MODERATELY_STRONG_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: VERY_WEAK_POSITIVE,
				conformityRules: MODERATE_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: VERY_WEAK_POSITIVE,
				benevolenceDependability: MODERATE_POSITIVE,
				benevolenceCaring: MODERATELY_STRONG_POSITIVE,
				universalismConcern: EXTREMELY_STRONG_POSITIVE,
				universalismNature: WEAK_POSITIVE,
				universalismTolerance: VERY_WEAK_POSITIVE,
				universalismObjectivity: MODERATELY_WEAK_POSITIVE,
			},
		},

		// X3
		X3: {
			high: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: MODERATELY_WEAK_POSITIVE,
				hedonism: VERY_WEAK_POSITIVE,
				achievement: NO_CORRELATION,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: MINIMAL_POSITIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: MODERATELY_WEAK_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MODERATELY_STRONG_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: VERY_WEAK_POSITIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: EXTREMELY_STRONG_NEGATIVE,
				benevolenceCaring: MODERATELY_STRONG_POSITIVE,
				universalismConcern: WEAK_POSITIVE,
				universalismNature: WEAK_NEGATIVE,
				universalismTolerance: VERY_WEAK_POSITIVE,
				universalismObjectivity: NO_CORRELATION,
			},
			low: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: MODERATELY_WEAK_NEGATIVE,
				hedonism: VERY_WEAK_NEGATIVE,
				achievement: NO_CORRELATION,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: MINIMAL_NEGATIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: MODERATELY_WEAK_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MODERATELY_STRONG_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: VERY_WEAK_NEGATIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: EXTREMELY_STRONG_POSITIVE,
				benevolenceCaring: MODERATELY_STRONG_NEGATIVE,
				universalismConcern: WEAK_NEGATIVE,
				universalismNature: WEAK_POSITIVE,
				universalismTolerance: VERY_WEAK_NEGATIVE,
				universalismObjectivity: NO_CORRELATION,
			},
		},

		// X4
		X4: {
			high: {
				selfDirectionThought: MINIMAL_POSITIVE,
				selfDirectionAction: VERY_WEAK_POSITIVE,
				stimulation: VERY_STRONG_POSITIVE,
				hedonism: MODERATE_POSITIVE,
				achievement: NEGLIGIBLE_POSITIVE,
				powerDominance: EXTREMELY_STRONG_POSITIVE,
				powerResources: EXTREMELY_STRONG_POSITIVE,
				face: NO_CORRELATION,
				securityPersonal: MINIMAL_NEGATIVE,
				securitySocietal: VERY_WEAK_NEGATIVE,
				tradition: STRONG_NEGATIVE,
				conformityRules: MODERATE_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: EXTREMELY_STRONG_NEGATIVE,
				benevolenceDependability: EXTREMELY_STRONG_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: MODERATELY_STRONG_NEGATIVE,
				universalismNature: MINIMAL_NEGATIVE,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: NO_CORRELATION,
			},
			low: {
				selfDirectionThought: MINIMAL_NEGATIVE,
				selfDirectionAction: VERY_WEAK_NEGATIVE,
				stimulation: VERY_STRONG_NEGATIVE,
				hedonism: MODERATE_NEGATIVE,
				achievement: NEGLIGIBLE_NEGATIVE,
				powerDominance: EXTREMELY_STRONG_NEGATIVE,
				powerResources: EXTREMELY_STRONG_NEGATIVE,
				face: NO_CORRELATION,
				securityPersonal: MINIMAL_POSITIVE,
				securitySocietal: VERY_WEAK_POSITIVE,
				tradition: STRONG_POSITIVE,
				conformityRules: MODERATE_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: EXTREMELY_STRONG_POSITIVE,
				benevolenceDependability: EXTREMELY_STRONG_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: MODERATELY_STRONG_POSITIVE,
				universalismNature: MINIMAL_POSITIVE,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: NO_CORRELATION,
			},
		},

		// A1
		A1: {
			high: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: NEGLIGIBLE_NEGATIVE,
				hedonism: EXTREMELY_STRONG_POSITIVE,
				achievement: WEAK_NEGATIVE,
				powerDominance: MODERATELY_STRONG_NEGATIVE,
				powerResources: VERY_WEAK_NEGATIVE,
				face: MODERATELY_WEAK_NEGATIVE,
				securityPersonal: NO_CORRELATION,
				securitySocietal: NEGLIGIBLE_POSITIVE,
				tradition: NEGLIGIBLE_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: VERY_WEAK_POSITIVE,
				humility: VERY_WEAK_POSITIVE,
				benevolenceDependability: VERY_WEAK_POSITIVE,
				benevolenceCaring: MODERATE_POSITIVE,
				universalismConcern: VERY_WEAK_POSITIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: MODERATELY_STRONG_POSITIVE,
				universalismObjectivity: NEGLIGIBLE_POSITIVE,
			},
			low: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: NEGLIGIBLE_POSITIVE,
				hedonism: EXTREMELY_STRONG_NEGATIVE,
				achievement: WEAK_POSITIVE,
				powerDominance: MODERATELY_STRONG_POSITIVE,
				powerResources: VERY_WEAK_POSITIVE,
				face: MODERATELY_WEAK_POSITIVE,
				securityPersonal: NO_CORRELATION,
				securitySocietal: NEGLIGIBLE_NEGATIVE,
				tradition: NEGLIGIBLE_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: VERY_WEAK_NEGATIVE,
				humility: VERY_WEAK_NEGATIVE,
				benevolenceDependability: VERY_WEAK_NEGATIVE,
				benevolenceCaring: MODERATE_NEGATIVE,
				universalismConcern: VERY_WEAK_NEGATIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: MODERATELY_STRONG_NEGATIVE,
				universalismObjectivity: NEGLIGIBLE_NEGATIVE,
			},
		},

		// A2
		A2: {
			high: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: WEAK_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: MINIMAL_NEGATIVE,
				powerDominance: STRONG_NEGATIVE,
				powerResources: MODERATELY_WEAK_NEGATIVE,
				face: VERY_WEAK_NEGATIVE,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: NEGLIGIBLE_POSITIVE,
				conformityInterpersonal: VERY_WEAK_POSITIVE,
				humility: MODERATELY_WEAK_POSITIVE,
				benevolenceDependability: VERY_WEAK_POSITIVE,
				benevolenceCaring: VERY_STRONG_POSITIVE,
				universalismConcern: MODERATELY_WEAK_POSITIVE,
				universalismNature: VERY_WEAK_POSITIVE,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: NO_CORRELATION,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: WEAK_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: MINIMAL_POSITIVE,
				powerDominance: STRONG_POSITIVE,
				powerResources: MODERATELY_WEAK_POSITIVE,
				face: VERY_WEAK_POSITIVE,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: NEGLIGIBLE_NEGATIVE,
				conformityInterpersonal: VERY_WEAK_NEGATIVE,
				humility: MODERATELY_WEAK_NEGATIVE,
				benevolenceDependability: VERY_WEAK_NEGATIVE,
				benevolenceCaring: VERY_STRONG_NEGATIVE,
				universalismConcern: MODERATELY_WEAK_NEGATIVE,
				universalismNature: VERY_WEAK_NEGATIVE,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: NO_CORRELATION,
			},
		},

		// A3
		A3: {
			high: {
				selfDirectionThought: MODERATELY_WEAK_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: EXTREMELY_STRONG_POSITIVE,
				hedonism: EXTREMELY_STRONG_POSITIVE,
				achievement: NEGLIGIBLE_NEGATIVE,
				powerDominance: MINIMAL_NEGATIVE,
				powerResources: MINIMAL_NEGATIVE,
				face: NEGLIGIBLE_NEGATIVE,
				securityPersonal: NO_CORRELATION,
				securitySocietal: NEGLIGIBLE_POSITIVE,
				tradition: MODERATE_NEGATIVE,
				conformityRules: WEAK_NEGATIVE,
				conformityInterpersonal: MINIMAL_POSITIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: VERY_WEAK_POSITIVE,
				benevolenceCaring: MINIMAL_POSITIVE,
				universalismConcern: MINIMAL_POSITIVE,
				universalismNature: MINIMAL_POSITIVE,
				universalismTolerance: MODERATE_POSITIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
			low: {
				selfDirectionThought: MODERATELY_WEAK_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: EXTREMELY_STRONG_NEGATIVE,
				hedonism: EXTREMELY_STRONG_NEGATIVE,
				achievement: NEGLIGIBLE_POSITIVE,
				powerDominance: MINIMAL_POSITIVE,
				powerResources: MINIMAL_POSITIVE,
				face: NEGLIGIBLE_POSITIVE,
				securityPersonal: NO_CORRELATION,
				securitySocietal: NEGLIGIBLE_NEGATIVE,
				tradition: MODERATE_POSITIVE,
				conformityRules: WEAK_POSITIVE,
				conformityInterpersonal: MINIMAL_NEGATIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: VERY_WEAK_NEGATIVE,
				benevolenceCaring: MINIMAL_NEGATIVE,
				universalismConcern: MINIMAL_NEGATIVE,
				universalismNature: MINIMAL_NEGATIVE,
				universalismTolerance: MODERATE_NEGATIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
		},

		// A4
		A4: {
			high: {
				selfDirectionThought: NO_CORRELATION,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: MODERATELY_STRONG_NEGATIVE,
				hedonism: WEAK_NEGATIVE,
				achievement: NO_CORRELATION,
				powerDominance: MINIMAL_NEGATIVE,
				powerResources: NO_CORRELATION,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: NEGLIGIBLE_POSITIVE,
				conformityInterpersonal: STRONG_POSITIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: MODERATE_POSITIVE,
				benevolenceCaring: VERY_WEAK_POSITIVE,
				universalismConcern: MINIMAL_NEGATIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_POSITIVE,
			},
			low: {
				selfDirectionThought: NO_CORRELATION,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: MODERATELY_STRONG_POSITIVE,
				hedonism: WEAK_POSITIVE,
				achievement: NO_CORRELATION,
				powerDominance: MINIMAL_POSITIVE,
				powerResources: NO_CORRELATION,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: NEGLIGIBLE_NEGATIVE,
				conformityInterpersonal: STRONG_NEGATIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: MODERATE_NEGATIVE,
				benevolenceCaring: VERY_WEAK_NEGATIVE,
				universalismConcern: MINIMAL_POSITIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_NEGATIVE,
			},
		},

		// C1
		C1: {
			high: {
				selfDirectionThought: MINIMAL_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: MODERATE_NEGATIVE,
				hedonism: WEAK_NEGATIVE,
				achievement: STRONG_POSITIVE,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: NEGLIGIBLE_POSITIVE,
				face: NO_CORRELATION,
				securityPersonal: WEAK_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: VERY_WEAK_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: NEGLIGIBLE_NEGATIVE,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: WEAK_NEGATIVE,
				universalismObjectivity: NO_CORRELATION,
			},
			low: {
				selfDirectionThought: MINIMAL_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: MODERATE_POSITIVE,
				hedonism: WEAK_POSITIVE,
				achievement: STRONG_NEGATIVE,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: NEGLIGIBLE_NEGATIVE,
				face: NO_CORRELATION,
				securityPersonal: WEAK_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: VERY_WEAK_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: NEGLIGIBLE_POSITIVE,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: WEAK_POSITIVE,
				universalismObjectivity: NO_CORRELATION,
			},
		},

		// C2
		C2: {
			high: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: NO_CORRELATION,
				stimulation: WEAK_NEGATIVE,
				hedonism: MODERATELY_STRONG_NEGATIVE,
				achievement: VERY_STRONG_POSITIVE,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: NO_CORRELATION,
				face: NEGLIGIBLE_POSITIVE,
				securityPersonal: MINIMAL_POSITIVE,
				securitySocietal: NEGLIGIBLE_POSITIVE,
				tradition: EXTREMELY_STRONG_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: MODERATELY_WEAK_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: VERY_WEAK_NEGATIVE,
				universalismTolerance: VERY_WEAK_NEGATIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
			low: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: NO_CORRELATION,
				stimulation: WEAK_POSITIVE,
				hedonism: MODERATELY_STRONG_POSITIVE,
				achievement: VERY_STRONG_NEGATIVE,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: NO_CORRELATION,
				face: NEGLIGIBLE_NEGATIVE,
				securityPersonal: MINIMAL_NEGATIVE,
				securitySocietal: NEGLIGIBLE_NEGATIVE,
				tradition: EXTREMELY_STRONG_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: MODERATELY_WEAK_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: VERY_WEAK_POSITIVE,
				universalismTolerance: VERY_WEAK_POSITIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
		},

		// C3
		C3: {
			high: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: NO_CORRELATION,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: MODERATE_NEGATIVE,
				achievement: EXTREMELY_STRONG_POSITIVE,
				powerDominance: MINIMAL_POSITIVE,
				powerResources: NEGLIGIBLE_POSITIVE,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: WEAK_NEGATIVE,
				tradition: EXTREMELY_STRONG_POSITIVE,
				conformityRules: VERY_WEAK_POSITIVE,
				conformityInterpersonal: EXTREMELY_STRONG_NEGATIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: WEAK_POSITIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: WEAK_NEGATIVE,
				universalismObjectivity: NO_CORRELATION,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: NO_CORRELATION,
				stimulation: MINIMAL_POSITIVE,
				hedonism: MODERATE_POSITIVE,
				achievement: EXTREMELY_STRONG_NEGATIVE,
				powerDominance: MINIMAL_NEGATIVE,
				powerResources: NEGLIGIBLE_NEGATIVE,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: WEAK_POSITIVE,
				tradition: EXTREMELY_STRONG_NEGATIVE,
				conformityRules: VERY_WEAK_NEGATIVE,
				conformityInterpersonal: EXTREMELY_STRONG_POSITIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: WEAK_NEGATIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: WEAK_POSITIVE,
				universalismObjectivity: NO_CORRELATION,
			},
		},

		// C4
		C4: {
			high: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: VERY_STRONG_NEGATIVE,
				hedonism: WEAK_NEGATIVE,
				achievement: MINIMAL_POSITIVE,
				powerDominance: EXTREMELY_STRONG_POSITIVE,
				powerResources: NO_CORRELATION,
				face: MINIMAL_POSITIVE,
				securityPersonal: STRONG_POSITIVE,
				securitySocietal: VERY_WEAK_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: MODERATE_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: VERY_STRONG_POSITIVE,
				hedonism: WEAK_POSITIVE,
				achievement: MINIMAL_NEGATIVE,
				powerDominance: EXTREMELY_STRONG_NEGATIVE,
				powerResources: NO_CORRELATION,
				face: MINIMAL_NEGATIVE,
				securityPersonal: STRONG_NEGATIVE,
				securitySocietal: VERY_WEAK_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: MODERATE_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
		},

		// O1
		O1: {
			high: {
				selfDirectionThought: STRONG_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: NEGLIGIBLE_POSITIVE,
				hedonism: MODERATELY_WEAK_POSITIVE,
				achievement: WEAK_NEGATIVE,
				powerDominance: MINIMAL_NEGATIVE,
				powerResources: MODERATE_NEGATIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: MINIMAL_NEGATIVE,
				securitySocietal: NEGLIGIBLE_NEGATIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: VERY_WEAK_NEGATIVE,
				conformityInterpersonal: EXTREMELY_STRONG_NEGATIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: MINIMAL_POSITIVE,
				universalismNature: MODERATE_POSITIVE,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
			low: {
				selfDirectionThought: STRONG_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: NEGLIGIBLE_NEGATIVE,
				hedonism: MODERATELY_WEAK_NEGATIVE,
				achievement: WEAK_POSITIVE,
				powerDominance: MINIMAL_POSITIVE,
				powerResources: MODERATE_POSITIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: MINIMAL_POSITIVE,
				securitySocietal: NEGLIGIBLE_POSITIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: VERY_WEAK_POSITIVE,
				conformityInterpersonal: EXTREMELY_STRONG_POSITIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: MINIMAL_NEGATIVE,
				universalismNature: MODERATE_NEGATIVE,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
		},

		// O2
		O2: {
			high: {
				selfDirectionThought: EXTREMELY_STRONG_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: MODERATELY_WEAK_POSITIVE,
				hedonism: NO_CORRELATION,
				achievement: NO_CORRELATION,
				powerDominance: EXTREMELY_STRONG_POSITIVE,
				powerResources: NO_CORRELATION,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MODERATELY_STRONG_NEGATIVE,
				conformityRules: MODERATELY_WEAK_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: EXTREMELY_STRONG_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: MODERATE_POSITIVE,
			},
			low: {
				selfDirectionThought: EXTREMELY_STRONG_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: MODERATELY_WEAK_NEGATIVE,
				hedonism: NO_CORRELATION,
				achievement: NO_CORRELATION,
				powerDominance: EXTREMELY_STRONG_NEGATIVE,
				powerResources: NO_CORRELATION,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MODERATELY_STRONG_POSITIVE,
				conformityRules: MODERATELY_WEAK_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: EXTREMELY_STRONG_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: MODERATE_NEGATIVE,
			},
		},

		// O3
		O3: {
			high: {
				selfDirectionThought: VERY_STRONG_POSITIVE,
				selfDirectionAction: MODERATE_POSITIVE,
				stimulation: VERY_WEAK_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: NO_CORRELATION,
				powerDominance: MODERATE_POSITIVE,
				powerResources: NEGLIGIBLE_NEGATIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: MINIMAL_NEGATIVE,
				securitySocietal: VERY_WEAK_NEGATIVE,
				tradition: MODERATE_NEGATIVE,
				conformityRules: MODERATELY_STRONG_NEGATIVE,
				conformityInterpersonal: EXTREMELY_STRONG_NEGATIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: MINIMAL_NEGATIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: MODERATELY_WEAK_POSITIVE,
			},
			low: {
				selfDirectionThought: VERY_STRONG_NEGATIVE,
				selfDirectionAction: MODERATE_NEGATIVE,
				stimulation: VERY_WEAK_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: NO_CORRELATION,
				powerDominance: MODERATE_NEGATIVE,
				powerResources: NEGLIGIBLE_POSITIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: MINIMAL_POSITIVE,
				securitySocietal: VERY_WEAK_POSITIVE,
				tradition: MODERATE_POSITIVE,
				conformityRules: MODERATELY_STRONG_POSITIVE,
				conformityInterpersonal: EXTREMELY_STRONG_POSITIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: MINIMAL_POSITIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: MODERATELY_WEAK_NEGATIVE,
			},
		},

		// O4
		O4: {
			high: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: MODERATELY_WEAK_POSITIVE,
				stimulation: EXTREMELY_STRONG_POSITIVE,
				hedonism: MINIMAL_POSITIVE,
				achievement: NO_CORRELATION,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: NO_CORRELATION,
				face: MODERATELY_WEAK_NEGATIVE,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MODERATE_NEGATIVE,
				tradition: VERY_STRONG_NEGATIVE,
				conformityRules: MODERATELY_STRONG_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: EXTREMELY_STRONG_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: MINIMAL_POSITIVE,
				universalismTolerance: MODERATE_POSITIVE,
				universalismObjectivity: VERY_WEAK_POSITIVE,
			},
			low: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: MODERATELY_WEAK_NEGATIVE,
				stimulation: EXTREMELY_STRONG_NEGATIVE,
				hedonism: MINIMAL_NEGATIVE,
				achievement: NO_CORRELATION,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: NO_CORRELATION,
				face: MODERATELY_WEAK_POSITIVE,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MODERATE_POSITIVE,
				tradition: VERY_STRONG_POSITIVE,
				conformityRules: MODERATELY_STRONG_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: EXTREMELY_STRONG_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: MINIMAL_NEGATIVE,
				universalismTolerance: MODERATE_NEGATIVE,
				universalismObjectivity: VERY_WEAK_NEGATIVE,
			},
		},

		// Alt1
		Alt1: {
			high: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: MINIMAL_NEGATIVE,
				powerDominance: MODERATELY_WEAK_NEGATIVE,
				powerResources: WEAK_NEGATIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: MINIMAL_POSITIVE,
				securitySocietal: VERY_WEAK_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: NEGLIGIBLE_POSITIVE,
				conformityInterpersonal: MODERATELY_WEAK_POSITIVE,
				humility: MODERATE_POSITIVE,
				benevolenceDependability: STRONG_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: VERY_STRONG_POSITIVE,
				universalismNature: WEAK_POSITIVE,
				universalismTolerance: MODERATELY_WEAK_POSITIVE,
				universalismObjectivity: WEAK_POSITIVE,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: MINIMAL_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: MINIMAL_POSITIVE,
				powerDominance: MODERATELY_WEAK_POSITIVE,
				powerResources: WEAK_POSITIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: MINIMAL_NEGATIVE,
				securitySocietal: VERY_WEAK_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: NEGLIGIBLE_NEGATIVE,
				conformityInterpersonal: MODERATELY_WEAK_NEGATIVE,
				humility: MODERATE_NEGATIVE,
				benevolenceDependability: STRONG_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: VERY_STRONG_NEGATIVE,
				universalismNature: WEAK_NEGATIVE,
				universalismTolerance: MODERATELY_WEAK_NEGATIVE,
				universalismObjectivity: WEAK_NEGATIVE,
			},
		},
	};
	const totals20 = {
		selfDirectionThought: 0,
		selfDirectionAction: 0,
		stimulation: 0,
		hedonism: 0,
		achievement: 0,
		powerDominance: 0,
		powerResources: 0,
		face: 0,
		securityPersonal: 0,
		securitySocietal: 0,
		conformityRules: 0,
		conformityInterpersonal: 0,
		tradition: 0,
		humility: 0,
		benevolenceCaring: 0,
		benevolenceDependability: 0,
		universalismConcern: 0,
		universalismNature: 0,
		universalismTolerance: 0,
		universalismObjectivity: 0,
	};

	for (const [facet, level] of Object.entries(facetLevels)) {

		const adjustmentSource = adjustments20;

		const adjustment = adjustmentSource[facet]?.[level];

		if (!adjustment) continue;

		for (const key in adjustment) {
			totals20[key] += adjustment[key];
		}
	}


	const relevantTotals = totals20;

	const numberValues = document.getElementById('numberValues');
	const top = Object.entries(relevantTotals)
		.sort((a, b) => b[1] - a[1]) // absteigend sortieren
		.slice(0, Number(numberValues.value));

	return top.map(([key]) => key);
}

function selectWorstThreeMoralValues(facetLevels) {
	const EXTREMELY_STRONG_POSITIVE = 10;
	const VERY_STRONG_POSITIVE = 9;
	const STRONG_POSITIVE = 8;
	const MODERATELY_STRONG_POSITIVE = 7;
	const MODERATE_POSITIVE = 6;
	const MODERATELY_WEAK_POSITIVE = 5;
	const WEAK_POSITIVE = 4;
	const VERY_WEAK_POSITIVE = 3;
	const MINIMAL_POSITIVE = 2;
	const NEGLIGIBLE_POSITIVE = 1;
	const NO_CORRELATION = 0;
	const NEGLIGIBLE_NEGATIVE = -1;
	const MINIMAL_NEGATIVE = -2;
	const VERY_WEAK_NEGATIVE = -3;
	const WEAK_NEGATIVE = -4;
	const MODERATELY_WEAK_NEGATIVE = -5;
	const MODERATE_NEGATIVE = -6;
	const MODERATELY_STRONG_NEGATIVE = -7;
	const STRONG_NEGATIVE = -8;
	const VERY_STRONG_NEGATIVE = -9;
	const EXTREMELY_STRONG_NEGATIVE = -10;

	const adjustments20 = {
		// H1
		H1: {
			high: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: EXTREMELY_STRONG_NEGATIVE,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: WEAK_NEGATIVE,
				powerDominance: MODERATELY_STRONG_NEGATIVE,
				powerResources: WEAK_NEGATIVE,
				face: MODERATE_NEGATIVE,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: VERY_WEAK_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: VERY_WEAK_POSITIVE,
				humility: MODERATELY_STRONG_POSITIVE,
				benevolenceDependability: MODERATELY_WEAK_POSITIVE,
				benevolenceCaring: VERY_WEAK_POSITIVE,
				universalismConcern: NEGLIGIBLE_NEGATIVE,
				universalismNature: EXTREMELY_STRONG_NEGATIVE,
				universalismTolerance: VERY_WEAK_POSITIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: EXTREMELY_STRONG_POSITIVE,
				stimulation: MINIMAL_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: WEAK_POSITIVE,
				powerDominance: MODERATELY_STRONG_POSITIVE,
				powerResources: WEAK_POSITIVE,
				face: MODERATE_POSITIVE,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: VERY_WEAK_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: VERY_WEAK_NEGATIVE,
				humility: MODERATELY_STRONG_NEGATIVE,
				benevolenceDependability: MODERATELY_WEAK_NEGATIVE,
				benevolenceCaring: VERY_WEAK_NEGATIVE,
				universalismConcern: NEGLIGIBLE_POSITIVE,
				universalismNature: EXTREMELY_STRONG_POSITIVE,
				universalismTolerance: VERY_WEAK_NEGATIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
		},

		// H2
		H2: {
			high: {
				selfDirectionThought: EXTREMELY_STRONG_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: NEGLIGIBLE_POSITIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: VERY_WEAK_NEGATIVE,
				powerDominance: MODERATE_NEGATIVE,
				powerResources: STRONG_NEGATIVE,
				face: NEGLIGIBLE_NEGATIVE,
				securityPersonal: EXTREMELY_STRONG_NEGATIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: WEAK_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: MINIMAL_POSITIVE,
				humility: WEAK_POSITIVE,
				benevolenceDependability: VERY_WEAK_POSITIVE,
				benevolenceCaring: MODERATELY_WEAK_POSITIVE,
				universalismConcern: STRONG_POSITIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: VERY_WEAK_POSITIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
			low: {
				selfDirectionThought: EXTREMELY_STRONG_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: NEGLIGIBLE_NEGATIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: VERY_WEAK_POSITIVE,
				powerDominance: MODERATE_POSITIVE,
				powerResources: STRONG_POSITIVE,
				face: NEGLIGIBLE_POSITIVE,
				securityPersonal: EXTREMELY_STRONG_POSITIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: WEAK_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: MINIMAL_NEGATIVE,
				humility: WEAK_NEGATIVE,
				benevolenceDependability: VERY_WEAK_NEGATIVE,
				benevolenceCaring: MODERATELY_WEAK_NEGATIVE,
				universalismConcern: STRONG_NEGATIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: VERY_WEAK_NEGATIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
		},

		// H3
		H3: {
			high: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: NEGLIGIBLE_NEGATIVE,
				hedonism: MINIMAL_NEGATIVE,
				achievement: MODERATE_NEGATIVE,
				powerDominance: WEAK_NEGATIVE,
				powerResources: VERY_STRONG_NEGATIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: NEGLIGIBLE_POSITIVE,
				conformityInterpersonal: MINIMAL_POSITIVE,
				humility: VERY_STRONG_POSITIVE,
				benevolenceDependability: MINIMAL_POSITIVE,
				benevolenceCaring: WEAK_POSITIVE,
				universalismConcern: MODERATE_POSITIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: EXTREMELY_STRONG_NEGATIVE,
				universalismObjectivity: VERY_WEAK_POSITIVE,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: NEGLIGIBLE_POSITIVE,
				hedonism: MINIMAL_POSITIVE,
				achievement: MODERATE_POSITIVE,
				powerDominance: WEAK_POSITIVE,
				powerResources: VERY_STRONG_POSITIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: NEGLIGIBLE_NEGATIVE,
				conformityInterpersonal: MINIMAL_NEGATIVE,
				humility: VERY_STRONG_NEGATIVE,
				benevolenceDependability: MINIMAL_NEGATIVE,
				benevolenceCaring: WEAK_NEGATIVE,
				universalismConcern: MODERATE_NEGATIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: EXTREMELY_STRONG_POSITIVE,
				universalismObjectivity: VERY_WEAK_NEGATIVE,
			},
		},

		// H4
		H4: {
			high: {
				selfDirectionThought: EXTREMELY_STRONG_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: VERY_WEAK_NEGATIVE,
				powerDominance: STRONG_NEGATIVE,
				powerResources: VERY_WEAK_NEGATIVE,
				face: MODERATE_NEGATIVE,
				securityPersonal: EXTREMELY_STRONG_NEGATIVE,
				securitySocietal: NEGLIGIBLE_POSITIVE,
				tradition: VERY_WEAK_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: MODERATELY_WEAK_POSITIVE,
				humility: EXTREMELY_STRONG_POSITIVE,
				benevolenceDependability: VERY_WEAK_POSITIVE,
				benevolenceCaring: MINIMAL_POSITIVE,
				universalismConcern: WEAK_POSITIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
			low: {
				selfDirectionThought: EXTREMELY_STRONG_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: MINIMAL_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: VERY_WEAK_POSITIVE,
				powerDominance: STRONG_POSITIVE,
				powerResources: VERY_WEAK_POSITIVE,
				face: MODERATE_POSITIVE,
				securityPersonal: EXTREMELY_STRONG_POSITIVE,
				securitySocietal: NEGLIGIBLE_NEGATIVE,
				tradition: VERY_WEAK_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: MODERATELY_WEAK_NEGATIVE,
				humility: EXTREMELY_STRONG_NEGATIVE,
				benevolenceDependability: VERY_WEAK_NEGATIVE,
				benevolenceCaring: MINIMAL_NEGATIVE,
				universalismConcern: WEAK_NEGATIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
		},

		// E1
		E1: {
			high: {
				selfDirectionThought: WEAK_NEGATIVE,
				selfDirectionAction: MODERATELY_WEAK_NEGATIVE,
				stimulation: STRONG_NEGATIVE,
				hedonism: VERY_WEAK_NEGATIVE,
				achievement: NEGLIGIBLE_NEGATIVE,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: EXTREMELY_STRONG_POSITIVE,
				face: EXTREMELY_STRONG_POSITIVE,
				securityPersonal: VERY_STRONG_POSITIVE,
				securitySocietal: MODERATE_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: VERY_WEAK_POSITIVE,
				conformityInterpersonal: MINIMAL_POSITIVE,
				humility: EXTREMELY_STRONG_NEGATIVE,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: EXTREMELY_STRONG_NEGATIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: EXTREMELY_STRONG_NEGATIVE,
			},
			low: {
				selfDirectionThought: WEAK_POSITIVE,
				selfDirectionAction: MODERATELY_WEAK_POSITIVE,
				stimulation: STRONG_POSITIVE,
				hedonism: VERY_WEAK_POSITIVE,
				achievement: NEGLIGIBLE_POSITIVE,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: EXTREMELY_STRONG_NEGATIVE,
				face: EXTREMELY_STRONG_NEGATIVE,
				securityPersonal: VERY_STRONG_NEGATIVE,
				securitySocietal: MODERATE_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: VERY_WEAK_NEGATIVE,
				conformityInterpersonal: MINIMAL_NEGATIVE,
				humility: EXTREMELY_STRONG_POSITIVE,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: EXTREMELY_STRONG_POSITIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: EXTREMELY_STRONG_POSITIVE,
			},
		},

		// E2
		E2: {
			high: {
				selfDirectionThought: MODERATE_NEGATIVE,
				selfDirectionAction: WEAK_NEGATIVE,
				stimulation: VERY_WEAK_NEGATIVE,
				hedonism: MINIMAL_NEGATIVE,
				achievement: NEGLIGIBLE_NEGATIVE,
				powerDominance: EXTREMELY_STRONG_POSITIVE,
				powerResources: EXTREMELY_STRONG_POSITIVE,
				face: EXTREMELY_STRONG_POSITIVE,
				securityPersonal: STRONG_POSITIVE,
				securitySocietal: MODERATELY_WEAK_POSITIVE,
				tradition: NEGLIGIBLE_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: EXTREMELY_STRONG_NEGATIVE,
				humility: EXTREMELY_STRONG_NEGATIVE,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: EXTREMELY_STRONG_NEGATIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_NEGATIVE,
			},
			low: {
				selfDirectionThought: MODERATE_POSITIVE,
				selfDirectionAction: WEAK_POSITIVE,
				stimulation: VERY_WEAK_POSITIVE,
				hedonism: MINIMAL_POSITIVE,
				achievement: NEGLIGIBLE_POSITIVE,
				powerDominance: EXTREMELY_STRONG_NEGATIVE,
				powerResources: EXTREMELY_STRONG_NEGATIVE,
				face: EXTREMELY_STRONG_NEGATIVE,
				securityPersonal: STRONG_NEGATIVE,
				securitySocietal: MODERATELY_WEAK_NEGATIVE,
				tradition: NEGLIGIBLE_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: EXTREMELY_STRONG_POSITIVE,
				humility: EXTREMELY_STRONG_POSITIVE,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: EXTREMELY_STRONG_POSITIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_POSITIVE,
			},
		},

		// E3
		E3: {
			high: {
				selfDirectionThought: MODERATE_NEGATIVE,
				selfDirectionAction: MODERATELY_STRONG_NEGATIVE,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: MINIMAL_NEGATIVE,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: EXTREMELY_STRONG_POSITIVE,
				face: EXTREMELY_STRONG_POSITIVE,
				securityPersonal: MODERATELY_STRONG_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: NEGLIGIBLE_POSITIVE,
				conformityRules: NEGLIGIBLE_POSITIVE,
				conformityInterpersonal: WEAK_POSITIVE,
				humility: EXTREMELY_STRONG_NEGATIVE,
				benevolenceDependability: MINIMAL_POSITIVE,
				benevolenceCaring: MODERATE_POSITIVE,
				universalismConcern: MINIMAL_POSITIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_NEGATIVE,
			},
			low: {
				selfDirectionThought: MODERATE_POSITIVE,
				selfDirectionAction: MODERATELY_STRONG_POSITIVE,
				stimulation: MINIMAL_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: MINIMAL_POSITIVE,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: EXTREMELY_STRONG_NEGATIVE,
				face: EXTREMELY_STRONG_NEGATIVE,
				securityPersonal: MODERATELY_STRONG_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: NEGLIGIBLE_NEGATIVE,
				conformityRules: NEGLIGIBLE_NEGATIVE,
				conformityInterpersonal: WEAK_NEGATIVE,
				humility: EXTREMELY_STRONG_POSITIVE,
				benevolenceDependability: MINIMAL_NEGATIVE,
				benevolenceCaring: MODERATE_NEGATIVE,
				universalismConcern: MINIMAL_NEGATIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_POSITIVE,
			},
		},

		// E4
		E4: {
			high: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: NEGLIGIBLE_NEGATIVE,
				hedonism: MINIMAL_NEGATIVE,
				achievement: MODERATELY_WEAK_NEGATIVE,
				powerDominance: MODERATELY_STRONG_NEGATIVE,
				powerResources: MINIMAL_NEGATIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: EXTREMELY_STRONG_NEGATIVE,
				tradition: VERY_WEAK_POSITIVE,
				conformityRules: EXTREMELY_STRONG_POSITIVE,
				conformityInterpersonal: VERY_WEAK_POSITIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: MODERATE_POSITIVE,
				benevolenceCaring: STRONG_POSITIVE,
				universalismConcern: VERY_WEAK_POSITIVE,
				universalismNature: VERY_WEAK_POSITIVE,
				universalismTolerance: MODERATE_NEGATIVE,
				universalismObjectivity: EXTREMELY_STRONG_NEGATIVE,
			},
			low: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: NEGLIGIBLE_POSITIVE,
				hedonism: MINIMAL_POSITIVE,
				achievement: MODERATELY_WEAK_POSITIVE,
				powerDominance: MODERATELY_STRONG_POSITIVE,
				powerResources: MINIMAL_POSITIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: EXTREMELY_STRONG_POSITIVE,
				tradition: VERY_WEAK_NEGATIVE,
				conformityRules: EXTREMELY_STRONG_NEGATIVE,
				conformityInterpersonal: VERY_WEAK_NEGATIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: MODERATE_NEGATIVE,
				benevolenceCaring: STRONG_NEGATIVE,
				universalismConcern: VERY_WEAK_NEGATIVE,
				universalismNature: VERY_WEAK_NEGATIVE,
				universalismTolerance: MODERATE_POSITIVE,
				universalismObjectivity: EXTREMELY_STRONG_POSITIVE,
			},
		},

		// X1
		X1: {
			high: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: MODERATELY_WEAK_POSITIVE,
				stimulation: MINIMAL_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: MODERATELY_STRONG_POSITIVE,
				powerDominance: VERY_WEAK_POSITIVE,
				powerResources: MINIMAL_POSITIVE,
				face: NEGLIGIBLE_POSITIVE,
				securityPersonal: MODERATE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: MINIMAL_NEGATIVE,
				humility: MODERATELY_WEAK_NEGATIVE,
				benevolenceDependability: EXTREMELY_STRONG_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: EXTREMELY_STRONG_NEGATIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: MINIMAL_NEGATIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
			low: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: MODERATELY_WEAK_NEGATIVE,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: MODERATELY_STRONG_NEGATIVE,
				powerDominance: VERY_WEAK_NEGATIVE,
				powerResources: MINIMAL_NEGATIVE,
				face: NEGLIGIBLE_NEGATIVE,
				securityPersonal: MODERATE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: MINIMAL_POSITIVE,
				humility: MODERATELY_WEAK_POSITIVE,
				benevolenceDependability: EXTREMELY_STRONG_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: EXTREMELY_STRONG_POSITIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: MINIMAL_POSITIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
		},

		// X2
		X2: {
			high: {
				selfDirectionThought: WEAK_POSITIVE,
				selfDirectionAction: MODERATE_POSITIVE,
				stimulation: STRONG_POSITIVE,
				hedonism: MINIMAL_POSITIVE,
				achievement: MINIMAL_POSITIVE,
				powerDominance: MODERATELY_WEAK_POSITIVE,
				powerResources: NEGLIGIBLE_POSITIVE,
				face: MODERATELY_WEAK_POSITIVE,
				securityPersonal: MODERATELY_STRONG_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: VERY_WEAK_NEGATIVE,
				conformityRules: MODERATE_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: VERY_WEAK_NEGATIVE,
				benevolenceDependability: MODERATE_NEGATIVE,
				benevolenceCaring: MODERATELY_STRONG_NEGATIVE,
				universalismConcern: EXTREMELY_STRONG_NEGATIVE,
				universalismNature: WEAK_NEGATIVE,
				universalismTolerance: VERY_WEAK_NEGATIVE,
				universalismObjectivity: MODERATELY_WEAK_NEGATIVE,
			},
			low: {
				selfDirectionThought: WEAK_NEGATIVE,
				selfDirectionAction: MODERATE_NEGATIVE,
				stimulation: STRONG_NEGATIVE,
				hedonism: MINIMAL_NEGATIVE,
				achievement: MINIMAL_NEGATIVE,
				powerDominance: MODERATELY_WEAK_NEGATIVE,
				powerResources: NEGLIGIBLE_NEGATIVE,
				face: MODERATELY_WEAK_NEGATIVE,
				securityPersonal: MODERATELY_STRONG_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: VERY_WEAK_POSITIVE,
				conformityRules: MODERATE_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: VERY_WEAK_POSITIVE,
				benevolenceDependability: MODERATE_POSITIVE,
				benevolenceCaring: MODERATELY_STRONG_POSITIVE,
				universalismConcern: EXTREMELY_STRONG_POSITIVE,
				universalismNature: WEAK_POSITIVE,
				universalismTolerance: VERY_WEAK_POSITIVE,
				universalismObjectivity: MODERATELY_WEAK_POSITIVE,
			},
		},

		// X3
		X3: {
			high: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: MODERATELY_WEAK_POSITIVE,
				hedonism: VERY_WEAK_POSITIVE,
				achievement: NO_CORRELATION,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: MINIMAL_POSITIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: MODERATELY_WEAK_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MODERATELY_STRONG_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: VERY_WEAK_POSITIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: EXTREMELY_STRONG_NEGATIVE,
				benevolenceCaring: MODERATELY_STRONG_POSITIVE,
				universalismConcern: WEAK_POSITIVE,
				universalismNature: WEAK_NEGATIVE,
				universalismTolerance: VERY_WEAK_POSITIVE,
				universalismObjectivity: NO_CORRELATION,
			},
			low: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: MODERATELY_WEAK_NEGATIVE,
				hedonism: VERY_WEAK_NEGATIVE,
				achievement: NO_CORRELATION,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: MINIMAL_NEGATIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: MODERATELY_WEAK_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MODERATELY_STRONG_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: VERY_WEAK_NEGATIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: EXTREMELY_STRONG_POSITIVE,
				benevolenceCaring: MODERATELY_STRONG_NEGATIVE,
				universalismConcern: WEAK_NEGATIVE,
				universalismNature: WEAK_POSITIVE,
				universalismTolerance: VERY_WEAK_NEGATIVE,
				universalismObjectivity: NO_CORRELATION,
			},
		},

		// X4
		X4: {
			high: {
				selfDirectionThought: MINIMAL_POSITIVE,
				selfDirectionAction: VERY_WEAK_POSITIVE,
				stimulation: VERY_STRONG_POSITIVE,
				hedonism: MODERATE_POSITIVE,
				achievement: NEGLIGIBLE_POSITIVE,
				powerDominance: EXTREMELY_STRONG_POSITIVE,
				powerResources: EXTREMELY_STRONG_POSITIVE,
				face: NO_CORRELATION,
				securityPersonal: MINIMAL_NEGATIVE,
				securitySocietal: VERY_WEAK_NEGATIVE,
				tradition: STRONG_NEGATIVE,
				conformityRules: MODERATE_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: EXTREMELY_STRONG_NEGATIVE,
				benevolenceDependability: EXTREMELY_STRONG_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: MODERATELY_STRONG_NEGATIVE,
				universalismNature: MINIMAL_NEGATIVE,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: NO_CORRELATION,
			},
			low: {
				selfDirectionThought: MINIMAL_NEGATIVE,
				selfDirectionAction: VERY_WEAK_NEGATIVE,
				stimulation: VERY_STRONG_NEGATIVE,
				hedonism: MODERATE_NEGATIVE,
				achievement: NEGLIGIBLE_NEGATIVE,
				powerDominance: EXTREMELY_STRONG_NEGATIVE,
				powerResources: EXTREMELY_STRONG_NEGATIVE,
				face: NO_CORRELATION,
				securityPersonal: MINIMAL_POSITIVE,
				securitySocietal: VERY_WEAK_POSITIVE,
				tradition: STRONG_POSITIVE,
				conformityRules: MODERATE_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: EXTREMELY_STRONG_POSITIVE,
				benevolenceDependability: EXTREMELY_STRONG_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: MODERATELY_STRONG_POSITIVE,
				universalismNature: MINIMAL_POSITIVE,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: NO_CORRELATION,
			},
		},

		// A1
		A1: {
			high: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: NEGLIGIBLE_NEGATIVE,
				hedonism: EXTREMELY_STRONG_POSITIVE,
				achievement: WEAK_NEGATIVE,
				powerDominance: MODERATELY_STRONG_NEGATIVE,
				powerResources: VERY_WEAK_NEGATIVE,
				face: MODERATELY_WEAK_NEGATIVE,
				securityPersonal: NO_CORRELATION,
				securitySocietal: NEGLIGIBLE_POSITIVE,
				tradition: NEGLIGIBLE_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: VERY_WEAK_POSITIVE,
				humility: VERY_WEAK_POSITIVE,
				benevolenceDependability: VERY_WEAK_POSITIVE,
				benevolenceCaring: MODERATE_POSITIVE,
				universalismConcern: VERY_WEAK_POSITIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: MODERATELY_STRONG_POSITIVE,
				universalismObjectivity: NEGLIGIBLE_POSITIVE,
			},
			low: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: NEGLIGIBLE_POSITIVE,
				hedonism: EXTREMELY_STRONG_NEGATIVE,
				achievement: WEAK_POSITIVE,
				powerDominance: MODERATELY_STRONG_POSITIVE,
				powerResources: VERY_WEAK_POSITIVE,
				face: MODERATELY_WEAK_POSITIVE,
				securityPersonal: NO_CORRELATION,
				securitySocietal: NEGLIGIBLE_NEGATIVE,
				tradition: NEGLIGIBLE_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: VERY_WEAK_NEGATIVE,
				humility: VERY_WEAK_NEGATIVE,
				benevolenceDependability: VERY_WEAK_NEGATIVE,
				benevolenceCaring: MODERATE_NEGATIVE,
				universalismConcern: VERY_WEAK_NEGATIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: MODERATELY_STRONG_NEGATIVE,
				universalismObjectivity: NEGLIGIBLE_NEGATIVE,
			},
		},

		// A2
		A2: {
			high: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: WEAK_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: MINIMAL_NEGATIVE,
				powerDominance: STRONG_NEGATIVE,
				powerResources: MODERATELY_WEAK_NEGATIVE,
				face: VERY_WEAK_NEGATIVE,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: NEGLIGIBLE_POSITIVE,
				conformityInterpersonal: VERY_WEAK_POSITIVE,
				humility: MODERATELY_WEAK_POSITIVE,
				benevolenceDependability: VERY_WEAK_POSITIVE,
				benevolenceCaring: VERY_STRONG_POSITIVE,
				universalismConcern: MODERATELY_WEAK_POSITIVE,
				universalismNature: VERY_WEAK_POSITIVE,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: NO_CORRELATION,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: WEAK_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: MINIMAL_POSITIVE,
				powerDominance: STRONG_POSITIVE,
				powerResources: MODERATELY_WEAK_POSITIVE,
				face: VERY_WEAK_POSITIVE,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: NEGLIGIBLE_NEGATIVE,
				conformityInterpersonal: VERY_WEAK_NEGATIVE,
				humility: MODERATELY_WEAK_NEGATIVE,
				benevolenceDependability: VERY_WEAK_NEGATIVE,
				benevolenceCaring: VERY_STRONG_NEGATIVE,
				universalismConcern: MODERATELY_WEAK_NEGATIVE,
				universalismNature: VERY_WEAK_NEGATIVE,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: NO_CORRELATION,
			},
		},

		// A3
		A3: {
			high: {
				selfDirectionThought: MODERATELY_WEAK_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: EXTREMELY_STRONG_POSITIVE,
				hedonism: EXTREMELY_STRONG_POSITIVE,
				achievement: NEGLIGIBLE_NEGATIVE,
				powerDominance: MINIMAL_NEGATIVE,
				powerResources: MINIMAL_NEGATIVE,
				face: NEGLIGIBLE_NEGATIVE,
				securityPersonal: NO_CORRELATION,
				securitySocietal: NEGLIGIBLE_POSITIVE,
				tradition: MODERATE_NEGATIVE,
				conformityRules: WEAK_NEGATIVE,
				conformityInterpersonal: MINIMAL_POSITIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: VERY_WEAK_POSITIVE,
				benevolenceCaring: MINIMAL_POSITIVE,
				universalismConcern: MINIMAL_POSITIVE,
				universalismNature: MINIMAL_POSITIVE,
				universalismTolerance: MODERATE_POSITIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
			low: {
				selfDirectionThought: MODERATELY_WEAK_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: EXTREMELY_STRONG_NEGATIVE,
				hedonism: EXTREMELY_STRONG_NEGATIVE,
				achievement: NEGLIGIBLE_POSITIVE,
				powerDominance: MINIMAL_POSITIVE,
				powerResources: MINIMAL_POSITIVE,
				face: NEGLIGIBLE_POSITIVE,
				securityPersonal: NO_CORRELATION,
				securitySocietal: NEGLIGIBLE_NEGATIVE,
				tradition: MODERATE_POSITIVE,
				conformityRules: WEAK_POSITIVE,
				conformityInterpersonal: MINIMAL_NEGATIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: VERY_WEAK_NEGATIVE,
				benevolenceCaring: MINIMAL_NEGATIVE,
				universalismConcern: MINIMAL_NEGATIVE,
				universalismNature: MINIMAL_NEGATIVE,
				universalismTolerance: MODERATE_NEGATIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
		},

		// A4
		A4: {
			high: {
				selfDirectionThought: NO_CORRELATION,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: MODERATELY_STRONG_NEGATIVE,
				hedonism: WEAK_NEGATIVE,
				achievement: NO_CORRELATION,
				powerDominance: MINIMAL_NEGATIVE,
				powerResources: NO_CORRELATION,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: NEGLIGIBLE_POSITIVE,
				conformityInterpersonal: STRONG_POSITIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: MODERATE_POSITIVE,
				benevolenceCaring: VERY_WEAK_POSITIVE,
				universalismConcern: MINIMAL_NEGATIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_POSITIVE,
			},
			low: {
				selfDirectionThought: NO_CORRELATION,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: MODERATELY_STRONG_POSITIVE,
				hedonism: WEAK_POSITIVE,
				achievement: NO_CORRELATION,
				powerDominance: MINIMAL_POSITIVE,
				powerResources: NO_CORRELATION,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: NEGLIGIBLE_NEGATIVE,
				conformityInterpersonal: STRONG_NEGATIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: MODERATE_NEGATIVE,
				benevolenceCaring: VERY_WEAK_NEGATIVE,
				universalismConcern: MINIMAL_POSITIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: NEGLIGIBLE_NEGATIVE,
			},
		},

		// C1
		C1: {
			high: {
				selfDirectionThought: MINIMAL_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: MODERATE_NEGATIVE,
				hedonism: WEAK_NEGATIVE,
				achievement: STRONG_POSITIVE,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: NEGLIGIBLE_POSITIVE,
				face: NO_CORRELATION,
				securityPersonal: WEAK_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: VERY_WEAK_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: NEGLIGIBLE_NEGATIVE,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: WEAK_NEGATIVE,
				universalismObjectivity: NO_CORRELATION,
			},
			low: {
				selfDirectionThought: MINIMAL_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: MODERATE_POSITIVE,
				hedonism: WEAK_POSITIVE,
				achievement: STRONG_NEGATIVE,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: NEGLIGIBLE_NEGATIVE,
				face: NO_CORRELATION,
				securityPersonal: WEAK_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: VERY_WEAK_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: NEGLIGIBLE_POSITIVE,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: WEAK_POSITIVE,
				universalismObjectivity: NO_CORRELATION,
			},
		},

		// C2
		C2: {
			high: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: NO_CORRELATION,
				stimulation: WEAK_NEGATIVE,
				hedonism: MODERATELY_STRONG_NEGATIVE,
				achievement: VERY_STRONG_POSITIVE,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: NO_CORRELATION,
				face: NEGLIGIBLE_POSITIVE,
				securityPersonal: MINIMAL_POSITIVE,
				securitySocietal: NEGLIGIBLE_POSITIVE,
				tradition: EXTREMELY_STRONG_POSITIVE,
				conformityRules: MINIMAL_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: MODERATELY_WEAK_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: VERY_WEAK_NEGATIVE,
				universalismTolerance: VERY_WEAK_NEGATIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
			low: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: NO_CORRELATION,
				stimulation: WEAK_POSITIVE,
				hedonism: MODERATELY_STRONG_POSITIVE,
				achievement: VERY_STRONG_NEGATIVE,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: NO_CORRELATION,
				face: NEGLIGIBLE_NEGATIVE,
				securityPersonal: MINIMAL_NEGATIVE,
				securitySocietal: NEGLIGIBLE_NEGATIVE,
				tradition: EXTREMELY_STRONG_NEGATIVE,
				conformityRules: MINIMAL_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: MODERATELY_WEAK_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: VERY_WEAK_POSITIVE,
				universalismTolerance: VERY_WEAK_POSITIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
		},

		// C3
		C3: {
			high: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: NO_CORRELATION,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: MODERATE_NEGATIVE,
				achievement: EXTREMELY_STRONG_POSITIVE,
				powerDominance: MINIMAL_POSITIVE,
				powerResources: NEGLIGIBLE_POSITIVE,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: WEAK_NEGATIVE,
				tradition: EXTREMELY_STRONG_POSITIVE,
				conformityRules: VERY_WEAK_POSITIVE,
				conformityInterpersonal: EXTREMELY_STRONG_NEGATIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: WEAK_POSITIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: WEAK_NEGATIVE,
				universalismObjectivity: NO_CORRELATION,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: NO_CORRELATION,
				stimulation: MINIMAL_POSITIVE,
				hedonism: MODERATE_POSITIVE,
				achievement: EXTREMELY_STRONG_NEGATIVE,
				powerDominance: MINIMAL_NEGATIVE,
				powerResources: NEGLIGIBLE_NEGATIVE,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: WEAK_POSITIVE,
				tradition: EXTREMELY_STRONG_NEGATIVE,
				conformityRules: VERY_WEAK_NEGATIVE,
				conformityInterpersonal: EXTREMELY_STRONG_POSITIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: WEAK_NEGATIVE,
				universalismNature: NO_CORRELATION,
				universalismTolerance: WEAK_POSITIVE,
				universalismObjectivity: NO_CORRELATION,
			},
		},

		// C4
		C4: {
			high: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: VERY_STRONG_NEGATIVE,
				hedonism: WEAK_NEGATIVE,
				achievement: MINIMAL_POSITIVE,
				powerDominance: EXTREMELY_STRONG_POSITIVE,
				powerResources: NO_CORRELATION,
				face: MINIMAL_POSITIVE,
				securityPersonal: STRONG_POSITIVE,
				securitySocietal: VERY_WEAK_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: MODERATE_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: VERY_STRONG_POSITIVE,
				hedonism: WEAK_POSITIVE,
				achievement: MINIMAL_NEGATIVE,
				powerDominance: EXTREMELY_STRONG_NEGATIVE,
				powerResources: NO_CORRELATION,
				face: MINIMAL_NEGATIVE,
				securityPersonal: STRONG_NEGATIVE,
				securitySocietal: VERY_WEAK_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: MODERATE_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NO_CORRELATION,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
		},

		// O1
		O1: {
			high: {
				selfDirectionThought: STRONG_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: NEGLIGIBLE_POSITIVE,
				hedonism: MODERATELY_WEAK_POSITIVE,
				achievement: WEAK_NEGATIVE,
				powerDominance: MINIMAL_NEGATIVE,
				powerResources: MODERATE_NEGATIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: MINIMAL_NEGATIVE,
				securitySocietal: NEGLIGIBLE_NEGATIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: VERY_WEAK_NEGATIVE,
				conformityInterpersonal: EXTREMELY_STRONG_NEGATIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: MINIMAL_POSITIVE,
				universalismNature: MODERATE_POSITIVE,
				universalismTolerance: NEGLIGIBLE_POSITIVE,
				universalismObjectivity: MINIMAL_POSITIVE,
			},
			low: {
				selfDirectionThought: STRONG_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: NEGLIGIBLE_NEGATIVE,
				hedonism: MODERATELY_WEAK_NEGATIVE,
				achievement: WEAK_POSITIVE,
				powerDominance: MINIMAL_POSITIVE,
				powerResources: MODERATE_POSITIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: MINIMAL_POSITIVE,
				securitySocietal: NEGLIGIBLE_POSITIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: VERY_WEAK_POSITIVE,
				conformityInterpersonal: EXTREMELY_STRONG_POSITIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: MINIMAL_NEGATIVE,
				universalismNature: MODERATE_NEGATIVE,
				universalismTolerance: NEGLIGIBLE_NEGATIVE,
				universalismObjectivity: MINIMAL_NEGATIVE,
			},
		},

		// O2
		O2: {
			high: {
				selfDirectionThought: EXTREMELY_STRONG_POSITIVE,
				selfDirectionAction: MINIMAL_POSITIVE,
				stimulation: MODERATELY_WEAK_POSITIVE,
				hedonism: NO_CORRELATION,
				achievement: NO_CORRELATION,
				powerDominance: EXTREMELY_STRONG_POSITIVE,
				powerResources: NO_CORRELATION,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MINIMAL_NEGATIVE,
				tradition: MODERATELY_STRONG_NEGATIVE,
				conformityRules: MODERATELY_WEAK_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: EXTREMELY_STRONG_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: MODERATE_POSITIVE,
			},
			low: {
				selfDirectionThought: EXTREMELY_STRONG_NEGATIVE,
				selfDirectionAction: MINIMAL_NEGATIVE,
				stimulation: MODERATELY_WEAK_NEGATIVE,
				hedonism: NO_CORRELATION,
				achievement: NO_CORRELATION,
				powerDominance: EXTREMELY_STRONG_NEGATIVE,
				powerResources: NO_CORRELATION,
				face: NO_CORRELATION,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MINIMAL_POSITIVE,
				tradition: MODERATELY_STRONG_POSITIVE,
				conformityRules: MODERATELY_WEAK_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: NO_CORRELATION,
				benevolenceDependability: EXTREMELY_STRONG_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: MODERATE_NEGATIVE,
			},
		},

		// O3
		O3: {
			high: {
				selfDirectionThought: VERY_STRONG_POSITIVE,
				selfDirectionAction: MODERATE_POSITIVE,
				stimulation: VERY_WEAK_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: NO_CORRELATION,
				powerDominance: MODERATE_POSITIVE,
				powerResources: NEGLIGIBLE_NEGATIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: MINIMAL_NEGATIVE,
				securitySocietal: VERY_WEAK_NEGATIVE,
				tradition: MODERATE_NEGATIVE,
				conformityRules: MODERATELY_STRONG_NEGATIVE,
				conformityInterpersonal: EXTREMELY_STRONG_NEGATIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: NEGLIGIBLE_POSITIVE,
				benevolenceCaring: NEGLIGIBLE_POSITIVE,
				universalismConcern: MINIMAL_NEGATIVE,
				universalismNature: NEGLIGIBLE_POSITIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: MODERATELY_WEAK_POSITIVE,
			},
			low: {
				selfDirectionThought: VERY_STRONG_NEGATIVE,
				selfDirectionAction: MODERATE_NEGATIVE,
				stimulation: VERY_WEAK_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: NO_CORRELATION,
				powerDominance: MODERATE_NEGATIVE,
				powerResources: NEGLIGIBLE_POSITIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: MINIMAL_POSITIVE,
				securitySocietal: VERY_WEAK_POSITIVE,
				tradition: MODERATE_POSITIVE,
				conformityRules: MODERATELY_STRONG_POSITIVE,
				conformityInterpersonal: EXTREMELY_STRONG_POSITIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: NEGLIGIBLE_NEGATIVE,
				benevolenceCaring: NEGLIGIBLE_NEGATIVE,
				universalismConcern: MINIMAL_POSITIVE,
				universalismNature: NEGLIGIBLE_NEGATIVE,
				universalismTolerance: NO_CORRELATION,
				universalismObjectivity: MODERATELY_WEAK_NEGATIVE,
			},
		},

		// O4
		O4: {
			high: {
				selfDirectionThought: VERY_WEAK_POSITIVE,
				selfDirectionAction: MODERATELY_WEAK_POSITIVE,
				stimulation: EXTREMELY_STRONG_POSITIVE,
				hedonism: MINIMAL_POSITIVE,
				achievement: NO_CORRELATION,
				powerDominance: NEGLIGIBLE_POSITIVE,
				powerResources: NO_CORRELATION,
				face: MODERATELY_WEAK_NEGATIVE,
				securityPersonal: NEGLIGIBLE_NEGATIVE,
				securitySocietal: MODERATE_NEGATIVE,
				tradition: VERY_STRONG_NEGATIVE,
				conformityRules: MODERATELY_STRONG_NEGATIVE,
				conformityInterpersonal: NEGLIGIBLE_NEGATIVE,
				humility: MINIMAL_POSITIVE,
				benevolenceDependability: EXTREMELY_STRONG_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: MINIMAL_POSITIVE,
				universalismTolerance: MODERATE_POSITIVE,
				universalismObjectivity: VERY_WEAK_POSITIVE,
			},
			low: {
				selfDirectionThought: VERY_WEAK_NEGATIVE,
				selfDirectionAction: MODERATELY_WEAK_NEGATIVE,
				stimulation: EXTREMELY_STRONG_NEGATIVE,
				hedonism: MINIMAL_NEGATIVE,
				achievement: NO_CORRELATION,
				powerDominance: NEGLIGIBLE_NEGATIVE,
				powerResources: NO_CORRELATION,
				face: MODERATELY_WEAK_POSITIVE,
				securityPersonal: NEGLIGIBLE_POSITIVE,
				securitySocietal: MODERATE_POSITIVE,
				tradition: VERY_STRONG_POSITIVE,
				conformityRules: MODERATELY_STRONG_POSITIVE,
				conformityInterpersonal: NEGLIGIBLE_POSITIVE,
				humility: MINIMAL_NEGATIVE,
				benevolenceDependability: EXTREMELY_STRONG_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: NO_CORRELATION,
				universalismNature: MINIMAL_NEGATIVE,
				universalismTolerance: MODERATE_NEGATIVE,
				universalismObjectivity: VERY_WEAK_NEGATIVE,
			},
		},

		// Alt1
		Alt1: {
			high: {
				selfDirectionThought: NEGLIGIBLE_POSITIVE,
				selfDirectionAction: NEGLIGIBLE_POSITIVE,
				stimulation: MINIMAL_NEGATIVE,
				hedonism: NEGLIGIBLE_NEGATIVE,
				achievement: MINIMAL_NEGATIVE,
				powerDominance: MODERATELY_WEAK_NEGATIVE,
				powerResources: WEAK_NEGATIVE,
				face: MINIMAL_NEGATIVE,
				securityPersonal: MINIMAL_POSITIVE,
				securitySocietal: VERY_WEAK_POSITIVE,
				tradition: MINIMAL_POSITIVE,
				conformityRules: NEGLIGIBLE_POSITIVE,
				conformityInterpersonal: MODERATELY_WEAK_POSITIVE,
				humility: MODERATE_POSITIVE,
				benevolenceDependability: STRONG_POSITIVE,
				benevolenceCaring: EXTREMELY_STRONG_POSITIVE,
				universalismConcern: VERY_STRONG_POSITIVE,
				universalismNature: WEAK_POSITIVE,
				universalismTolerance: MODERATELY_WEAK_POSITIVE,
				universalismObjectivity: WEAK_POSITIVE,
			},
			low: {
				selfDirectionThought: NEGLIGIBLE_NEGATIVE,
				selfDirectionAction: NEGLIGIBLE_NEGATIVE,
				stimulation: MINIMAL_POSITIVE,
				hedonism: NEGLIGIBLE_POSITIVE,
				achievement: MINIMAL_POSITIVE,
				powerDominance: MODERATELY_WEAK_POSITIVE,
				powerResources: WEAK_POSITIVE,
				face: MINIMAL_POSITIVE,
				securityPersonal: MINIMAL_NEGATIVE,
				securitySocietal: VERY_WEAK_NEGATIVE,
				tradition: MINIMAL_NEGATIVE,
				conformityRules: NEGLIGIBLE_NEGATIVE,
				conformityInterpersonal: MODERATELY_WEAK_NEGATIVE,
				humility: MODERATE_NEGATIVE,
				benevolenceDependability: STRONG_NEGATIVE,
				benevolenceCaring: EXTREMELY_STRONG_NEGATIVE,
				universalismConcern: VERY_STRONG_NEGATIVE,
				universalismNature: WEAK_NEGATIVE,
				universalismTolerance: MODERATELY_WEAK_NEGATIVE,
				universalismObjectivity: WEAK_NEGATIVE,
			},
		},
	};
	const totals20 = {
		selfDirectionThought: 0,
		selfDirectionAction: 0,
		stimulation: 0,
		hedonism: 0,
		achievement: 0,
		powerDominance: 0,
		powerResources: 0,
		face: 0,
		securityPersonal: 0,
		securitySocietal: 0,
		conformityRules: 0,
		conformityInterpersonal: 0,
		tradition: 0,
		humility: 0,
		benevolenceCaring: 0,
		benevolenceDependability: 0,
		universalismConcern: 0,
		universalismNature: 0,
		universalismTolerance: 0,
		universalismObjectivity: 0,
	};

	for (const [facet, level] of Object.entries(facetLevels)) {

		const adjustmentSource = adjustments20;

		const adjustment = adjustmentSource[facet]?.[level];

		if (!adjustment) continue;

		for (const key in adjustment) {
			totals20[key] += adjustment[key];
		}
	}


	const relevantTotals = totals20;

	const numberValues = document.getElementById('numberValues');
	const top = Object.entries(relevantTotals)
		.sort((a, b) => a[1] - b[1]) // absteigend sortieren
		.slice(0, Number(numberValues.value));

	return top.map(([key]) => key);
}