const EINZELWERT_TEXTE = {
	selfDirectionThought: {
		pm: [
			'Ich hinterfrage jede Aussage, bevor ich ihr folge, unabhängig davon, wer sie gemacht hat.',
			'Meine Neugier ist kein Hobby, sie ist der Kern dessen, wie ich die Welt begreife.',
			'Ich entwickle eigene Theorien und verteidige sie, auch wenn alle anderen anders denken.',
			'Ich lese, was verboten oder unbequem ist, aus reiner intellektueller Neugier.',
			'Ich hinterfrage Voraussetzungen, bevor ich Schlüsse akzeptiere.',
			'Dogmen jeder Art wecken meinen Widerspruch, nicht aus Trotz, sondern aus Prinzip.',
			'Ich erkläre zu viel, zu lange, zu gerne, weil mir das Denken selbst wichtig ist.',
			'Ich vertraue meinem eigenen Urteil mehr als dem Konsens.',
		],
		ideale: [
			'Erkenntnisfreiheit: Neugier ist heilig. Wer das Denken einschränkt, schadet allen.',
			'Eigendenken: Wer die Gedanken anderer nachdenkt, denkt gar nicht.',
			'Kritik: Wer nicht widerspricht, stimmt zu, und das ist keine neutrale Haltung.',
			'Offenheit: Jede Idee verdient eine Prüfung, bevor sie verworfen wird.',
			'Wahrheitssuche: Was wahr ist, lässt sich zeigen. Was sich nicht zeigen lässt, ist Glaube.',
			'Intellektuelle Redlichkeit: Ich sage, was ich denke, auch wenn es Ärger macht.',
			'Freiheit des Geistes: Ein Verstand in Ketten produziert nur Ketten.',
			'Unabhängigkeit: Ich lasse mich von keiner Schule und keinem Dogma definieren.',
		],
		bindungen: [
			'Es gibt eine Frage, die ich mein ganzes Leben zu beantworten versuche.',
			'Ein Buch, eine Begegnung oder eine Entdeckung hat mein Denken irreversibel verändert.',
			'Ich habe meine überzeugungen gegen alle verteidigt und stehe dazu.',
			'Es gibt jemanden, dem ich beweisen will, dass meine Ideen Wert haben.',
			'Ich suche den Beweis für eine Theorie, die mein Leben verändert hat.',
			'Mein Wissen hat mir mehr Feinde als Freunde eingebracht, und ich Würde nichts zurücknehmen.',
			'Ich habe einmal das Falsche geglaubt und es teuer bezahlt, seitdem prüfe ich alles selbst.',
			'Es gibt etwas, das ich denke und das andere gefährlich finden, und das mich nicht loslässt.',
		],
		makel: [
			'Ich verliere mich in Gedanken, während die Welt um mich herum handelt.',
			'Ich bin überzeugt von der Überlegenheit meiner Analyse, selbst wenn andere recht haben.',
			'Ich hinterfrage alles, manchmal auch die eigene Handlungsfähigkeit.',
			'Ich riskiere zu viel für das Wissen um einer Sache willen.',
			'Meine intellektuelle Arroganz treibt Personen weg, die ich eigentlich schätze.',
			'Ich lehne intuitives Handeln ab und verpasse Chancen, die die Analyse vorbereitet hätte.',
			'Meine Unfähigkeit, einfach zu vertrauen, hält mich von echten Bindungen fern.',
			'Ich erkläre zu viel, zu lange, auch wenn niemand zuhört.',
		],
	},

	selfDirectionAction: {
		pm: [
			'Ich entscheide selbst, was das Beste für mich ist, ohne andere um Erlaubnis zu fragen.',
			'Ich plane mein Leben nach meinen eigenen Vorstellungen, nicht nach fremden Erwartungen.',
			'Ich brauche Raum, der mir gehört, und verteidige ihn.',
			'Ich handle, wann und wie ich es für richtig halte.',
			'Ich folge meinen eigenen Zielen, auch wenn niemand sie versteht.',
			'Ich schränke mich lieber selbst ein als mich von aussen einschränken zu lassen.',
			'Ich lasse mir nicht vorschreiben, wer ich sein soll.',
			'Meine Entscheidungen gehören mir, Konsequenzen eingeschlossen.',
		],
		ideale: [
			'Freiheit: Niemand hat das Recht, mir vorzuschreiben, wie ich zu leben habe.',
			'Eigenständigkeit: Ich bin die Autorin meines Lebens, kein anderer.',
			'Selbstverwirklichung: Was ich aus mir mache, ist das Einzige, das zählt.',
			'Unabhängigkeit: Ich plane ohne Zustimmung einzuholen.',
			'Handlungsfreiheit: Wer bestimmt, wie ich handle, bestimmt, wer ich bin.',
			'Privatheit: Was ich nach aussen gebe, bestimme ich selbst.',
			'Autonomie: Ich trage die Verantwortung für mein Leben, also trage ich auch die Kontrolle.',
			'Selbstbestimmung: Was ich brauche, weiss ich selbst am besten.',
		],
		bindungen: [
			'Ich habe einmal alles aufgegeben, um meinen eigenen Weg zu gehen, und bereue es nicht.',
			'Es gibt jemanden, dem ich zeigen werde, dass mein Weg der richtige war.',
			'Ich habe jemanden verlassen, der mir zu viel vorgeschrieben hat.',
			'Es gibt ein Ziel, das ich mir selbst gesteckt habe und das mir niemand nehmen kann.',
			'Ich schulde einer Person die Erkenntnis, dass das eigene Urteil zählt.',
			'Ich habe einmal gezwungen gehandelt und trage das noch heute.',
			'Jemand hat mir erlaubt, ich selbst zu sein, und ich habe das nie vergessen.',
			'Ich kämpfe für etwas, das niemand ausser mir als lohnenswert betrachtet.',
		],
		makel: [
			'Ich nähre einen Widerwillen gegen jede Form von Abhängigkeit, auch wenn sie mir nützt.',
			'Ich breche Vereinbarungen, wenn ich sie nachträglich für falsch halte.',
			'Ich gebe Verantwortung nicht auf andere, auch wenn ich sie brauchen Würde.',
			'Ich misstraue Führung so grundlegend, dass ich sinnvolle Strukturen sabotiere.',
			'Ich verletze Bindungen, weil ich meine Unabhängigkeit über alles stelle.',
			'Mein Bedürfnis nach Kontrolle über mich selbst macht mich unkooperativ.',
			'Ich entscheide impulsiv, weil Abhängigkeit von Planung mir wie Kontrollverlust erscheint.',
			'Ich übersehe, dass meine Autonomie auf dem Beitrag anderer beruht.',
		],
	},

	stimulation: {
		pm: [
			'Ich brauche neue Eindrücke wie andere Luft brauchen.',
			'Ich bin am lebendigsten, wenn ich etwas zum ersten Mal tue.',
			'Langeweile ist für mich keine Unannehmlichkeit, sie ist unerträglich.',
			'Ich suche das Unbekannte, weil das Bekannte mich nicht mehr interessiert.',
			'Wenn es zu ruhig wird, fange ich an, Dinge zu verändern.',
			'Ich wechsle Richtungen, wenn eine Sache aufhört, mich zu fesseln.',
			'Routine verlangsamt mein Denken.',
			'Das Risiko ist für mich kein Hindernis, es ist ein Anreiz.',
		],
		ideale: [
			'Abenteuer: Wer nie das Unbekannte betritt, hat nie wirklich gelebt.',
			'Wandel: Was sich nicht verändert, stirbt langsam.',
			'Entdeckung: Das Nächste ist immer interessanter als das Letzte.',
			'Lebendigkeit: Ich will spüren, dass ich da bin.',
			'Erfahrung: Wer nichts wagt, erlebt nichts.',
			'Aufbruch: Der Aufbruch ist wichtiger als das Ziel.',
			'Intensität: Ein intensives Jahr schlägt ein bequemes Jahrzehnt.',
			'Neugier: Was ich nicht kenne, will ich kennen.',
		],
		bindungen: [
			'Es gibt einen Ort, den ich noch nicht gesehen habe und der mich zieht.',
			'Eine Begegnung hat alles verändert, weil sie in mir etwas ausgelöst hat, das ich nicht kannte.',
			'Ich habe einmal etwas gewagt, das alle für falsch hielten, und es war die beste Entscheidung.',
			'Es gibt etwas, das ich noch nicht getan habe und dem ich naher kommen will.',
			'Jemand hat mir gezeigt, dass das Unbekannte keine Bedrohung ist, sondern ein Geschenk.',
			'Ich werde die Stadt nie vergessen, in der ich mich zum ersten Mal vollständig lebendig gefühlt habe.',
			'Ich verfolge eine Spur, die ich nicht erklären kann, aber nicht loslassen will.',
			'Ich habe einmal zu lang gezaudert und eine Chance verloren, die sich nicht wiederholt hat.',
		],
		makel: [
			'Ich sabotiere Stabilität, die mir und anderen gut täte.',
			'Ich verspreche mehr als ich halte, weil das Nächste immer naherkommt.',
			'Ich breche Verbindungen, wenn sie anfangen, berechenbar zu werden.',
			'Ich unterschätze das Bewährte, weil es mich nicht mehr überrascht.',
			'Meine Unruhe kostet andere Verlasslichkeit, die sie brauchen.',
			'Ich handle impulsiv und nenne es Mut.',
			'Ich bin in Schulden, finanziellen oder andersartigen, weil ich selten Nein sage zu dem, was mich lockt.',
			'Ich lasse fertige Dinge liegen und fange neue an.',
		],
	},

	hedonism: {
		pm: [
			'Ich geniesse das Beste, was verfügbar ist, und entschuldige mich nicht dafür.',
			'Ich lebe in dem Bewusstsein, dass Genuss kein Luxus ist, sondern ein Bestandteil des Lebens.',
			'Ich investiere Zeit und Mittel in das, was mir Freude bereitet.',
			'Ich nehme mir das Recht, gut zu leben, ohne es mir verdienen zu müssen.',
			'Ich weiss, was mir schmeckt, was mir gutsteht, und was mir Freude bereitet.',
			'Ich schaffe Räume für Genuss und verteidige sie gegen Pflichten.',
			'Ich geniesse das Hier und Jetzt mehr als ich auf das Spätere warte.',
			'Ich halte Freude für eine ernstzunehmende Angelegenheit.',
		],
		ideale: [
			'Lebensfreude: Wer sich kein Vergnügen gönnt, verarmt innerlich.',
			'Genuss: Das Gute zu geniessen ist keine Schwäche, es ist Weisheit.',
			'Wohlbefinden: Was ich für mein Wohlbefinden tue, tue ich auch für meine Umgebung.',
			'Freude: Wer nicht lacht, wenn es Grund gibt zu lachen, vergeudet das Beste am Dasein.',
			'Sinnesfreude: Was sich gut anfühlt, hat seinen Wert.',
			'Präsenz: Das jetzige Erleben ist wichtiger als die spätere Erinnerung.',
			'Lebensqualität: Ich bin nicht hier, um Mangel zu verwalten.',
			'Selbstfürsorge: Wer sich nicht um sich selbst kümmert, kümmert sich bald um niemanden mehr.',
		],
		bindungen: [
			'Es gibt einen Ort oder eine Situation, die mir das Gefühl gibt, vollständig lebendig zu sein.',
			'Jemand hat mir beibracht, dass Genuss keine Schande ist.',
			'Ich habe einmal auf Freude verzichtet und damit nichts gewonnen.',
			'Es gibt etwas, das mir treu geblieben ist, weil es mir immer Freude bereitet.',
			'Ich habe jemandem versprochen, das Leben nicht nur zu erdulden.',
			'Es gibt eine Erfahrung, die ich einmal gemacht habe und nie vergessen werde.',
			'Jemand, der mir wichtig war, hat mir gezeigt, wie man lebt, und ich folge dem noch heute.',
			'Ich schütze meinen Zugang zu dem, was mir gut tut.',
		],
		makel: [
			'Ich bin in Schulden, weil ich Genuss höher stelle als Rücklagen.',
			'Ich verschiebe Pflichten, wenn etwas Angenehmeres lockt.',
			'Ich urteile hart über Personen, die sich keine Freude gönnen.',
			'Mein Appetit ist schwer zu zähmen, auch dort, wo es schadet.',
			'Ich vernachlässige langfristige Ziele zugunsten unmittelbarer Befriedigung.',
			'Ich halte Disziplin für eine Tugend anderer.',
			'Mein Hedonismus macht mich blind für das, was Opfer von mir verlangt.',
			'Ich geniesse auf Kosten von Personen, die für mich arbeiten.',
		],
	},

	achievement: {
		pm: [
			'Mittelmassigkeit ist für mich keine Option, in keiner Hinsicht.',
			'Ich setze mir Ziele, die andere für unrealistisch halten, und arbeite still daran.',
			'Ich lasse mich von Rückschlägen nicht aufhalten, ich verwandle sie in Antrieb.',
			'Ich vergleiche mich mit den Besten, nicht um sie kleinzumachen, sondern um besser zu werden.',
			'Lob ohne echte Leistung dahinter lässt mich kalt.',
			'Mein Können ist kein Zufall, es ist das Ergebnis jahrelanger Konsequenz.',
			'Ich überarbeite, übe und verfeinere, bis es so gut ist, wie ich es mir vorstelle.',
			'Ich erinnere mich an jede Niederlage und weiss, was sie mich gelehrt hat.',
		],
		ideale: [
			'Exzellenz: Wer das Mögliche nicht voll ausschöpft, verschwendet es.',
			'Leistung: Was man sich erarbeitet, gehört einem. Was man geschenkt bekommt, nicht.',
			'Meisterschaft: Der Weg zur Meisterschaft dauert ein Leben.',
			'Ehrgeiz: Ohne den Willen zur Verbesserung ist Stillstand schon Rückgang.',
			'Beweis: Man muss zeigen, was man kann, nicht davon reden.',
			'Selbstuberwindung: Das Hindernis bin ich selbst, und ich überwinde es.',
			'Verdienst: Was ich mir erarbeite, gehört mir.',
			'Kompetenz: Können schützt besser als jede Stellung.',
		],
		bindungen: [
			'Ich habe einmal versagt, als es darauf ankam, und das wird mir nicht wieder passieren.',
			'Es gibt jemanden, dem ich beweisen will, was ich wirklich bin.',
			'Meine Arbeit ist mein Erbe, alles andere ist vergänglich.',
			'Ich werde das Werk vollenden, das mir übertragen oder hinterlassen wurde.',
			'Es gibt einen Rivalen, dessen blosse Existenz mich antreibt.',
			'Ich habe einer Person versprochen, die Besten zu übertreffen.',
			'Ich trage eine Schuld, die ich nur durch Leistung begleichen kann.',
			'Ich kämpfe darum, der Beste meines Fachs zu werden, ohne Abkürzungen.',
		],
		makel: [
			'Mein Stolz macht es mir unmöglich, Schwäche zuzugeben.',
			'Versagen destabilisiert mich auf eine Weise, die andere nicht verstehen.',
			'Ich opfere Bindungen dem Ehrgeiz und merke es zu spät.',
			'Ich sehe Personen als Mittel zu meinen Zielen.',
			'Ich bin eifersuchtig auf überlegenheit und handle das schlecht aus.',
			'Ich dulde keine Mittelmassigkeit in meiner Umgebung.',
			'Ich überarbeite mich und nenne es Disziplin.',
			'Mein Fokus auf Leistung lässt mich das übersehen, was nicht messbar ist.',
		],
	},

	powerDominance: {
		pm: [
			'Ich erkenne sofort, wer in einem Raum wirklich die Kontrolle hat.',
			'Ich suche nicht aktiv nach Führung, sie findet mich.',
			'Ich spreche mit einer Autorität, die schwer zu ignorieren ist.',
			'Ich beobachte jeden Raum und weiss schnell, ob er richtig geführt wird.',
			'Ich erkenne Machtstrukturen, bevor andere sie wahrnehmen.',
			'Ich führe, weil ich es besser kann als die, die es tun.',
			'Wer mir widerspricht, muss es begründen können.',
			'Ich dulde keine Führer, die ihre Rolle nicht verdienen.',
		],
		ideale: [
			'Herrschaft: Die Fähigen sollen führen. Das ist keine Arroganz, das ist Ordnung.',
			'Macht: Wer nicht führt, wird geführt, und ich bin nicht zum Gehorchen gemacht.',
			'Kontrolle: Ohne Kontrolle gibt es kein Ziel, nur Chaos.',
			'Führung: Wer Verantwortung trägt, muss auch Entscheidungen treffen dürfen.',
			'Einfluss: Wirkung setzt Macht voraus.',
			'Stärke: Wer schwach ist, kann niemanden schützen.',
			'Durchsetzung: Was richtig ist, muss auch umgesetzt werden.',
			'Autorität: Echte Autorität entsteht nicht durch Titel, sondern durch Handeln.',
		],
		bindungen: [
			'Es gibt eine Position oder Rolle, die mir gehört, und ich kämpfe darum.',
			'Ich habe einmal Kontrolle verloren. Das passiert mir nicht wieder.',
			'Ich werde meine Leute schützen, auf meine Art und mit meinen Mitteln.',
			'Es gibt jemanden, dem ich zeigen werde, wer hier die Entscheidungen trifft.',
			'Ich habe einmal jemanden führen lassen, der es nicht konnte, und die Folgen getragen.',
			'Ich kämpfe um einen Einfluss, der mir zu Unrecht abgesprochen wird.',
			'Jemand hat mir einmal Macht gegeben und ich habe sie gut genutzt, seitdem weiss ich, wofür sie gut ist.',
			'Es gibt eine Entscheidung, die ich allein treffe, weil ich der Einzige bin, dem ich vertraue.',
		],
		makel: [
			'Ich sehe in jedem eine potenzielle Bedrohung meiner Position.',
			'Mein Kontrollimpuls zerstört Beziehungen, bevor sie sich entwickeln können.',
			'Ich unterdrücke Widerspruch, auch wenn er berechtigt ist.',
			'Ich führe durch Einschüchterung, wenn überzeugen scheitert.',
			'Meine Notwendigkeit zu dominieren macht mich zu Verbindungen unfähig.',
			'Ich opfere Gerechtigkeit zugunsten von Kontrolle.',
			'Ich nehme Kritik als Angriff wahr und reagiere entsprechend.',
			'Ich vertraue niemandem genügend, um wirklich zu delegieren.',
		],
	},

	powerResources: {
		pm: [
			'Ich weiss genau, wer was hat und was das wert ist.',
			'Materielle Sicherheit ist für mich kein Ziel, sie ist die Voraussetzung für alles andere.',
			'Ich baue auf, was mir gehört, und verliere es nicht leichtfertig.',
			'Ich schätze, was vorhanden ist, bevor ich daran denke, was fehlt.',
			'Ich kenne den Wert von Dingen, nicht nur den Preis.',
			'Wer nichts hat, kann nichts tun. Deshalb sorge ich dafür, dass ich etwas habe.',
			'Ich investiere in das, was Bestand hat.',
			'Ich kontrolliere meine Mittel, bevor ich Ziele verfolge.',
		],
		ideale: [
			'Ressourcen: Wer keine Mittel hat, hat keine Optionen.',
			'Vermögen: Was ich aufgebaut habe, schützt mich und die, die bei mir sind.',
			'Besitz: Was mir gehört, kann mir niemand nehmen.',
			'Absicherung: Sicherheit ist das Fundament, auf dem alles andere steht.',
			'Akkumulation: Je mehr ich habe, desto mehr kann ich tun.',
			'Wirtschaft: Wer gut haushält, hält länger durch.',
			'Kontrolle über Mittel: Wer die Ressourcen hält, hält die Möglichkeiten.',
			'Unabhängigkeit durch Vermögen: Geld befreit mehr als jede Ideologie.',
		],
		bindungen: [
			'Ich habe einmal alles verloren und weiss seitdem, was Besitz wirklich bedeutet.',
			'Es gibt etwas, das ich aufgebaut habe und das ich um jeden Preis schütze.',
			'Jemand hat mir übertragen, was er hatte, und ich trage die Verantwortung dafür.',
			'Ich kämpfe darum, meiner Gemeinschaft Mittel zu geben, die sie braucht.',
			'Ich schulde jemandem das, was ich heute habe.',
			'Es gibt einen Zustand der Armut oder des Mangels, in den ich nie zurückkehren will.',
			'Was ich besitze, hat eine Geschichte, die ich nicht vergessen werde.',
			'Ich verwalte etwas, das größer ist als ich selbst.',
		],
		makel: [
			'Ich messe Personen nach ihrem Nutzen für meine Ziele.',
			'Ich halte Ressourcen zurück, die anderen helfen Würden.',
			'Ich misstraue Grosszügigkeit, weil ich sie für Manipulation halte.',
			'Ich investiere zu viel in Absicherung und zu wenig in das Leben.',
			'Ich verliere Beziehungen, weil ich alles durch den Filter von Wert und Kosten bewerte.',
			'Ich bin bereit, ethische Grenzen zu übertreten, wenn die Mittel es verlangen.',
			'Mein Fokus auf Besitz lässt mich das übersehen, was sich nicht anhäufen lässt.',
			'Ich klammere mich an das, was ich habe, auch wenn es mich zurückhält.',
		],
	},

	face: {
		pm: [
			'Ich weiss, wie ich auf andere wirke, und das ist keine Eitelkeit, das ist Kompetenz.',
			'Ich verteidige meinen Ruf aktiv, weil er mir gehort.',
			'Ich halte mich an soziale Erwartungen, die meinen Status absichern.',
			'Ich achte darauf, wer mich sieht und wie.',
			'Ich vermeide öffentliche Niederlagen mit mehr Aufwand als private.',
			'Ich unterscheide sehr genau, was ich nach innen und was ich nach aussen zeige.',
			'Wie ich wahrgenommen werde, entscheidet über meinen Spielraum.',
			'Ich schaffe und bewahre ein Bild von mir, das mir Raum gibt.',
		],
		ideale: [
			'Ansehen: Was andere von mir denken, bestimmt, was ich tun kann.',
			'Würde: Ich bewahre meine Haltung, auch wenn es mich etwas kostet.',
			'Ruf: Ein guter Ruf ist schwer zu verdienen und leicht zu verlieren.',
			'Ehre: Was man tut, soll dem entsprechen, was man sagt zu sein.',
			'Oeffentliches Bild: Wie ich erscheine, ist Teil dessen, was ich bin.',
			'Status: Anerkennung ist keine Eitelkeit, sie ist soziales Kapital.',
			'Repräsentation: Ich vertrete etwas, und das tue ich mit Haltung.',
			'Makellosigkeit: Was ich von mir zeige, soll stimmen.',
		],
		bindungen: [
			'Ich habe einmal meinen Ruf beschädigt und weiss, was das kostet.',
			'Es gibt jemanden, vor dem ich in gutem Ansehen stehen will, komme was wolle.',
			'Ich verteidige den Ruf einer Person, die mir wichtig ist.',
			'Ich trage einen Namen oder eine Zugehörigkeit, die ich nicht beschmutzen will.',
			'Jemand hat mir Respekt entgegengebracht, den ich zu verdienen versuche.',
			'Ich habe einmal jemanden durch Unachtsamkeit blosgestellt und bereue das.',
			'Es gibt eine Gemeinschaft, deren Ansehen von meinem Verhalten abhängt.',
			'Ich kämpfe darum, als das gesehen zu werden, was ich wirklich bin.',
		],
		makel: [
			'Ich vermeide echte Nähe, weil sie meinen Status gefährden könnte.',
			'Ich Lüge oder beschönige, um mein Bild zu schützen.',
			'Ich behandle andere schlecht, wenn niemand zuschaut.',
			'Mein Bedürfnis nach Anerkennung macht mich manipulierbar.',
			'Ich opfere das Richtige für das Angemessene.',
			'Ich messe den Wert einer Handlung daran, ob sie gesehen wird.',
			'Ich fürchte Blamage mehr als tatsächlichen Schaden.',
			'Mein Selbstbild hängt so sehr von aussen ab, dass ich mich selbst nicht kenne.',
		],
	},

	securityPersonal: {
		pm: [
			'Ich kenne meine Fluchtwege, bevor ich einen unbekannten Ort betrete.',
			'Ich bereite mich auf Bedrohungen vor, die wahrscheinlich nie eintreten.',
			'Bevor ich vertraue, prüfe ich gründlich und ohne Eile.',
			'Ich trage immer etwas bei mir, das mir Sicherheit gibt.',
			'Ich schütze meine Nächsten so, wie ich selbst geschützt sein wollte.',
			'Unbekannte Personen sind für mich zunächst unbekannte Risiken.',
			'Meine Grenzen sind klar gesetzt und ich verteidige sie ruhig.',
			'Ich handle nicht, wenn ich die Lage nicht einschätzen kann.',
		],
		ideale: [
			'Selbsterhaltung: Wer sich nicht selbst schützt, kann niemanden anderen schützen.',
			'Absicherung: Wer nicht plant, vertraut dem Zufall, das tue ich nicht.',
			'Schutz: Die Pflicht gegenüber meinen Nächsten steht über vielem anderem.',
			'Vorsicht: Ein kluger Kopf schützt besser als ein kuhner.',
			'Vorbereitung: Das Schlimmste anzunehmen schützt vor dem Schlimmsten.',
			'Kontrolle: Was ich kontrollieren kann, werde ich kontrollieren.',
			'Unversehrtheit: Wer gesund bleibt, kann länger kämpfen.',
			'Besonnenheit: Risikobereitschaft ohne Planung ist Leichtsinn.',
		],
		bindungen: [
			'Ich habe Gefahr erlebt und weiss, wie sie sich anfühlt, bevor sie einschlägt.',
			'Es gibt jemanden, für dessen Sicherheit ich alles tue.',
			'Ich habe einmal versagt, jemanden zu schützen, das wird mir nicht wieder passieren.',
			'Ich trage eine Verantwortung für Personen, die von mir abhängig sind.',
			'Ich baue Schutz auf, weil ich weiss, was passiert, wenn er fehlt.',
			'Es gibt eine Bedrohung, auf die ich mich seit langer Zeit vorbereite.',
			'Jemand hat mich in einem Moment des Risikos geschützt, und das vergesse ich nicht.',
			'Ich habe einmal Sicherheit als selbstverständlich behandelt und den Preis gezahlt.',
		],
		makel: [
			'Ich lehne Risiken ab, die mir eigentlich zugutekommen Würden.',
			'Mein Schutzdrang macht mich kontrollierend gegenüber denen, die ich liebe.',
			'Ich misstraue reflexartig und verpasse dadurch echte Chancen.',
			'Meine Vorsicht wirkt auf andere wie Engstirnigkeit, manchmal zurecht.',
			'Ich verhindere bei anderen Risiken, die sie eingehen sollten.',
			'Ich lasse Chancen verstreichen, weil das Risiko unkalkulierbar erscheint.',
			'Mein Sicherheitsbedürfnis macht mich zur Bremse.',
			'Ich vertraue niemandem genug, um echte Unterstützung anzunehmen.',
		],
	},

	securitySocietal: {
		pm: [
			'Ich engagiere mich für Strukturen, die allen zugutekommen.',
			'Ich halte soziale Ordnung für eine Errungenschaft, keine Selbstverständlichkeit.',
			'Ich unterstütze Institutionen, die das Gemeinwohl schützen.',
			'Ich handle im Bewusstsein, dass meine Entscheidungen andere betreffen.',
			'Ich habe das größere Bild im Blick, nicht nur meine eigene Lage.',
			'Ich halte Gemeinschaft für stark genug, um Einzelne zu tragen.',
			'Ich sorge mich um das, was passiert, wenn Strukturen wegfallen.',
			'Ich verteidige die Ordnung, von der andere nicht wissen, wie viel sie ihnen gibt.',
		],
		ideale: [
			'Gemeinschaftssicherheit: Was alle schützt, schützt auch mich.',
			'Stabilität: Gesellschaftliche Ordnung entsteht nicht von selbst.',
			'Verlasslichkeit der Strukturen: Wer sich auf nichts verlassen kann, kann nichts aufbauen.',
			'Schutz des Gemeinwohls: Was die Gemeinschaft hält, hält alle.',
			'Ordnung: Was geregelt ist, kann sich nicht auflosen.',
			'Sicherheit für alle: Sicherheit für einige ist keine Sicherheit.',
			'Solidarität: Wer fällt, sollte aufgefangen werden.',
			'Gesellschaftlicher Zusammenhalt: Was uns verbindet, schützt uns.',
		],
		bindungen: [
			'Ich habe gesehen, wie schnell eine Ordnung zerfällt, und weiss, was dann passiert.',
			'Ich setze mich für eine Gemeinschaft ein, die mich einmal aufgefangen hat.',
			'Es gibt eine Institution oder Struktur, die ich verteidigen werde.',
			'Ich bin jemandem verpflichtet, der mir gezeigt hat, was Zusammenhalt bedeutet.',
			'Ich kämpfe für etwas, das größer ist als mein persönlicher Nutzen.',
			'Ich habe einmal erlebt, wie es ist, wenn niemand da ist, und will das nicht wieder.',
			'Es gibt eine Gemeinschaft, deren Fortbestand von dem abhängt, was ich tue.',
			'Ich halte ein Versprechen, das ich gegenüber etwas größerem als mir selbst gegeben habe.',
		],
		makel: [
			'Ich opfere das Individuum für das Kollektiv, ohne es zu bemerken.',
			'Ich verteidige Strukturen, die längst ungerecht geworden sind.',
			'Mein Vertrauen in Institutionen macht mich blind für ihren Missbrauch.',
			'Ich stelle gesellschaftliche Erwartungen über das, was wirklich stimmt.',
			'Ich passe mein Verhalten so stark dem Kollektiv an, dass ich mich selbst verliere.',
			'Ich dulde Ungerechtigkeit, wenn sie der Stabilität dient.',
			'Ich halte an Ordnungen fest, die mir schaden, weil die Alternative unbekannt ist.',
			'Ich bin so sehr auf das Grosse konzentriert, dass ich das Kleine übersehe.',
		],
	},

	tradition: {
		pm: [
			'Ich halte Bräauche und überlieferungen für einen Faden, der Generationen verbindet.',
			'Ich ehre, was meine Vorfahren bewahrt haben, auch wenn ich nicht immer verstehe warum.',
			'Ich gebe weiter, was mir gegeben wurde.',
			'Ich vertraue dem, was sich über lange Zeit bewahrt hat.',
			'Ich halte Rituale für mehr als Symbol, sie tragen etwas.',
			'Ich sehe im Alten nicht das Vergangene, sondern das Bewahrte.',
			'Ich handle im Geist derer, die vor mir waren.',
			'Was überliefert wurde, hat einen Grund, der nicht immer sichtbar ist.',
		],
		ideale: [
			'Tradition: Was die Vorfahren bewahrt haben, hat einen Grund.',
			'Kontinuität: Was sich nicht überträgt, geht verloren.',
			'Erbe: Was mir gegeben wurde, gebe ich weiter.',
			'Verwurzelung: Wer seine Wurzeln kennt, weiss, wer er ist.',
			'überlieferung: Wissen, das mündlich oder symbolisch weitergegeben wird, ist nicht weniger wahr.',
			'Pietät: Ehrerbietung gegenüber dem, was war, ist keine Schwäche.',
			'Gemeinschaftsgedächtnis: Was wir teilen, definiert uns.',
			'Bewahrung: Was gut ist, sollte nicht dem Wandel zum Opfer fallen.',
		],
		bindungen: [
			'Ich pflege eine Tradition, die mir wichtige Personen übermittelt haben.',
			'Es gibt einen Brauch oder ein Ritual, das mich mit denen verbindet, die nicht mehr da sind.',
			'Ich habe versprochen, etwas weiterzugeben, das mir anvertraut wurde.',
			'Es gibt eine überlieferung, die ich verteidigen werde, auch wenn ich allein stehe.',
			'Jemand hat mir gezeigt, was es bedeutet, Teil von etwas zu sein, das länger besteht als das eigene Leben.',
			'Ich folge einem Weg, den andere vor mir gegangen sind, und das gibt mir Halt.',
			'Es gibt eine Gemeinschaft, deren Gedächtnis ich trage.',
			'Ich habe einmal eine Tradition gebrochen und die Leere später verstanden.',
		],
		makel: [
			'Ich halte an Traditionen fest, die längst mehr schaden als nützen.',
			'Ich verweigere Wandel, auch wenn er notwendig wäre.',
			'Ich erwarte von anderen, Bräauche einzuhalten, die ihnen nichts bedeuten.',
			'Ich verteidige das Alte um seiner selbst willen.',
			'Meine Verwurzelung in der Vergangenheit hält mich vom Jetzt fern.',
			'Ich urteile hart über die, die sich vom überkommenen löesen.',
			'Ich opfere das Richtige für das Herkömmliche.',
			'Meine Ehrerbietung gegenüber Traditionen macht mich unbeweglich.',
		],
	},

	conformityRules: {
		pm: [
			'Ich halte Regeln für die Grundlage, auf der Gemeinschaft funktioniert.',
			'Ich befolge Gesetze und Vorschriften, auch wenn sie mich einschränken.',
			'Ich handle im Rahmen dessen, was vereinbart und gültig ist.',
			'Ich vertraue darauf, dass Regeln einen Grund haben, den ich nicht immer kenne.',
			'Ich halte Verpflichtungen ein, weil sie mich binden, ob ich sie mag oder nicht.',
			'Ich weiss, was von mir erwartet wird, und handle entsprechend.',
			'Ich vermeide, was gegen offizielle Erwartungen verstösst.',
			'Was geregelt ist, halte ich ein, was ungeklärt ist, kläre ich.',
		],
		ideale: [
			'Regelgebundenheit: Was für alle gilt, muss für alle gelten.',
			'Verpflichtung: Wer Regeln akzeptiert, muss ihnen folgen.',
			'Ordnung durch Normen: Was geregelt ist, kann nicht beliebig ausgelegt werden.',
			'Verlasslichkeit: Wer Regeln bricht, wird unberechenbar.',
			'Gemeinschaftsvertrag: Was wir gemeinsam vereinbart haben, bindet uns.',
			'Rechtsstaatlichkeit: Wer das Recht achtet, schützt alle.',
			'Disziplin: Regeln sind nicht Einschränkung, sie sind Struktur.',
			'Fairness durch Gleichbehandlung: Wer Regeln macht, muss sie selbst einhalten.',
		],
		bindungen: [
			'Ich folge einer Ordnung, der ich mich freiwillig unterworfen habe.',
			'Es gibt Regeln, die mich beschützt haben, und ich gebe das zurück.',
			'Ich habe einmal Regeln gebrochen und die Konsequenzen für andere getragen.',
			'Jemand hat mir vertraut, weil ich verlasslich war, und das will ich bleiben.',
			'Es gibt eine Institution, deren Regeln ich achte, weil ich ihren Sinn verstehe.',
			'Ich verteidige die Ordnung, auch wenn sie mir persönlich im Weg steht.',
			'Ich habe von einer Ordnung profitiert und stehe in der Pflicht, sie zu unterstützen.',
			'Ich folge einem Versprechen, das ich gegeben habe.',
		],
		makel: [
			'Ich befolge Regeln, auch wenn sie offensichtlich falsch sind.',
			'Ich melde oder verurteile andere, wenn sie aus Notwendigkeit abweichen.',
			'Meine Regelgebundenheit macht mich starr in Situationen, die Urteilsvermögen erfordern.',
			'Ich schütze die Form, wenn der Inhalt längst verloren ist.',
			'Ich nutze Regeln, um Unbequemes zu vermeiden.',
			'Ich verweigere Flexibilität, die der Gerechtigkeit dienen Würde.',
			'Ich folge Regeln, die mir schaden, ohne sie zu hinterfragen.',
			'Ich urteile hart über die, die ausbrechen, auch wenn sie recht hatten.',
		],
	},

	conformityInterpersonal: {
		pm: [
			'Ich vermeide es, andere zu stören, zu verletzen oder ihnen im Weg zu sein.',
			'Ich passe mein Verhalten dem an, was für andere angenehm ist.',
			'Ich halte Rücksichtnahme für eine Grundform des Respekts.',
			'Ich handle so, dass niemand, der nichts damit zu tun hat, darunter leidet.',
			'Ich lasse Streit vermeiden, wo er vermieden werden kann.',
			'Ich zeige meine Haltung, ohne andere zu überwältigen.',
			'Ich bin zurückhaltend, nicht weil ich nichts zu sagen hätte, sondern weil es gerade passt.',
			'Ich nehme Rücksicht, ohne mich dafür zu entschuldigen.',
		],
		ideale: [
			'Rücksichtnahme: Was mir nicht gehört, lasse ich in Ruhe.',
			'Harmonie: Wer unnötig schadet, macht sich und anderen das Leben schlechter.',
			'Respekt: Die Würde anderer ist keine Verhandlungssache.',
			'Anpassungsfähigkeit: Wer sich nicht anpassen kann, kann nicht zusammenleben.',
			'Soziale Verträglichkeit: Wie ich handle, bestimmt, wie wir miteinander auskommen.',
			'Friedfertigkeit: Konflikte, die vermieden werden können, sollen vermieden werden.',
			'Zurückhaltung: Nicht alles, was ich denke, muss gesagt werden.',
			'Anstand: Verhalten, das anderen schadet, ohne sie zu betreffen, hat keinen Platz.',
		],
		bindungen: [
			'Ich lebe unter Personen, auf die ich Rücksicht nehme, weil ich sie kenne.',
			'Jemand hat mir gezeigt, was es bedeutet, wenn Harmonie verletzt wird.',
			'Ich habe einmal jemanden durch mein Verhalten verletzt und das nicht vergessen.',
			'Ich halte eine Gemeinschaft zusammen, indem ich unnötige Reibung vermeide.',
			'Es gibt Personen, für die ich mich zurücknehme, weil es richtig ist.',
			'Jemand hat mir Vertrauen geschenkt, das ich nicht durch ruckslichtsloses Verhalten zerstören will.',
			'Ich habe Konflikte entstehen sehen, die vermeidbar gewesen wären.',
			'Ich handle so, dass ich niemanden in eine Lage bringe, die er nicht will.',
		],
		makel: [
			'Ich vermeide Konflikte auch dort, wo sie nötig wären.',
			'Ich sage nicht, was ich denke, um die Atmosphäre zu schützen.',
			'Ich lasse mich übersehen, weil ich mich nicht aufdrängen will.',
			'Meine Rücksichtnahme macht mich unlesbar für andere.',
			'Ich opfere Ehrlichkeit für Harmonie.',
			'Ich passe mich so weit an, dass ich mich selbst verliere.',
			'Ich halte Frieden auf Kosten derer, die es vertreten könnte.',
			'Mein Wunsch, niemandem zur Last zu fallen, macht mich unsichtbar.',
		],
	},

	humility: {
		pm: [
			'Ich weiss, dass ich ein kleiner Teil von etwas viel Größerem bin.',
			'Ich stelle mich nicht über andere, auch wenn ich es könnte.',
			'Ich erkenne meine Grenzen an und halte das für eine Stärke.',
			'Ich brauche keine Bühne, um zu wirken.',
			'Ich messe mich nicht an anderen, weil das kein sinnvoller Massstab ist.',
			'Ich trete zurück, wenn jemand besser geeignet ist.',
			'Ich erkenne, was mir gegeben wurde, und bin dankbar dafür.',
			'Ich lebe im Bewusstsein, dass meine Bedeutung relativ ist.',
		],
		ideale: [
			'Bescheidenheit: Wer weiss, was er ist, muss es anderen nicht beweisen.',
			'Demut: Das Eingestehen von Grenzen ist kein Versagen, es ist Ehrlichkeit.',
			'Zurückhaltung: Ich gebe nur das von mir preis, was mir wichtig ist.',
			'Genugsamkeit: Wer weiss, wann es genug ist, hat mehr als wer immer mehr will.',
			'Stille Wirkung: Die lauteste Stimme ist selten die klugste.',
			'Dienst: Was ich tue, zählt. Nicht wofür ich bekannt bin.',
			'Dankbarkeit: Was ich habe, wurde mir ermöglicht, nicht nur verdient.',
			'Masshalten: Wer mehr beansprucht als ihm zusteht, schwäecht das Ganze.',
		],
		bindungen: [
			'Jemand hat mich gelehrt, dass Größe sich nicht ankündigt.',
			'Ich erinnere mich an einen Moment, in dem ich überheblich war, und wer mich dabei gesehen hat.',
			'Es gibt jemanden, dessen stilles Wirken mich geprägt hat.',
			'Ich schulde jemandem Dankbarkeit für etwas, das ich nicht selbst erarbeitet habe.',
			'Ich habe einmal Anerkennung verloren und dabei gelernt, dass sie nicht zählt.',
			'Ich lebe im Bewusstsein dessen, was mir gegeben wurde und was ich weitergeben soll.',
			'Es gibt eine Größe, die ich nie erreichen werde, und das ist in Ordnung.',
			'Ich hüte etwas im Verborgenen, das nie gesehen werden wird.',
		],
		makel: [
			'Ich beschneide mich selbst dort, wo Mut gefragt wäre.',
			'Ich nehme nicht, was mir zusteht, aus Angst, anmassend zu wirken.',
			'Meine Zurückhaltung macht mich zum Hindernis für das, was ich anstrebe.',
			'Ich unterschätze mich und hindere damit andere, mir zu vertrauen.',
			'Ich lasse mich übergehen, obwohl ich besser könnte.',
			'Meine Bescheidenheit wird von anderen als Zustimmung gelesen.',
			'Ich verweigere Verantwortung, die mir zugekommen wäre.',
			'Ich halte Zurückhaltung für Tugend, auch wenn sie mich und andere schwächt.',
		],
	},

	benevolenceDependability: {
		pm: [
			'Ich bleibe auch dann, wenn es schwierig wird.',
			'Ich halte Versprechen, weil ich weiss, was es bedeutet, wenn jemand es nicht tut.',
			'Wer auf mich zählt, kann das.',
			'Ich bin für die da, denen ich mich verpflichtet fühle, ohne zu rechnen.',
			'Ich erscheine, auch wenn es bequemer wäre, fernzubleiben.',
			'Ich folge durch, was ich begonnen habe.',
			'Meine Verlasslichkeit ist kein Versprechen, es ist eine Tatsache.',
			'Ich lasse niemanden, dem ich etwas schulde, im Stich.',
		],
		ideale: [
			'Verlasslichkeit: Wer auf mich zählt, wird nicht enttäuscht.',
			'Treue: Ich halte zu denen, zu denen ich halte, auch wenn es teuer wird.',
			'Verpflichtung: Wer etwas verspricht, muss es halten.',
			'Beständigkeit: Ich bin da, nicht nur wenn es angenehm ist.',
			'Vertrauen: Wer mir vertraut, hat guten Grund dafür.',
			'Zuverlassigkeit: Was ich sage, gilt.',
			'Stabilität für andere: Ich bin der Fels, an dem sich andere orientieren können.',
			'Pflicht: Wer seinen Aufgaben nicht nachkommt, lässt andere im Stich.',
		],
		bindungen: [
			'Es gibt jemanden, dem ich versprochen habe, da zu sein, und das halte ich.',
			'Jemand hat sich auf mich verlassen, als niemand anderes da war.',
			'Ich habe einmal jemanden im Stich gelassen und trage das noch.',
			'Ich bin einer Person oder Sache verpflichtet, die keinen anderen hat.',
			'Meine Verlasslichkeit ist das Einzige, das einer Person Sicherheit gibt.',
			'Jemand hat mir vertraut, und dieses Vertrauen zu behalten ist mir alles.',
			'Ich habe einen Eid geleistet oder ein Wort gegeben, das ich nicht brechen werde.',
			'Es gibt eine Gruppe, deren Bestand davon abhängt, dass ich bleibe.',
		],
		makel: [
			'Ich halte Verpflichtungen ein, auch wenn sie mir schaden.',
			'Ich kann keine Bindungen aufgeben, auch wenn sie längst erloschen sein sollten.',
			'Ich erschöpfe mich durch Verlasslichkeit, die niemand von mir verlangt.',
			'Ich bin so berechenbar, dass andere mich ausnutzen.',
			'Ich lasse mir keine Schwäche erlauben, weil ich fürchte, andere zu enttäuschen.',
			'Meine Treue gilt Personen, die sie nicht verdienen.',
			'Ich opfere mich für Verpflichtungen, die ich längst hätte ablegen können.',
			'Ich helfe, ohne zu fragen, ob die Hilfe erwünscht ist.',
		],
	},

	benevolenceCaring: {
		pm: [
			'Ich spüre, wenn jemand Hilfe braucht, bevor er es ausspricht.',
			'Ich trage die Sorgen anderer, auch wenn sie es nicht wissen.',
			'für Unbekannte bin ich höflich, für meine Personen bin ich bedingungslos da.',
			'Ich erinnere mich an kleine Details über Personen, die mir wichtig sind.',
			'Ich lasse niemanden allein, der nicht allein sein will.',
			'Ich frage mich bei jeder Entscheidung, wen sie betrifft und wie.',
			'Ich gebe nicht halb.',
			'Ich bin am stärksten, wenn jemand anderes es braucht.',
		],
		ideale: [
			'fürsorge: Die wichtigste Kraft ist die, die andere aufrichtet.',
			'Wärme: Wer sich nicht geborgen fühlt, kann nichts aufbauen.',
			'Nähe: Wer sich um andere kümmert, ist näher an dem, was zählt.',
			'Prasenz: Da zu sein ist manchmal die stärkste Hilfe.',
			'Hingabe: Was ich tue, tue ich ganz.',
			'Liebe: Nicht die romantische, sondern die, die bleibt, wenn es schwer wird.',
			'Mitgefühl: Wer leidet, verdient Aufmerksamkeit, kein Urteil.',
			'Zugehörigkeit: Niemand sollte allein durch das müssen, was ich tragen kann.',
		],
		bindungen: [
			'Ich Würde alles für die tun, die ich liebe.',
			'Es gibt jemanden, den ich nicht retten konnte, als ich es hätte können.',
			'Meine Nächsten sind der Grund für alles, was ich tue.',
			'Ich werde für jemanden da sein, der niemals an mir gezweifelt hat.',
			'Es gibt eine Person, für die ich Stärke aufbringe, die ich selbst nicht habe.',
			'Ich habe gesehen, was passiert, wenn niemand da ist, und will das nicht wieder.',
			'Ich habe einmal jemanden verlassen, dem ich wichtig war, und kämpfe darum, das wiedergutzumachen.',
			'Es gibt jemanden, der mir etwas bedeutet, das ich nicht in Worte fassen kann.',
		],
		makel: [
			'Ich kann keine Grenzen ziehen, meine fürsorge erschöpft mich.',
			'Ich verteidige Personen aus meinem Kreis, auch wenn sie im Unrecht sind.',
			'Ich stelle die Harmonie meiner Gruppe über das, was eigentlich richtig wäre.',
			'Ich merke nicht, wann fürsorge zur Abhängigkeit wird.',
			'Ich opfere mich für andere und werde unsichtbar.',
			'Ich habe Angst, Personen zu verlieren, und handle deshalb manchmal unklug.',
			'Meine fürsorge richtet sich nach innen, Fremde bleiben unsichtbar.',
			'Ich nehme Leid auf mich, das nicht meins ist, und verliere mich dabei.',
		],
	},

	universalismConcern: {
		pm: [
			'Ich denke bei Entscheidungen an alle, nicht nur an die, die ich kenne.',
			'Gerechtigkeit ist für mich keine Theorie, sie ist ein Handlungsprinzip.',
			'Ich setze mich für die ein, die keine Stimme haben.',
			'Ich hinterfrage, ob das, was mir nützt, anderen schadet.',
			'Ich handle im Bewusstsein, dass alle gleich viel zählen.',
			'Ich nehme Ungerechtigkeit nicht hin, wenn ich etwas ändern kann.',
			'Mir ist das Schicksal von Fremden nicht gleichgültig.',
			'Ich sehe die Welt als einen Ort, für den ich mit verantwortlich bin.',
		],
		ideale: [
			'Gerechtigkeit: Was falsch ist, muss falsch genannt werden, egal wem es nützt.',
			'Gleichheit: Was für mich gilt, gilt auch für die, die ich nicht kenne.',
			'Universelle Würde: Jedes Wesen verdient Achtung.',
			'Eintreten für andere: Wer sich nicht wehren kann, braucht jemanden, der es tut.',
			'Verantwortung für das Ganze: Was ich tue, betrifft mehr als mich.',
			'Frieden: Was Konflikte verursacht, sollte abgebaut werden.',
			'Solidarität ohne Grenzen: Die Gemeinschaft endet nicht dort, wo ich sie kenne.',
			'Weltoffenheit: Was ausserhalb meines Horizonts liegt, gehört dennoch dazu.',
		],
		bindungen: [
			'Ich habe einmal gesehen, wie systematisches Unrecht funktioniert, und das hat mich verändert.',
			'Es gibt eine Gruppe oder ein Wesen, das ich schütze, obwohl es mir fremd ist.',
			'Jemand hat mir gezeigt, was es bedeutet, für andere einzustehen.',
			'Ich trage das Leid von Personen, die ich nie treffen werde, und das ist kein Fehler.',
			'Ich kämpfe für eine Sache, die größer ist als mein persönlicher Nutzen.',
			'Ich habe einmal weggeschaut und das nie vergessen.',
			'Es gibt ein Unrecht, das ich nicht hinnehmen werde, solange ich handeln kann.',
			'Ich schulde einer ungerechten Erfahrung das Versprechen, es besser zu machen.',
		],
		makel: [
			'Ich bin so auf das grosse Ganze konzentriert, dass ich die nahen Bindungen vernachlässige.',
			'Ich moralisiere, wo Zuhören gefragt wäre.',
			'Ich brenne aus im Einsatz für andere.',
			'Ich urteile hart über die, die nicht so handeln wie ich.',
			'Ich trage Schuld für Unrecht, für das ich nicht verantwortlich bin.',
			'Ich vernachlässige mein eigenes Wohlbefinden zugunsten von Fernstehendem.',
			'Ich sehe das Leid der Welt und bin unfähig, loszulassen.',
			'Ich erwarte von anderen ein Mass an Verantwortung, das ich selbst kaum trage.',
		],
	},

	universalismNature: {
		pm: [
			'Ich behandle die natürliche Welt als etwas, das ich nicht besitze, sondern dem ich angehöre.',
			'Ich handle im Bewusstsein, dass ich Teil eines größeren Gleichgewichts bin.',
			'Ich achte auf das, was nicht sprechen kann, aber trotzdem zählt.',
			'Ich nehme weniger, als ich könnte, weil ich weiss, was das bedeutet.',
			'Ich empfinde Verantwortung gegenüber dem, das nicht handeln kann.',
			'Ich sehe Schönheit und Wert in dem, was nicht nützlich ist.',
			'Ich handle so, dass die Welt nach mir nicht ärmer ist.',
			'Ich spüre eine Verbindung zu dem, was nicht erzeugt wurde.',
		],
		ideale: [
			'Naturschutz: Was nicht von uns gemacht wurde, verdient unseren Schutz.',
			'Bewahrung: Die Welt, die wir vorfinden, ist nicht nur unsere.',
			'Gleichgewicht: Was aus dem Lot gerät, kostet alle mehr, als es bringt.',
			'Verbundenheit mit dem Lebenden: Wir sind Teil von etwas, das größer ist als jede Gemeinschaft.',
			'Verantwortung gegenüber dem Nicht-Sprechenden: Wer keine Stimme hat, braucht eine.',
			'Ehrfurcht: Was die Welt hervorbringt, verdient Achtung.',
			'Langzeitdenken: Was wir heute tun, bestimmt, was morgen noch da ist.',
			'Bescheidenheit gegenüber dem Natürlichen: Wir sind nicht das Mass aller Dinge.',
		],
		bindungen: [
			'Es gibt einen Ort in der natürlichen Welt, der mir wichtig ist und den ich schütze.',
			'Ich habe einmal erlebt, wie etwas Unveränderliches unverändert wurde, und das hat mich geformt.',
			'Jemand hat mir die Verbundenheit zur Welt gegeben, die ich nie verloren habe.',
			'Ich trage Verantwortung für das, was nicht für sich selbst sprechen kann.',
			'Es gibt ein Oekosystem, eine Linie, eine Welt, für die ich eintreten werde.',
			'Ich habe eine Wüste gesehen, die einmal Wald war, und weiss, was auf dem Spiel steht.',
			'Meine tiefsten Erfahrungen habe ich nicht in Gebäuden gemacht.',
			'Ich lebe in einem Bewusstsein für das Lebende, das viele nicht mehr haben.',
		],
		makel: [
			'Ich werte Tiere oder Natur höher als Personen, die leiden.',
			'Ich urteile hart über andere, deren Lebensweise ich für schädlich halte.',
			'Mein Idealismus im Naturschutz macht mich in praktischen Fragen unbeweglich.',
			'Ich vernachlässige nahe Bindungen zugunsten von etwas, das nicht um mich trauern Würde.',
			'Ich trage Schuld für Zerstörung, für die ich nicht persönlich verantwortlich bin.',
			'Ich erwarte von anderen ein Mass an Achtsamkeit, das ich selbst kaum einhalte.',
			'Ich lasse mich von der Größe der Aufgabe läehmen.',
			'Ich behandle Personen wie Störfaktoren in einem System, das besser ohne sie wäre.',
		],
	},

	universalismTolerance: {
		pm: [
			'Ich begegne dem, was mir fremd ist, zuerst mit Neugier, nicht mit Abwehr.',
			'Ich halte Andersartigkeit nicht für ein Problem, das gelöst werden muss.',
			'Ich höre zu, bevor ich urteile, auch wenn das unangenehm ist.',
			'Ich unterscheide zwischen dem, was mir nicht gefällt, und dem, was falsch ist.',
			'Ich gebe dem Fremden Raum, auch wenn ich es nicht verstehe.',
			'Ich halte meine eigene Sichtweise für eine unter vielen möglichen.',
			'Ich akzeptiere Personen, deren Weg sich von meinem unterscheidet.',
			'Ich prüfe mein Unbehagen, bevor ich es zur Norm mache.',
		],
		ideale: [
			'Toleranz: Wer anders ist, ist nicht falsch.',
			'Offenheit: Was ich nicht verstehe, kann trotzdem berechtigt sein.',
			'Pluralismus: Viele Wege können zum Gleichen führen.',
			'Inklusion: Wer dazugehört, gehört dazu, unabhängig von Unterschieden.',
			'Verständnis: Wer urteilt, ohne zu verstehen, urteilt falsch.',
			'Akzeptanz: Die Würde anderer hängt nicht von ihrer Aehnlichkeit mit mir ab.',
			'Weltoffenheit: Was ausserhalb meiner Erfahrung liegt, hat trotzdem Wert.',
			'Freiheit vom Urteil: Wer keine Schaden anrichtet, darf anders sein.',
		],
		bindungen: [
			'Ich bin jemandem begegnet, der mein Bild von dem, was normal ist, grundlegend verändert hat.',
			'Es gibt eine Person oder Gruppe, für die ich eingetreten bin, obwohl es mir etwas gekostet hat.',
			'Jemand hat mir gegenüber Toleranz gezeigt, die ich nicht erwartet hatte, und das hat mich geprägt.',
			'Ich habe einmal jemanden ausgegrenzt und die Folgen gesehen.',
			'Es gibt eine Begegnung, die mir gezeigt hat, dass das Unvertraute das Wertvollere sein kann.',
			'Ich schütze jemanden, der in einem Umfeld fremd ist, das ihn nicht akzeptiert.',
			'Ich kämpfe dafür, dass Andersartigkeit kein Ausschlussgrund ist.',
			'Ich trage die Erfahrung, am falschen Ort der Falsche gewesen zu sein.',
		],
		makel: [
			'Ich toleriere auch das, was Grenzen haben sollte.',
			'Ich verurteile jede Form von Intoleranz so stark, dass ich selbst intolerant werde.',
			'Ich verwechsle Toleranz mit Gleichgültigkeit.',
			'Ich weiche Konflikten aus, die ich durch Toleranz rechtfertige.',
			'Ich halte meine Offenheit für universal, obwohl sie ihre Grenzen hat.',
			'Ich urteile schnell über jene, die nicht so tolerant sind wie ich.',
			'Ich akzeptiere Verhalten, das mir oder anderen schadet, um niemanden auszugrenzen.',
			'Meine Toleranz macht mich blind für echte Grenzverletzungen.',
		],
	},

	universalismObjectivity: {
		pm: [
			'Ich suche die Wahrheit, auch wenn sie unbequem ist.',
			'Ich prüfe meine eigenen Annahmen mit dem gleichen Mass wie die anderer.',
			'Ich lasse mich von Belegen leiten, nicht von Erwünschtheit.',
			'Ich halte rationales Denken für eine Form des Respekts gegenüber der Wirklichkeit.',
			'Ich spreche aus, was ich für wahr halte, auch wenn der Raum dagegen ist.',
			'Ich versuche, Dinge zu sehen, wie sie sind, nicht wie ich sie sehen möchte.',
			'Ich korrigiere mich, wenn ich widerlegt werde, ohne mich zu schäemen.',
			'Ich halte Unvoreingenommenheit für eine Pflicht, nicht nur eine Tugend.',
		],
		ideale: [
			'Wahrheit: Was wahr ist, hängt nicht davon ab, ob es angenehm ist.',
			'Objektivität: Wer voreingenommen urteilt, urteilt falsch.',
			'Rationalität: Emotionen sind ein Signal, kein Beweis.',
			'Unvoreingenommenheit: Was ich glaube, muss sich zeigen lassen.',
			'Intellektuelle Redlichkeit: Wer lügt oder beschönigt, beschädigt das Vertrauen.',
			'Klarheit: Was gedacht werden soll, kann auch ausgesprochen werden.',
			'Wissensbasiertes Handeln: Wer weiss, handelt besser als wer glaubt.',
			'Kritische Prüfung: Was standhalt, darf bleiben. Was fällt, gehört korrigiert.',
		],
		bindungen: [
			'Ich habe einmal erlebt, wie Lüge oder Selbstbetrug jemandem geschadet hat, den ich mochte.',
			'Es gibt eine Wahrheit, die ich verteidige, obwohl es einfacher wäre zu schweigen.',
			'Jemand hat mir beigebracht, dass Klarheit eine Gabe ist.',
			'Ich schulde einer Erfahrung das Versprechen, nie wieder wegzuschauen.',
			'Es gibt eine Frage, deren Antwort ich kenne, und die ich nicht verschweigen werde.',
			'Ich habe einmal die Wahrheit verschwiegen und den Schaden getragen.',
			'Ich folge einer Methode, die mir hilft, weniger falsch zu liegen.',
			'Es gibt jemanden, dem ich durch ehrliche Einschätzung geholfen habe, als andere es nicht taten.',
		],
		makel: [
			'Ich verletze andere durch Sachlichkeit, die sie nicht gebraucht haben.',
			'Ich überze von der überlegenheit meiner Analyse, auch wenn ich falsch liege.',
			'Ich halte Gefühle systematisch für weniger wert als Argumente.',
			'Ich verweigere Mitgefühl, wenn die Fakten dagegen sprechen.',
			'Meine Sachlichkeit klingt für andere wie Kälte.',
			'Ich bringe Wahrheiten ein, für die der Moment nicht da ist.',
			'Ich verlasse mich so sehr auf Belege, dass ich intuitive Richtigkeit übersehe.',
			'Ich behalte recht, auch wenn es die Beziehung kostet.',
		],
	},
};

const KOHAERENZ_TEXTE = {
	sehrKoharent: [
		'Alle drei Kernwerte liegen eng beieinander im Schwartz-Kreis. Dieses Profil ist in sich geschlossen und stimmig, die Motivation dieser Person läuft in eine klare Richtung.',
		'Die drei Werte bilden ein kompaktes Bündel ohne innere Spannung. Was diese Person antreibt, zieht an einem Strang.',
		'Ein eng verwobenes Werteprofil, das kaum Raum für innere Konflikte lässt. Konsequenz und Klarheit prägen diesen Charakter.',
	],
	koharent: [
		'Die drei Werte sind miteinander vereinbar, auch wenn leichte Spannungen möglich sind. Das Profil ist insgesamt stimmig und nachvollziehbar.',
		'Dieses Wertetrio bildet eine erkennbare innere Linie, die nur an wenigen Stellen Reibung erzeugt.',
		'Die Kombination macht Sinn, ohne starke Widersprüche zu erzeugen. Es gibt Nuancen, aber kein Zerreissen.',
	],
	gemischt: [
		'Die drei Werte stammen aus unterschiedlichen Bereichen des Schwartz-Kreises und stehen in einer mittleren Spannung. Dieses Profil lebt von der Auseinandersetzung zwischen seinen Motivationen.',
		'Hier treffen Antriebe aufeinander, die nicht immer in dieselbe Richtung zeigen. Das macht den Charakter vielschichtig und manchmal unberechenbar.',
		'Ein gemischtes Profil, das keine leichte Einheit bildet. Die Werte erfordern Aushandlung, keine einfache Verschmelzung.',
	],
	spannungsreich: [
		'Mindestens zwei Werte stehen in strukturellem Widerspruch zueinander. Dieses Profil beschreibt eine Person, die sich ständig zwischen konkurrierenden Antrieben entscheiden muss.',
		'Die Kombination erzeugt echte innere Spannung. Was die Person in einer Dimension anstrebt, arbeitet in einer anderen gegen sie.',
		'Spannungsreich und dramatisch: Dieses Wertetrio beschreibt keinen Charakter ohne Reibung, sondern einen, der von ihr angetrieben wird.',
	],
	konfliktgeladen: [
		'Gegensätzliche Werte treffen hier direkt aufeinander. Das ist kein Fehler, sondern eine der interessantesten Konstellationen: Diese Person trägt einen tiefen inneren Widerspruch in sich.',
		'Werte, die im Schwartz-Kreis auf gegenüberliegenden Seiten stehen, schliessen sich normalerweise aus. Diese Person hat beide verinnerlicht und lebt mit der Spannung.',
		'Eine konfliktgeladene Kombination: Entweder handelt diese Person situationsabhängig nach einem der Werte, oder sie hat eine Art gefunden, den Widerspruch zu leben, der anderen schwer erklärbar ist.',
	],
};
