const BEREICH_TEXTE = {
	OW_hoch: {
		pm: [
			'Ich hinterfrage Annahmen, bevor ich ihnen folge, selbst wenn alle anderen sie für selbstverständlich halten.',
			'Ich brauche neue Eindrücke wie andere Luft brauchen, Stillstand fühlt sich für mich wie langsames Verrotten an.',
			'Wenn ich eine Grenze sehe, frage ich zuerst, wer sie gesetzt hat und warum.',
			'Ich geniesse das Beste, was gerade verfügbar ist, und lasse mir das von niemandem madig machen.',
			'Ich lerne lieber durch eigene Erfahrung als durch fremde Anweisungen.',
			'Regeln interessieren mich vor allem dann, wenn sie erklären, warum etwas so und nicht anders ist.',
			'Ich bin am lebendigsten, wenn ich etwas zum ersten Mal tue.',
			'Ich schränke mich lieber selbst ein als mich von aussen einschränken zu lassen.',
		],
		ideale: [
			'Freiheit: Niemand hat das Recht, mir vorzuschreiben, wie ich zu denken oder zu leben habe.',
			'Neugier: Wer aufhört zu fragen, hört auf zu wachsen.',
			'Lebensfreude: Wer nicht lacht, wenn es Grund zum Lachen gibt, vergeudet das Beste am Dasein.',
			'Eigenständigkeit: Ich vertraue mir selbst mehr als jedem System, das mir sagt, wer ich sein soll.',
			'Abenteuer: Wer nie das Unbekannte betritt, hat nie wirklich gelebt.',
			'Ehrlichkeit mit sich selbst: Lieber eine unbequeme Wahrheit als eine bequeme Lüge.',
			'Erfahrung: Was ich selbst erlebt habe, nimmt mir niemand mehr weg.',
			'Wandel: Was sich nicht verändert, verknochert.',
		],
		bindungen: [
			'Es gibt einen Ort, an dem ich mich zum ersten Mal wirklich frei gefühlt habe, und der zieht mich immer noch.',
			'Jemand hat mir einmal erlaubt, ich selbst zu sein, und ich habe das nie vergessen.',
			'Ich habe einmal alles aufgegeben, um etwas Unbekanntes zu wagen, und bereue es nicht.',
			'Eine Begegnung hat mein Denken so grundlegend verändert, dass ich seitdem ein anderer bin.',
			'Ich habe jemanden verlassen, der mir zu viel vorgeschrieben hat, und das macht mir manchmal noch zu schaffen.',
			'Ich schulde einer Person die Erkenntnis, dass das eigene Urteil mehr zählt als fremde Meinungen.',
			'Es gibt ein Ziel, das ich mir selbst gesteckt habe, das mir niemand stehlen kann.',
			'Jemand hat mir gezeigt, dass Regeln manchmal gebrochen werden müssen, um das Richtige zu tun.',
		],
		makel: [
			'Ich verliere mich in eigene Gedanken, während die Welt um mich herum handelt.',
			'Wenn es zu ruhig wird, sabotiere ich Situationen unbewusst, nur um wieder etwas zu spüren.',
			'Ich verspreche mehr als ich halte, weil neue Ideen die alten Vorsätze verdrängen.',
			'Meine Ungeduld mit Strukturen kostet mich Chancen, die nur durch Beständigkeit erreichbar wären.',
			'Ich lehne Einschränkungen ab, auch wenn sie mir nützen würden.',
			'Ich bin in Schulden, finanziellen oder andersartigen, weil ich selten Nein sage zu dem, was mich lockt.',
			'Meine Begeisterung für das Neue lässt mich das Bewiesene unterschätzen.',
			'Ich halte Loyalität gegenüber Ideen höher als Loyalität gegenüber Personen.',
		],
	},

	OW_niedrig: {
		pm: [
			'Ich warte lieber ab, bis eine Situation sich geklärt hat, bevor ich handle.',
			'Ich bevorzuge das Vertraute, nicht aus Feigheit, sondern weil Bewährtes seinen Grund hat.',
			'Abenteuer um des Abenteuers willen erscheint mir selbstzerstörerisch.',
			'Ich halte Genuss für etwas, das man sich verdienen muss, bevor man ihn sich gönnt.',
			'Ich stelle in Frage, ob das Neue wirklich besser ist als das Alte.',
			'Ungezwungenheit ist für mich keine Tugend, sie ist eine Einladung zu Fehlern.',
			'Ich schätze Klarheit und Voraussagbarkeit mehr als Abwechslung.',
			'Spontanität macht mir kein Vergnügen, sie macht mir Sorgen.',
		],
		ideale: [
			'Besonnenheit: Ein kluger Geist prüft, bevor er springt.',
			'Disziplin: Wer den eigenen Antrieben nachläuft, wird von ihnen geführt, nicht umgekehrt.',
			'Beständigkeit: Was heute funktioniert, sollte nicht leichtfertig aufgegeben werden.',
			'Kontrolle: Wer die eigene Lage nicht kennt, hat sie nicht in der Hand.',
			'Würde: Nicht jeder Impuls verdient Ausdruck.',
			'Ernsthaftigkeit: Wer alles zum Spiel macht, hat nichts wirklich ernst genommen.',
			'Verlasslichkeit: Wer sich selbst im Weg steht, kann anderen keinen Weg zeigen.',
			'Klarheit: Ich weiss, wer ich bin, und brauche keinen Wandel, um das herauszufinden.',
		],
		bindungen: [
			'Ich folge dem, was mir meine Gemeinschaft, meine Tradition oder meine Pflicht aufgetragen hat.',
			'Ich schütze etwas oder jemanden, den Unberechenbarkeit bedrohen könnte.',
			'Es gibt eine stabile Wahrheit in meinem Leben, um die herum sich alles andere angeordnet hat.',
			'Ich lebe für eine Sache oder eine Person, nicht für Erlebnisse.',
			'Jemand hat mir gezeigt, dass Disziplin einen weiter bringt als jede Eingebung.',
			'Ich habe einmal die Kontrolle verloren und trage die Folgen noch heute.',
			'Ich schulde einer Person das Versprechen, den Kopf oben zu behalten, egal was kommt.',
			'Eine Erfahrung mit Chaos hat mir eindrücklich gezeigt, was auf dem Spiel steht.',
		],
		makel: [
			'Ich handle nicht, wenn keine Erlaubnis oder kein klarer Plan vorliegt, auch wenn die Lage es fordern würde.',
			'Ich lehne Risiken ab, die mir eigentlich nützen würden.',
			'Ich bremse andere, wenn ich mir selbst Mut machen müsste.',
			'Ich urteile hart über Personen, die sich Genuss oder Freiheit gönnen.',
			'Meine Ablehnung von Wandel macht mich blind für Chancen, die nur im Unbekannten liegen.',
			'Ich verweigere Flexibilität, die eigentlich Stärke wäre.',
			'Ich misstraue Leichtigkeit so grundlegend, dass ich sie nie zugelassen habe.',
			'Meine Beständigkeit ist manchmal nur ein anderes Wort für Angst.',
		],
	},
	SE_hoch: {
		pm: [
			'Ich beobachte jeden Raum, den ich betrete, und weiss schnell, wer hier das Sagen hat und ob das der Richtige ist.',
			'Mittelmassigkeit ist für mich keine Option, in keiner Hinsicht.',
			'Ich setze mir Ziele, die andere für unrealistisch halten, und arbeite still daran.',
			'Ich lasse mich von Rückschlägen nicht aufhalten, ich verwandle sie in Antrieb.',
			'Ich vergleiche mich mit den Besten, nicht um sie kleinzumachen, sondern um besser zu werden.',
			'Lob ohne echte Leistung dahinter lässt mich kalt.',
			'Ich erkenne sofort, wenn jemand versucht, Einfluss auf mich zu nehmen, bevor ich mir das Recht dazu verdient habe.',
			'Mein Können ist kein Zufall, es ist das Ergebnis von jahrelanger Konsequenz.',
		],
		ideale: [
			'Exzellenz: Wer das Mögliche nicht voll ausschöpft, verschwendet es.',
			'Einfluss: Wer keine Wirkung hat, existiert in den Augen anderer kaum.',
			'Leistung: Was man sich erarbeitet, gehört einem. Was man geschenkt bekommt, nicht.',
			'Ehrgeiz: Ohne den Willen zur Verbesserung ist Stillstand schon der Beginn des Rückgangs.',
			'Ruhm: Wer der Beste ist, soll auch so gesehen werden.',
			'Herrschaft: Die Fähigen sollen führen. Das ist keine Arroganz, sondern Ordnung.',
			'Macht: Wer nicht führt, wird geführt, und ich bin nicht zum Gehorchen gemacht.',
			'Anerkennung: Ich tue nicht so, als wäre es mir egal, was andere von mir denken.',
		],
		bindungen: [
			'Es gibt eine Position oder Rolle, die mir gehört, und ich kämpfe darum.',
			'Ich habe einmal versagt, als es darauf ankam, und das wird mir nie wieder passieren.',
			'Es gibt jemanden, dem ich beweisen will, was ich wirklich bin.',
			'Ich werde das Werk vollenden, das mir übertragen oder hinterlassen wurde.',
			'Meine Arbeit ist mein Erbe, alles andere ist vergänglich.',
			'Es gibt einen Rivalen, dessen blossere Existenz mich antreibt.',
			'Ich habe einer Person versprochen, die Besten zu übertreffen, und das war kein leeres Wort.',
			'Ich trage eine Schuld, die ich nur durch Leistung begleichen kann.',
		],
		makel: [
			'Mein Stolz macht es mir unmöglich, Schwäche zuzugeben oder um Hilfe zu bitten.',
			'Ich sehe in anderen potenzielle Konkurrenten, bevor ich sie als Verbundete sehe.',
			'Versagen destabilisiert mich auf eine Weise, die andere nicht verstehen.',
			'Ich opfere Bindungen dem Ehrgeiz und merke es zu spät.',
			'Ich bin eifersuchtig auf Überlegenheit und handle das schlecht aus.',
			'Ich sehe Personen als Mittel zu meinen Zielen, nicht als Zwecke.',
			'Mein Blick auf andere ist urteilend. Ich dulde keine Mittelmassigkeit in meiner Nähe.',
			'Ich überarbeite mich und nenne es Disziplin.',
		],
	},
	SE_niedrig: {
		pm: [
			'Ich tue, was ich kann, und lasse gut genug sein.',
			'Ansehen ist mir kein erstrebenswertes Ziel, ich möchte geachtet werden, nicht bewundert.',
			'Wenn andere um Einfluss kämpfen, trete ich zurück und warte, bis es vorbei ist.',
			'Ich messe mich nicht an anderen. Mein Massstab liegt in mir selbst.',
			'Wettbewerb erscheint mir als Ablenkung von dem, worauf es wirklich ankommt.',
			'Ich brauche keine Bühne, um zu wirken.',
			'Macht ängstet mich nicht, sie interessiert mich nur nicht.',
			'Ich arbeite lieber im Verborgenen als im Rampenlicht.',
		],
		ideale: [
			'Genugsamkeit: Besser gut genug als erschöpft und perfekt.',
			'Stille: Wer am lautesten spricht, hat nicht unbedingt das Meiste zu sagen.',
			'Bescheidenheit: Wer weiss, was er ist, muss es anderen nicht beweisen.',
			'Dienst: Was zählt, ist was ich getan habe, nicht wofür ich bekannt bin.',
			'Einfachheit: Das Komplizierte ist selten das Richtige.',
			'Zurückhaltung: Ich gebe nur das von mir preis, was mir wichtig ist, nicht das, was beeindruckt.',
			'Gleichmut: Was ich nicht kontrollieren kann, trage ich ohne Aufriss.',
			'Tiefe: Lieber wenig und echt als viel und hohl.',
		],
		bindungen: [
			'Ich lebe für die Personen in meiner Nähe, nicht für die Welt darüber hinaus.',
			'Jemand hat mir gezeigt, dass Bescheidenheit kein Zeichen von Schwäche ist.',
			'Ich verbringe meine Zeit lieber mit Personen als mit Erfolgen.',
			'Es gibt eine stille Arbeit, die ich leiste, und der ich treu bleibe, egal ob sie gesehen wird.',
			'Ich habe einmal erlebt, was Macht mit jemandem macht, den ich mochte, und das habe ich nicht vergessen.',
			'Jemand hat mich so angenommen, wie ich bin, ohne Leistung zu erwarten, das ist mir mehr wert als jeder Ruhm.',
			'Ich schütze etwas Kleines und Unspektakuläres, das mir unendlich viel bedeutet.',
			'Ich habe einmal Ansehen gehabt und verloren, und festgestellt, dass ich es nicht vermisse.',
		],
		makel: [
			'Ich bin so weit zurückgetreten, dass ich unsichtbar geworden bin, auch dort, wo ich hätte wirken können.',
			'Ich unterschätze mich und hindere damit andere daran, mir zu vertrauen.',
			'Ich lasse Chancen verstreichen, weil der Anspruch, sie wahrzunehmen, mir anmassend vorkäme.',
			'Ich gebe Verantwortung nicht auf mich, auch wenn ich gebraucht würde.',
			'Mein Desinteresse an Status macht mich blind für Machtstrukturen, die mich beeinflussen.',
			'Ich handle nicht, wenn Entschlossenheit gefragt wäre, und nenne es Bescheidenheit.',
			'Ich lasse mich von anderen übersehen, obwohl ich mehr könnte.',
			'Mein Rückzug ist manchmal keine Tugend, sondern Bequemlichkeit.',
		],
	},
	BW_hoch: {
		pm: [
			'Ich kenne meine Fluchtwege, bevor ich einen unbekannten Ort betrete.',
			'Ich bereite mich auf Bedrohungen vor, die wahrscheinlich nie eintreten werden.',
			'Bevor ich vertraue, prüfe ich, gründlich und ohne Eile.',
			'Ich handle nicht impulsiv, ich denke erst, dann.',
			'Ich halte mich an Abmachungen, auch wenn es unbequem ist.',
			'Ich kenne die Regeln, die für mich gelten, und ich kenne sie genau.',
			'Was ich schütze, schütze ich ernsthaft.',
			'Ich schätze Personen, die verlasslich sind, mehr als solche, die beeindruckend sind.',
		],
		ideale: [
			'Schutz: Die Pflicht gegenüber meinen Nächsten steht über allem anderen.',
			'Vorsicht: Ein kluger Geist schützt besser als ein kuhner.',
			'Beständigkeit: Was sich bewahrt hat, hat seinen Wert bewiesen.',
			'Ordnung: Was geregelt ist, kann nicht aus den Fugen geraten.',
			'Verlasslichkeit: Ich werde da sein, wenn es darauf ankommt.',
			'Tradition: Was die Vorfahren bewahrt haben, hat einen Grund, der nicht immer auf den ersten Blick erkennbar ist.',
			'Pflicht: Wer seinen Aufgaben ausweicht, lässt andere im Stich.',
			'Vorbereitung: Das Schlimmste anzunehmen schützt vor dem Schlimmsten.',
		],
		bindungen: [
			'Ich habe einmal versagt, jemanden zu schützen, das wird mir nicht wieder passieren.',
			'Ich trage eine Verantwortung für Personen, die von mir abhängig sind.',
			'Es gibt eine Bedrohung, auf die ich mich schon lange vorbereite.',
			'Ich habe Gefahr erlebt und weiss, wie sie sich anfühlt, bevor sie einschlägt.',
			'Es gibt jemanden, für dessen Sicherheit ich alles tü.',
			'Eine Tradition oder Ordnung, die ich hüte, hat mehr Wert als ich selbst.',
			'Ich habe Chaos erlebt und weiss, was passiert, wenn Schutz fehlt.',
			'Ich folge einem Versprechen, das ich gegeben habe, auch wenn niemand mehr darüber wacht.',
		],
		makel: [
			'Ich lehne Risiken ab, die mir eigentlich zugutekommen würden.',
			'Mein Schutzdrang macht mich kontrollierend gegenüber denen, die ich liebe.',
			'Ich misstraue reflexartig und verpasse dadurch echte Chancen.',
			'Ich verhindere bei anderen Risiken, die sie eingehen sollten.',
			'Meine Vorsicht wirkt auf andere wie Engstirnigkeit, manchmal zurecht.',
			'Ich hange an Strukturen, die längst überholt sind.',
			'Ich bringe Neues nicht zum Zuge, weil ich das Vertraute nicht loslassen kann.',
			'Mein Sicherheitsbedürfnis macht mich zur Bremse, wenn schnelles Handeln gefragt wäre.',
		],
	},
	BW_niedrig: {
		pm: [
			'Ich halte mich nicht an Regeln, die keinen einleuchtenden Zweck haben.',
			'Tradition ist für mich eine Erklärung, die noch aussteht, keine Anweisung.',
			'Ich schütze, was mir wichtig ist, auf meine eigene Art, nicht durch Einhaltung von Formen.',
			'Sicherheit kaufe ich mir nicht durch Gehorsamkeit.',
			'Ich finde es beschränkend, wenn Erwartungen wichtiger sind als Ergebnisse.',
			'Was überholt ist, sollte sich ändern, egal wie lange es schon gilt.',
			'Mir ist es gleichgültig, ob mein Weg der übliche ist.',
			'Vorschriften interessieren mich als Beschreibungen, nicht als Befehle.',
		],
		ideale: [
			'Wandel: Was nicht mehr passt, sollte nicht weiter erzwungen werden.',
			'Eigenverantwortung: Ich lasse mich nicht durch Regeln ersetzen, die ich selbst fällen kann.',
			'Bruch: Manchmal ist das Richtige das Ungewohnte.',
			'Befreiung: Was einsperrt, gehört gebrochen, nicht bewahrt.',
			'Wahrheit vor Form: Besser richtig und ungewöhnlich als falsch und anständig.',
			'Beweglichkeit: Was sich bewegen kann, überlebt. Was starr ist, zerbricht.',
			'Erneuerung: Das Neue entsteht nur dort, wo das Alte Platz macht.',
			'Unmittelbarkeit: Was in diesem Moment zählt, zählt mehr als was sich historisch bewährt hat.',
		],
		bindungen: [
			'Ich habe eine Einschränkung hinter mir gelassen, die mich lahmgelegt hat.',
			'Jemand hat mir gezeigt, dass Regeln für die gemacht sind, die sie nicht brauchen.',
			'Es gibt eine alte Ordnung, die ich aufgebrochen habe, und ich stehe dazu.',
			'Ich kämpfe für etwas, das die bestehende Struktur nicht kennt und nicht fördert.',
			'Jemand hat mir erlaubt, anders zu sein, und das hat alles verändert.',
			'Ich habe einmal gesehen, wie Tradition als Waffe eingesetzt wurde, seitdem prüfe ich alles.',
			'Ich schütze jemanden vor einer Ordnung, die ihn zerquetschen würde.',
			'Ich habe Pflicht von Zwang unterscheiden gelernt, und das war kein kleiner Unterschied.',
		],
		makel: [
			'Ich halte mich nicht an Vereinbarungen, wenn ich neue Gründe finde, sie zu umgehen.',
			'Ich unterschätze Strukturen, die mir unsichtbar helfen.',
			'Meine Verachtung für Regeln macht mich unzuverlässig für die, die auf mich setzen.',
			'Ich weiss nicht immer, wann Gehorsam tatsächlich das Richtige wäre.',
			'Ich zertöre, was mich beengt, bevor ich prüfe, was es trägt.',
			'Meine Freiheit kostet andere Sicherheit, die sie brauchen.',
			'Ich nähre einen Widerwillen gegen jede Form von Verpflichtung.',
			'Ich behandle Verlasslichkeit als Eigenschaft anderer, nicht als meine Aufgabe.',
		],
	},
	ST_hoch: {
		pm: [
			'Ich spüre, wenn jemand Hilfe braucht, bevor er es ausspricht.',
			'Ich erinnere mich an kleine Details über Personen, die mir wichtig sind.',
			'Ich bleibe auch dann, wenn es schwierig wird.',
			'für Unbekannte bin ich höflich, für meine Personen bin ich bedingungslos da.',
			'Ich trage die Sorgen anderer, auch wenn sie es nicht wissen.',
			'Ich frage mich bei jeder Entscheidung, wen sie betrifft und wie.',
			'Ich sehe, was übrigbleibt, wenn jemand zur Seite stehen müsste und niemand da ist.',
			'Ich lasse niemanden, dem ich etwas schulde, im Stich, egal zu welchem Preis.',
		],
		ideale: [
			'Fürsorge: Die wichtigste Kraft ist die, die andere aufrichtet.',
			'Gerechtigkeit: Was falsch ist, sollte falsch genannt werden, unabhängig davon, wem es nützt.',
			'Verbundenheit: Wir kommen weiter zusammen als allein, das ist keine Sentimentalität, das ist Tatsache.',
			'Würde: Was wir füreinander tun, ist das Einzige, das wirklich zählt.',
			'Empathie: Ich fühle, was du fühlst, und das verpflichtet mich.',
			'Offenheit: Wer anders ist, ist nicht falsch.',
			'Wärme: Wer sich nicht geborgen fühlt, kann nichts aufbauen.',
			'Hingabe: Ich gebe nicht halb.',
		],
		bindungen: [
			'Ich würde alles für die tun, die ich liebe, das ist keine Übertreibung.',
			'Es gibt jemanden, den ich nicht retten konnte, als ich es hätte können.',
			'Meine Gruppe, meine Gemeinschaft, meine Nächsten sind der Grund für alles.',
			'Ich habe einmal jemanden verlassen, dem ich wichtig war, und kämpfe darum, das wiedergutzumachen.',
			'Ich werde für jemanden da sein, der niemals an mir gezweifelt hat.',
			'Es gibt eine Person, für die ich Stärke aufbringe, die ich selbst nicht habe.',
			'Ich trage die Verantwortung für Personen, die sie mir gegeben haben, und nehme sie ernst.',
			'Ich habe gesehen, was passiert, wenn niemand da ist, und will nicht, dass das wieder geschieht.',
		],
		makel: [
			'Ich kann keine Grenzen ziehen, meine fürsorge erschöpft mich.',
			'Ich verteidige Personen aus meinem Kreis, auch wenn sie im Unrecht sind.',
			'Verrat trifft mich so tief, dass ich nie wieder wirklich vertraue.',
			'Ich stelle die Harmonie meiner Gruppe über das, was eigentlich richtig wäre.',
			'Meine Loyalität ist keine Tugend, wenn sie mich in falsche Konflikte zieht.',
			'Ich opfere mich für andere und werde unsichtbar, und leide still darunter.',
			'Ich merke nicht, wann Fürsorge zur Abhängigkeit wird, in beide Richtungen.',
			'Ich habe Angst, Personen zu verlieren, und handle deshalb manchmal unklug.',
		],
	},
	ST_niedrig: {
		pm: [
			'Ich kümmere mich zuerst um mich selbst, dann um andere, und halte das für ehrlich.',
			'Ich halte Distanz zu Personen, die ich nicht kenne, und das ist keine Kälte.',
			'Ich helfe, wenn ich kann, aber nicht auf Kosten meiner eigenen Ziele.',
			'Mitleid ist kein Handlungsprinzip für mich.',
			'Ich beurteile Situationen nach Fakten, nicht nach Gefühlen.',
			'Ich bin verlasslich gegenüber denen, die mir nahestehen, aber nicht gegenüber allen.',
			'Ich überlasse anderen ihre Entscheidungen und erwarte dasselbe von ihnen.',
			'Universelle fürsorge erscheint mir naiv oder zumindest unerreichbar.',
		],
		ideale: [
			'Eigenverantwortung: Jede Person ist für sich selbst zuständig.',
			'Sachlichkeit: Emotionen sind kein Kompass für kluge Entscheidungen.',
			'Unabhängigkeit: Ich brauche keine Zustimmung, um zu wissen, was richtig ist.',
			'Stärke: Wer sich nicht selbst helfen kann, kann anderen nicht helfen.',
			'Klarheit: Ich verspreche nicht mehr, als ich halte.',
			'Fokus: Wer sich um alles sorgt, sorgt sich um nichts richtig.',
			'Pragmatismus: Was funktioniert, zählt mehr als was schön klingt.',
			'Grenzen: Ich weiss, wo ich ende und andere beginnen.',
		],
		bindungen: [
			'Ich habe gelernt, dass zu viel Nähe teuer bezahlt wird.',
			'Jemand hat mir gezeigt, dass man sich auf sich selbst verlassen muss.',
			'Es gibt Personen, denen ich verpflichtet bin, aber es sind nicht viele.',
			'Ich habe einmal alles für jemanden gegeben und wurde enttäuscht, seitdem halte ich Abstand.',
			'Ich verfolge ein Ziel, für das ich keine Verbundeten brauche.',
			'Was ich liebe, schütze ich, aber ich mache keinen Kult daraus.',
			'Ich schulde jemandem Dankbarkeit, aber ich mache das auf meine eigene stille Weise.',
			'Ich habe gelernt, Gefühle und Entscheidungen voneinander zu trennen.',
		],
		makel: [
			'Ich merke zu spät, wenn jemand meine Unterstützung braucht.',
			'Ich übersehe die Kosten meines Rückzugs für andere.',
			'Meine Sachlichkeit klingt für andere wie Herzlosigkeit.',
			'Ich halte mich aus Konflikten heraus, in denen mein Eingreifen etwas geändert hätte.',
			'Ich verliere Bindungen, weil ich nicht zeige, was sie mir bedeuten.',
			'Ich rechtfertige Gleichgültigkeit als Stärke.',
			'Ich übersehe, dass meine Unabhängigkeit auf dem Beitrag anderer beruht.',
			'Ich trenne mich von Personen, bevor ich weiss, ob es nötig gewesen wäre.',
		],
	},
};
const SPANNUNGS_TEXTE = {
	OW_BW: [
		'Freiheit und Sicherheit ziehen diese Person in entgegengesetzte Richtungen. Was sie anzieht, ist genau das, was ihr Gleichgewicht bedroht.',
		'Der Wunsch, selbst zu bestimmen, und der Wunsch, ein stabiles Fundament zu haben, schliessen sich für diese Person gegenseitig aus, zumindest glaubt sie das.',
		'Diese Person weiss, was sie will, aber nicht immer, ob das, was sie will, ihr auch bekommt. Freiheit und Schutz verhandeln in ihr ständig miteinander.',
		'Zwischen Aufbruch und Ankerpunkt. Diese Person lebt mit der Spannung, dass das eine immer auf Kosten des anderen geht.',
		'Diese Person folgt dem Neuen und misstraut dem Vertrauten zugleich, oder umgekehrt. Dieser innere Widerspruch formt ihre Entscheidungen mehr als sie zugeben würde.',
	],
	SE_ST: [
		'Eigener Aufstieg und Sorge um andere schliessen sich für diese Person schwieriger aus, als sie sich eingesteht.',
		'Diese Person will etwas leisten und gleichzeitig dazugehören. Beides gelingt selten gleichzeitig, und das weiss sie.',
		'Einfluss und Empathie widersprechen sich in dieser Person auf eine Weise, die sie zwingt, sich immer wieder neu zu entscheiden.',
		'Was für sie zählt, und was für andere zählt, sind selten dasselbe. Diese Person lebt mit dieser Lucke.',
		'Diese Person möchte gewinnen und gleichzeitig gute Verbindungen halten. Dass beides selten zusammengeht, ist ihr ständiger Begleiter.',
	],
};

const ARCHETYP_NAMEN = {
	OW: {
		stark:   ['Der Freie Geist',    'Die Wandernde Seele', 'Der Ungezahlte',       'Der Neugierige'],
		moderat: ['Die Offene Hand',    'Der Sucher',          'Der Bewegliche',        'Der Fragensteller'],
	},
	SE: {
		stark:   ['Der Unerbittliche',  'Der Aufsteiger',    'Der Stratege',          'Der Ehrgeizige'],
		moderat: ['Der Entschlossene',  'Der Beweiser',        'Der Gestalter',       'Der Aufsteiger'],
	},
	BW: {
		stark:   ['Der Hüter',         'Der Wächter',      'Der Beständige',       'Der Schildhalter'],
		moderat: ['Der Verlässliche',   'Der Vorsichtige',     'Der Ordener',         'Der Traditionshüter'],
	},
	ST: {
		stark:   ['Der Fürsorgliche',  'Der Verbundene',      'Der Hingebungsvolle',   'Der Empathische'],
		moderat: ['Der Treue',          'Der Stille Helfer',   'Der Gerechte',          'Der Mittragende'],
	},
};
